import type { Question } from "@/lib/types";

const jsRefs = [{ site: "mdn", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript" }];
const reactRefs = [{ site: "react", url: "https://react.dev" }];
const webRefs = [{ site: "mdn", url: "https://developer.mozilla.org/en-US/docs/Web" }];

/** First authoring wave: the hand-curated quiz catalog. */
export const authoredQuizStubs: Question[] = [
  {
    id: "js-hoisting", track: "quiz", level: "beginner", title: "Explain hoisting in JavaScript", tags: ["javascript", "scope"], status: "ready", canonicalTopic: "hoisting",
    prompt: "What is hoisted, what is not initialized yet, and why does `let` behave differently from `var` before its declaration?",
    hints: ["Separate declaration from initialization.", "Function declarations, `var`, and lexical declarations are not equivalent."],
    approach: "Explain the creation phase first. Contrast function declarations, `var`, and `let`/`const`; then name the temporal dead zone.",
    solution: "Hoisting means declarations are processed before the surrounding code executes. Function declarations are available with their function value. `var` is created and initialized to `undefined`, so reading it early is allowed but usually a bug. `let`, `const`, and `class` bindings are created too, but remain inaccessible in the temporal dead zone until their declaration runs; an early read throws a `ReferenceError`. Prefer `const`/`let` so an accidental early read fails loudly.",
    interviewerNotes: "A strong answer distinguishes declaration from initialization instead of saying that JavaScript 'moves code to the top'.",
    sourceRefs: jsRefs,
    options: [{ id: "a", label: "Every declaration is initialized with its final value before execution" }, { id: "b", label: "Function declarations are initialized, `var` starts as undefined, and `let`/`const` are in the temporal dead zone", correct: true }, { id: "c", label: "Only variables inside functions are hoisted" }, { id: "d", label: "Hoisting only applies in non-strict mode" }],
  },
  {
    id: "js-prototypes", track: "quiz", level: "mid", title: "Prototypal inheritance vs class syntax", tags: ["javascript", "objects"], status: "ready", canonicalTopic: "prototypes",
    prompt: "How does property lookup work through a prototype chain, and what does JavaScript `class` syntax add?",
    hints: ["Objects can delegate to another object.", "Classes are syntax over prototypes, not a separate inheritance model."],
    approach: "Describe own-property lookup, then delegation through `[[Prototype]]`. Contrast shared prototype methods with per-instance fields.",
    solution: "When `obj.name` is read, JavaScript checks `obj`’s own properties, then follows its `[[Prototype]]` chain until it finds the property or reaches `null`. `class` provides familiar syntax for constructor functions, prototype methods, inheritance, and `super`; the runtime model is still prototype delegation. Put shared methods on the prototype so instances do not each allocate a new function, and favor composition when an inheritance tree is not a natural fit.",
    interviewerNotes: "Listen for the lookup chain and the fact that classes are not classical-object copies.", sourceRefs: jsRefs,
    options: [{ id: "a", label: "Classes use a completely separate runtime from prototypes" }, { id: "b", label: "Lookup checks own properties then delegates through the prototype chain; classes are syntax over that model", correct: true }, { id: "c", label: "Every object must inherit from a class" }, { id: "d", label: "Prototype methods are copied into every instance" }],
  },
  {
    id: "dom-event-delegation", track: "quiz", level: "mid", title: "What is event delegation?", tags: ["dom", "events"], status: "ready", canonicalTopic: "event-delegation",
    prompt: "How can one listener handle actions in a changing list, and what checks keep that safe?",
    hints: ["Most DOM events bubble.", "`event.target` may be a nested icon, not the button you expect."],
    approach: "Attach a listener to a stable ancestor, locate the intended control with `closest`, and guard against matches outside the container.",
    solution: "Event delegation attaches one listener to a stable ancestor and uses event bubbling to handle interactions from descendants. For example, a list listener can call `event.target.closest('[data-action]')`, verify that the match is inside the list, and route by `data-action`. It avoids creating a listener for every row and works for rows added later. Do not use it for events that do not bubble without their bubbling counterpart, and be deliberate about `stopPropagation` and nested interactive controls.",
    interviewerNotes: "A practical answer includes `closest()` and does not assume the click target is the button itself.", sourceRefs: webRefs,
    options: [{ id: "a", label: "It copies a listener onto each future child" }, { id: "b", label: "A stable ancestor handles bubbled events from descendants", correct: true }, { id: "c", label: "It prevents all events from bubbling" }, { id: "d", label: "It only works with React synthetic events" }],
  },
  {
    id: "web-cors", track: "quiz", level: "mid", title: "Explain CORS and simple vs preflight requests", tags: ["networking", "security"], status: "ready", canonicalTopic: "cors",
    prompt: "Why can a server receive a cross-origin request that browser JavaScript cannot read? When does the browser send an OPTIONS preflight?",
    hints: ["CORS is a browser read-access policy.", "Non-safelisted methods, headers, or content types trigger a preflight."],
    approach: "Define origin, distinguish request delivery from response visibility, then explain the server headers and credential constraint.",
    solution: "CORS is a browser-enforced policy that controls whether a page may read a cross-origin response. The server opts in with headers such as `Access-Control-Allow-Origin`; without them, the request may still reach the server but the browser hides the response from script. A safelisted request can go directly. A request using a non-safelisted method, header, or content type is normally preceded by an `OPTIONS` preflight asking whether the real request is allowed. Credentialed requests need an explicit origin and `Access-Control-Allow-Credentials: true`; `*` cannot be used for that case.",
    interviewerNotes: "The key correction is that CORS is not an API authentication or server-side firewall.", sourceRefs: webRefs,
    options: [{ id: "a", label: "CORS prevents a request from ever reaching another server" }, { id: "b", label: "CORS controls browser script access to a cross-origin response; some requests are preflighted", correct: true }, { id: "c", label: "Every cross-origin GET requires OPTIONS" }, { id: "d", label: "CORS replaces authentication" }],
  },
  {
    id: "web-storage", track: "quiz", level: "beginner", title: "Cookies vs localStorage vs sessionStorage", tags: ["browser", "security"], status: "ready", canonicalTopic: "web-storage",
    prompt: "Compare lifetime, request behavior, scope, and security trade-offs. Where should a sensitive session token live?",
    hints: ["Cookies can accompany HTTP requests.", "Web Storage is readable by JavaScript."],
    approach: "Use a small comparison: cookies for server-managed sessions; local storage for non-sensitive durable preference; session storage for a tab session.",
    solution: "Cookies are small values scoped by domain/path and can be sent with matching HTTP requests. `HttpOnly`, `Secure`, and `SameSite` make them appropriate for server-managed session cookies because JavaScript cannot read an HttpOnly value. `localStorage` persists by origin until cleared and is readable by any script on that origin; use it for non-sensitive preferences, not bearer session tokens. `sessionStorage` is also script-readable but is isolated to a tab and normally ends when that tab closes. All three need a clear retention policy and XSS protection.",
    interviewerNotes: "Do not present localStorage as a universally safe token store; discuss XSS and cookie CSRF protections together.", sourceRefs: webRefs,
    options: [{ id: "a", label: "localStorage is sent with every same-origin request" }, { id: "b", label: "HttpOnly cookies are not readable by JavaScript and can support server-managed sessions", correct: true }, { id: "c", label: "sessionStorage is shared by every browser tab" }, { id: "d", label: "Cookies cannot have security attributes" }],
  },
  {
    id: "css-critical-css", track: "quiz", level: "senior", title: "What is critical CSS?", tags: ["css", "performance"], status: "ready", canonicalTopic: "critical-css",
    prompt: "Which CSS belongs in the critical path, and how do you improve render speed without creating a maintenance problem?",
    hints: ["Stylesheets block first render while they are needed.", "Only above-the-fold rules are candidates."],
    approach: "Connect it to render-blocking CSS, then state the trade-off: small and generated/maintained deliberately, with the rest loaded normally.",
    solution: "Critical CSS is the smallest set of styles needed to render the initial viewport correctly. Inlining or prioritizing it can reduce render delay because the browser does not have to wait for a large stylesheet before painting. Keep it genuinely small—layout, typography, and the initial route shell—not an entire framework bundle. Load the remaining CSS normally or split it by route, and measure LCP and visual regressions. A large inline block hurts caching and can make future pages slower.",
    interviewerNotes: "Senior signal: they mention cache trade-offs and measure the impact instead of treating inlining as automatically faster.", sourceRefs: webRefs,
    options: [{ id: "a", label: "All application CSS embedded in every HTML response" }, { id: "b", label: "The minimal styles required for the initial viewport, prioritized to unblock render", correct: true }, { id: "c", label: "CSS that only runs after JavaScript hydration" }, { id: "d", label: "A replacement for responsive design" }],
  },
  {
    id: "css-bfc", track: "quiz", level: "mid", title: "Block formatting context — why it matters", tags: ["css", "layout"], status: "ready", canonicalTopic: "bfc",
    prompt: "What layout problems can a block formatting context isolate, and which modern properties create one?",
    hints: ["It contains its internal float layout.", "`display: flow-root` is the explicit modern tool."],
    approach: "Explain it as an independent block layout region, then give float containment and margin behavior as concrete effects.",
    solution: "A block formatting context (BFC) is an independent block layout region. Its contents lay out without interacting with floats outside it, and it contains internal floats for height calculation; adjacent margins between its contents and outside blocks also do not collapse through the boundary. `display: flow-root` is the clear modern way to create one. Other mechanisms such as `overflow: auto/hidden`, flex/grid containers, and absolutely positioned elements can create BFCs, but using overflow just to clear floats can have unwanted clipping or scrolling effects.",
    interviewerNotes: "Prefer a real layout outcome over a memorized list of BFC triggers.", sourceRefs: webRefs,
    options: [{ id: "a", label: "A BFC is a JavaScript event queue" }, { id: "b", label: "An independent block layout region that can contain floats; `flow-root` creates one explicitly", correct: true }, { id: "c", label: "It is required for every flex container" }, { id: "d", label: "It makes all descendants position: fixed" }],
  },
  {
    id: "css-centering", track: "quiz", level: "beginner", title: "Ways to center a div", tags: ["css", "layout"], status: "ready", canonicalTopic: "css-centering",
    prompt: "How would you center an unknown-size item in both axes, center a fixed-width block horizontally, and avoid unnecessary positioning hacks?",
    hints: ["Use layout systems for layout.", "Auto inline margins center a block with a constrained width."],
    approach: "Match the method to the constraint: flex/grid for two axes, auto margins for a constrained block, and absolute positioning only when it is actually an overlay.",
    solution: "For an item centered in both axes, use the parent as `display: grid; place-items: center` or `display: flex; align-items: center; justify-content: center`. For a block with a known or bounded width, `margin-inline: auto` centers it horizontally. Text can use `text-align: center` in its inline formatting context. Avoid absolute positioning plus transforms for normal document layout—it removes the element from flow and is best reserved for genuine overlays.",
    interviewerNotes: "Good candidates ask what must be centered and whether it must remain in normal flow.", sourceRefs: webRefs,
    options: [{ id: "a", label: "Absolute positioning is the only reliable approach" }, { id: "b", label: "Grid or Flexbox center unknown-size items; auto inline margins center a constrained block", correct: true }, { id: "c", label: "text-align centers any block element" }, { id: "d", label: "Flexbox cannot center vertically" }],
  },
  {
    id: "react-fiber", track: "quiz", level: "senior", title: "What problem does React Fiber solve?", tags: ["react", "rendering"], status: "ready", canonicalTopic: "react-fiber",
    prompt: "Why did React need work that can be paused, prioritized, and resumed instead of one uninterrupted tree reconciliation pass?",
    hints: ["Large synchronous updates block input and paint.", "Fiber is an internal representation of work units."],
    approach: "State the user-visible problem first: responsiveness. Then describe Fiber as React’s incremental scheduling architecture, not an API to program against.",
    solution: "React Fiber is the internal architecture that represents component work as small units which React can schedule, pause, abandon, and resume. It was designed to prevent a large render update from monopolizing the main thread when more urgent work—such as typing or an interaction—needs attention. This enables priorities, concurrent rendering features, Suspense coordination, and better interruption handling. It does not make every render asynchronous or promise a particular scheduling order; application code should use the public APIs rather than depend on Fiber internals.",
    interviewerNotes: "Avoid saying Fiber is a virtual DOM replacement. The important outcome is interruptible, prioritized rendering.", sourceRefs: reactRefs,
    options: [{ id: "a", label: "It replaces JavaScript with a worker thread" }, { id: "b", label: "It breaks rendering into schedulable work so urgent updates can remain responsive", correct: true }, { id: "c", label: "It is React’s CSS engine" }, { id: "d", label: "It guarantees every component renders only once" }],
  },
  {
    id: "react-concurrent", track: "quiz", level: "senior", title: "startTransition and concurrent rendering", tags: ["react", "performance"], status: "ready", canonicalTopic: "concurrent-react",
    prompt: "When should an update be wrapped in `startTransition`, and why must the transition update itself stay pure and interruptible?",
    hints: ["Keep the input value urgent.", "A transition is interruptible background rendering, not a timer."],
    approach: "Use search as the example: update the controlled input immediately, transition the expensive result view, and expose pending state if useful.",
    solution: "`startTransition` marks state updates as non-urgent. React can keep urgent updates such as typing responsive, pause an in-progress transition render, and restart it with fresher data. A common example is updating a filter input immediately while transitioning a large result list. Do not wrap the controlled input’s own value update in a transition because it must keep pace with the user. Transition rendering may run more than once or be discarded, so render must remain pure and effects belong in their proper lifecycle, not in render.",
    interviewerNotes: "Look for the urgent-vs-non-urgent split, rather than a claim that transitions make work free.", sourceRefs: reactRefs,
    options: [{ id: "a", label: "It delays all updates by a fixed amount" }, { id: "b", label: "It marks non-urgent updates as interruptible while urgent input can update immediately", correct: true }, { id: "c", label: "It replaces useState" }, { id: "d", label: "It should wrap every controlled input update" }],
  },
  {
    id: "react-state-management", track: "quiz", level: "mid", title: "Context vs Redux/Zustand — when each", tags: ["react", "state"], status: "ready", canonicalTopic: "state-management",
    prompt: "How do you choose among local state, Context, and an external store without making Context a global dumping ground?",
    hints: ["State should live as close to its consumers as possible.", "Context is good for stable, broad dependencies; an external store may be better for frequent shared updates."],
    approach: "Begin with local/URL/server state, then explain Context for dependency distribution and a store for complex cross-cutting client state.",
    solution: "Start with the narrowest owner: component state for local UI, URL state for shareable navigation state, and a server cache for remote data. Context is excellent for broadly needed, relatively stable dependencies such as theme, locale, or an authenticated user boundary. A large Context value that changes frequently can re-render many consumers and obscures ownership. Use an external store such as Redux or Zustand when multiple distant features coordinate complex client state, selectors, devtools, middleware, or explicit state transitions add value. The choice follows access pattern and update frequency, not team fashion.",
    interviewerNotes: "A nuanced answer includes server state and URL state instead of framing the choice as Context versus Redux only.", sourceRefs: reactRefs,
    options: [{ id: "a", label: "All state belongs in one Context provider" }, { id: "b", label: "Use the narrowest owner; Context suits broad stable dependencies and an external store can suit complex shared client state", correct: true }, { id: "c", label: "Context cannot trigger re-renders" }, { id: "d", label: "Redux should hold all server responses forever" }],
  },
  {
    id: "react-controlled-inputs", track: "quiz", level: "beginner", title: "Controlled vs uncontrolled inputs", tags: ["react", "forms"], status: "ready", canonicalTopic: "controlled-inputs",
    prompt: "Who owns an input’s current value in each approach, and when is an uncontrolled ref a reasonable choice?",
    hints: ["A controlled input receives a `value` prop.", "The DOM can own state when React does not need to react to every keystroke."],
    approach: "Contrast React state as the source of truth with the DOM as the source of truth; connect controlled inputs to validation and derived UI.",
    solution: "A controlled input receives its value from React state and reports changes through `onChange`, so React is the source of truth. This makes live validation, conditional UI, formatting, and resetting predictable. An uncontrolled input stores its current value in the DOM; React can read it with a ref or `FormData` on submit. It is a good fit for simple forms, integrating non-React widgets, or avoiding a state update for every keystroke when live coordination is unnecessary. Do not switch an input between controlled and uncontrolled during its lifetime.",
    interviewerNotes: "They should identify the ownership model, not simply call one approach better.", sourceRefs: reactRefs,
    options: [{ id: "a", label: "Controlled inputs keep their value only in the DOM" }, { id: "b", label: "Controlled inputs use React state as the source of truth; uncontrolled inputs let the DOM hold the current value", correct: true }, { id: "c", label: "Uncontrolled inputs cannot be read in React" }, { id: "d", label: "An input should alternate between modes each render" }],
  },
  {
    id: "react-virtual-dom", track: "quiz", level: "beginner", title: "What is the virtual DOM?", tags: ["react", "rendering"], status: "ready", canonicalTopic: "virtual-dom",
    prompt: "What does React compare before committing a change, and why does this not mean DOM changes are always cheap?",
    hints: ["It is an in-memory description, not a browser API.", "Rendering work, reconciliation, layout, and paint are separate costs."],
    approach: "Explain declarative render output, reconciliation against the prior tree, then the commit to the real DOM.",
    solution: "The virtual DOM is an in-memory description of the UI React wants to show. After state changes, React renders a new description, reconciles it with the previous one using component types and keys, then commits the necessary changes to the browser DOM. It makes declarative UI practical, but it is not a blanket performance guarantee: rendering a very large tree, expensive component work, layout, paint, and unstable list keys can still be costly. Measure the actual bottleneck before optimizing.",
    interviewerNotes: "Correct the common myth that React recreates the entire real DOM on every update.", sourceRefs: reactRefs,
    options: [{ id: "a", label: "A second DOM maintained by the browser" }, { id: "b", label: "An in-memory UI description React reconciles before committing real DOM changes", correct: true }, { id: "c", label: "A guarantee that rendering never causes layout" }, { id: "d", label: "A replacement for component keys" }],
  },
  {
    id: "react-hydration", track: "quiz", level: "senior", title: "Explain hydration mismatches", tags: ["ssr", "react"], status: "ready", canonicalTopic: "hydration",
    prompt: "Why must the first client render agree with server HTML, and which common sources of nondeterminism cause a mismatch?",
    hints: ["The client attaches behavior to server-rendered markup.", "Time, randomness, locale, browser-only data, and invalid HTML are common culprits."],
    approach: "Define hydration, name mismatch inputs, then give safe patterns: pass server-derived data, defer client-only reads, and render valid deterministic markup.",
    solution: "Hydration is React attaching event handlers and state to HTML that was rendered on the server. The client’s first render must produce the same structure and content; otherwise React warns, may discard work, and users can see flicker or broken behavior. Common causes are `Date.now()`, `Math.random()`, locale/time-zone differences, reading `window` or storage during render, browser extensions, and invalid nested HTML. Pass stable server data as props, initialize client-only state after mount when necessary, and make the initial render deterministic. `suppressHydrationWarning` is a narrow escape hatch, not a cure.",
    interviewerNotes: "A strong answer treats the cause, not just the warning suppression flag.", sourceRefs: reactRefs,
    options: [{ id: "a", label: "Hydration only downloads CSS" }, { id: "b", label: "The initial client render must match server HTML so React can attach behavior predictably", correct: true }, { id: "c", label: "Random values are ideal server-rendered content" }, { id: "d", label: "suppressHydrationWarning fixes the underlying mismatch" }],
  },
  {
    id: "web-csrf", track: "quiz", level: "mid", title: "CSRF — how frontends participate in defense", tags: ["security", "cookies"], status: "ready", canonicalTopic: "csrf",
    prompt: "Why are cookie-authenticated state-changing endpoints vulnerable to CSRF, and which layered defenses should a frontend support?",
    hints: ["Browsers may attach cookies automatically.", "SameSite helps but is not the only control."],
    approach: "Explain the attacker’s cross-site form/request, then cover SameSite, server-side origin checks, CSRF tokens, and safe UI behavior.",
    solution: "Cross-site request forgery occurs when a victim’s browser sends an authenticated request to a site because its cookies are attached automatically, even though the request was initiated from an attacker’s page. Frontends participate by using the application’s CSRF-token convention for state-changing requests, avoiding side effects on GET, and respecting credential settings. Servers should use `SameSite` cookies where compatible, verify Origin/Referer for sensitive requests, and validate an unpredictable CSRF token when required. CORS is not a CSRF defense because it controls response reading, not whether a request is sent.",
    interviewerNotes: "The crucial distinction is CSRF’s reliance on ambient credentials, unlike XSS running inside the trusted origin.", sourceRefs: webRefs,
    options: [{ id: "a", label: "CSRF is prevented by hiding a response with CORS" }, { id: "b", label: "It exploits automatically attached credentials; use layered defenses such as SameSite, origin checks, and CSRF tokens", correct: true }, { id: "c", label: "It only affects GET requests" }, { id: "d", label: "HttpOnly alone prevents CSRF" }],
  },
  {
    id: "web-csp", track: "quiz", level: "senior", title: "Content Security Policy basics for FE", tags: ["security", "xss"], status: "ready", canonicalTopic: "csp",
    prompt: "What does CSP restrict, and how would you roll it out without breaking a production application?",
    hints: ["It is defense in depth for script execution and resource loading.", "Start with report-only mode and remove unsafe inline patterns deliberately."],
    approach: "Name key directives, then describe report-only rollout, nonces/hashes, third-party inventory, and monitoring.",
    solution: "Content Security Policy is a response header that tells the browser which sources may load scripts, styles, images, frames, and other resources, and can limit where forms connect. A strong `script-src` with nonces or hashes makes many injected inline scripts fail, reducing XSS impact; it does not replace output escaping and input validation. Roll it out first in `Content-Security-Policy-Report-Only`, collect violations, inventory legitimate third parties, and replace inline handlers/eval-style patterns. Avoid adding `'unsafe-inline'` or broad wildcards just to silence reports, because that removes much of the protection.",
    interviewerNotes: "CSP is a mitigator and an operational discipline, not a substitute for fixing unsafe sinks.", sourceRefs: webRefs,
    options: [{ id: "a", label: "A way to encrypt API responses" }, { id: "b", label: "A browser policy limiting allowed resource sources and script execution patterns", correct: true }, { id: "c", label: "A replacement for escaping user content" }, { id: "d", label: "Only a server-side firewall rule" }],
  },
  {
    id: "a11y-aria-live", track: "quiz", level: "mid", title: "aria-live regions — when to use", tags: ["a11y", "screen-readers"], status: "ready", canonicalTopic: "aria-live",
    prompt: "Which updates should be announced to assistive technology, and how do polite and assertive live regions differ?",
    hints: ["Do not announce every visual change.", "Use assertive only for urgent interruptions."],
    approach: "Give concrete examples—form status, search results, errors—then explain stable live-region placement and message deduplication.",
    solution: "An `aria-live` region announces meaningful dynamic changes to screen-reader users without moving focus. Use `aria-live=\"polite\"` for non-urgent updates such as a save confirmation or changed result count; the screen reader finishes its current speech first. `aria-live=\"assertive\"` interrupts and is appropriate only for urgent errors or safety-critical status. Keep the region present in the DOM before changing its text, use concise messages, and avoid announcing routine loading spinners or every keystroke. If user action needs attention, focus management may be better than an announcement alone.",
    interviewerNotes: "Accessibility quality is restraint: the wrong live region can make an app unbearable to use.", sourceRefs: webRefs,
    options: [{ id: "a", label: "A live region should announce every DOM mutation" }, { id: "b", label: "Use polite announcements for routine meaningful updates and assertive only for urgent interruptions", correct: true }, { id: "c", label: "aria-live automatically moves keyboard focus" }, { id: "d", label: "It is only useful for visual users" }],
  },
  {
    id: "a11y-reduced-motion", track: "quiz", level: "mid", title: "Respecting prefers-reduced-motion", tags: ["a11y", "motion"], status: "ready", canonicalTopic: "reduced-motion",
    prompt: "How should an interface respond to a user’s reduced-motion preference without making the product feel broken?",
    hints: ["Reduce nonessential motion; do not remove information.", "The media query is a preference, not an instruction to freeze every transition."],
    approach: "Treat motion as an enhancement. Preserve state changes and feedback with opacity, instant changes, or simpler transitions.",
    solution: "Use `@media (prefers-reduced-motion: reduce)` to remove or greatly shorten nonessential movement such as parallax, looping decoration, auto-playing carousels, large scale/slide transitions, and smooth scrolling. Preserve the information the animation conveyed: an accordion can open immediately, a toast can appear without flying across the screen, and a loading state can still have text. Respect the operating-system preference by default and, when useful, provide an in-product override that does not fight it. Test keyboard focus and scroll behavior in the reduced mode too.",
    interviewerNotes: "The goal is reducing vestibular triggers while keeping orientation and feedback clear.", sourceRefs: webRefs,
    options: [{ id: "a", label: "Disable all visual state changes" }, { id: "b", label: "Reduce nonessential movement while preserving the information and feedback it conveyed", correct: true }, { id: "c", label: "Only apply the preference on mobile" }, { id: "d", label: "Ignore the preference if animation is branded" }],
  },
  {
    id: "architecture-module-federation", track: "quiz", level: "staff", title: "Module federation trade-offs", tags: ["architecture", "microfrontends"], status: "ready", canonicalTopic: "module-federation",
    prompt: "What organizational problem can runtime module sharing solve, and what coupling, reliability, and performance costs does it introduce?",
    hints: ["Independent deployment is a means, not the goal.", "Shared dependencies and runtime contracts still need governance."],
    approach: "Start with team boundaries and release friction. Then assess runtime failure modes, version compatibility, ownership, observability, and the cost of distributed UX.",
    solution: "Module Federation lets separately built applications expose and consume modules at runtime. It can reduce deployment coupling when teams own genuinely independent verticals that need to compose in one shell. The trade-offs are significant: runtime availability and version compatibility become production dependencies; duplicate frameworks can inflate the bundle; shared design, routing, authentication, testing, and error boundaries need explicit contracts; and a remote outage can damage the host experience. Prefer a modular monolith or package-based design system when teams can coordinate releases. Choose federation for proven organizational independence, with fallbacks, version policies, ownership, and observability in place.",
    interviewerNotes: "Staff-level answers ground the choice in team topology and operational cost, not novelty.", sourceRefs: webRefs,
    options: [{ id: "a", label: "It eliminates the need for versioning and integration tests" }, { id: "b", label: "It can enable independent runtime composition but adds runtime, versioning, performance, and governance costs", correct: true }, { id: "c", label: "It is required for any shared component library" }, { id: "d", label: "It guarantees smaller JavaScript bundles" }],
  },
  {
    id: "architecture-microfrontends", track: "quiz", level: "staff", title: "When microfrontends are worth it", tags: ["architecture", "organization"], status: "ready", canonicalTopic: "microfrontends",
    prompt: "Which signals justify microfrontends, and which common problems should you solve first inside a monorepo or modular application?",
    hints: ["Team autonomy must outweigh coordination cost.", "Codebase size alone is not enough."],
    approach: "Frame the decision around independently owned business domains and blocked delivery, then contrast it with internal modules, packages, and platform standards.",
    solution: "Microfrontends can be worth the cost when durable, independently staffed business domains have conflicting release cadences or delivery bottlenecks that a shared application cannot resolve, and when the organization can support platform ownership. They are not a cure for a large repository, slow builds, or unclear code boundaries. First try clear domain modules, a monorepo with package boundaries, a shared design system, code ownership, and a better release pipeline. If you adopt microfrontends, define shell/remote contracts, navigation and auth ownership, design-token governance, performance budgets, shared dependency policy, end-to-end testing, and failure isolation. The architecture should make customer flows simpler, not make the org chart visible in the UI.",
    interviewerNotes: "The best answer names the alternatives and accepts that every deployment boundary creates a distributed-system cost.", sourceRefs: webRefs,
    options: [{ id: "a", label: "They are the default for any frontend with more than one team" }, { id: "b", label: "They fit durable independent domains when autonomy outweighs the platform and runtime costs", correct: true }, { id: "c", label: "They remove the need for shared UI standards" }, { id: "d", label: "They are a simple fix for slow linting" }],
  },
];
