import type { Question } from "@/lib/types";
import { makeQuiz, mdn, tsRefs, type QuizInput } from "@/content/quiz-helpers";

const q = (input: QuizInput): Question => makeQuiz("wave3", input);

export const quizWave3: Question[] = [
  q({
    topic: "what-are-generators-and-iterators",
    title: "What are generators and iterators?",
    level: "mid",
    tags: ["javascript", "iteration"],
    prompt: "You need to read a very large list lazily, one chunk at a time, and let the caller stop early. Why is a generator a good fit?",
    hints: ["An iterator is any object whose next() returns { value, done }.", "A generator function pauses at each yield and resumes on the next call."],
    approach: "Define the iterator protocol, show how function* builds one, and mention laziness, two-way communication, and early exit.",
    solution:
      "An iterator is an object with a `next()` method that returns `{ value, done }`. An iterable has a `[Symbol.iterator]()` method that returns an iterator, which is what `for...of`, spread, and destructuring consume. A generator function (`function*`) returns an object that is both: each call to `next()` runs the body until the next `yield`, then pauses with its local state intact. That makes values lazy, because nothing is computed until requested, and it lets an infinite sequence exist without running out of memory. `next(value)` sends a value back in as the result of the paused `yield`, which is how libraries once built async flows on top of generators. `return()` and `throw()` end or fail the generator, and `for...of` calls `return()` automatically when you `break`, so `finally` blocks clean up. Async generators (`async function*`) pair with `for await...of` to stream results from the network.",
    notes: "A strong answer ties laziness to memory and early exit, and mentions that for...of calls return() on break.",
    correct: "It runs lazily, pausing at each yield, so values are produced on demand and the caller can stop early",
    wrong: [
      "It runs the whole function up front and stores every value in an array before the first loop iteration",
      "It runs on a separate thread so the main thread is never blocked while values are produced",
      "It makes the function return a Promise that resolves with all values at once",
    ],
  }),
  q({
    topic: "explain-proxy-and-reflect",
    title: "Explain Proxy and Reflect",
    level: "senior",
    tags: ["javascript", "metaprogramming"],
    prompt: "A reactive library wraps state in a Proxy and logs every property read and write. Why pair the traps with Reflect?",
    hints: ["Reflect has one method per internal operation, with the same signature as the matching trap.", "Think about getters, receivers, and the return value of set."],
    approach: "Describe traps, say what Reflect offers, and explain why forwarding with Reflect preserves default behaviour and `this`.",
    solution:
      "A `Proxy` wraps a target and lets you intercept fundamental operations through traps such as `get`, `set`, `has`, `deleteProperty`, and `ownKeys`. `Reflect` exposes those same operations as plain functions with matching signatures. Inside a trap, calling `Reflect.get(target, key, receiver)` or `Reflect.set(target, key, value, receiver)` performs the default behaviour correctly: the `receiver` argument keeps `this` bound to the proxy when the property is a getter or setter, and `Reflect.set` returns a boolean that a `set` trap must return truthy for or strict-mode code throws a TypeError. Reflect also reports failure by returning `false` instead of throwing, which is easier to forward. Proxies have costs: they cannot be polyfilled, they add overhead per access, they break identity (`proxy !== target`), and some built-ins such as `Map` methods fail when called with a proxy as `this`. Vue 3 builds its reactivity on Proxy for this reason.",
    notes: "Look for the receiver argument and the set-return-value rule. Bonus for naming the identity and internal-slot pitfalls.",
    correct: "Reflect runs the default operation correctly, including the receiver for getters and setters, and returns the boolean a set trap needs",
    wrong: [
      "Reflect makes the proxy deeply reactive, so nested objects are wrapped automatically with no extra work in the traps and nested property updates trigger the traps",
      "Reflect freezes the target so traps cannot be bypassed by code that holds a reference to the original object",
      "Reflect is required by the language specification, so creating a Proxy without calling it in every trap throws",
    ],
  }),
  q({
    topic: "what-is-object-freeze-vs-object-seal",
    title: "What is Object.freeze vs Object.seal?",
    level: "mid",
    tags: ["javascript", "objects"],
    prompt: "After `Object.seal(user)`, what can you still do to `user.name`, and how does `Object.freeze` differ?",
    hints: ["Seal locks the set of keys. Freeze also locks the values.", "Both are shallow."],
    approach: "Compare add, delete, and update behaviour for preventExtensions, seal, and freeze, and mention shallowness and strict mode errors.",
    solution:
      "`Object.preventExtensions` stops new properties being added. `Object.seal` does that and also marks every existing property non-configurable, so you cannot delete them, but you can still change the values of writable properties. `Object.freeze` goes further and makes every data property non-writable too, so nothing can be added, removed, or reassigned. All three are shallow: a nested object inside a frozen object can still be changed unless you freeze it as well. In sloppy mode a blocked write fails silently. In strict mode, and inside modules and classes, it throws a TypeError. `Object.isFrozen` and `Object.isSealed` test the state. Freezing arrays blocks `push` and index assignment. Freezing is a cheap guard for constants, but it is not a substitute for immutable data structures, because copies are still mutable.",
    notes: "Most miss that sealed values remain writable, and that none of the three is deep.",
    correct: "After seal you can still reassign user.name but cannot add or delete keys. freeze also blocks reassignment. Both are shallow",
    wrong: [
      "After seal user.name is read-only and freeze additionally prevents deleting keys. Both are deep, so nested objects are locked too",
      "Seal and freeze behave identically, since freeze is only the newer name for seal added in a later specification",
      "Seal blocks reads of user.name from other modules, and freeze additionally blocks reads from other threads",
    ],
  }),
  q({
    topic: "what-is-structuredclone",
    title: "What is structuredClone?",
    level: "mid",
    tags: ["javascript", "objects"],
    prompt: "You deep-copy state with `JSON.parse(JSON.stringify(x))` and your Dates become strings and a Map disappears. What is the better built-in, and what does it still not copy?",
    hints: ["It uses the structured clone algorithm that postMessage uses.", "Functions and DOM nodes are not cloneable."],
    approach: "Say what it supports that JSON does not, list what it rejects, and note that prototypes are lost.",
    solution:
      "`structuredClone(value)` performs a deep copy using the structured clone algorithm, the same one `postMessage` and IndexedDB use. Unlike the JSON round trip it preserves `Date`, `RegExp`, `Map`, `Set`, `ArrayBuffer` and typed arrays, `Error` objects, `undefined` values, and circular references. It throws a `DataCloneError` for functions and DOM nodes, and symbol-keyed properties are skipped. Class instances are cloned as plain objects: the prototype chain and methods are lost, and getters are evaluated to their values. You can pass `{ transfer: [buffer] }` to move an ArrayBuffer instead of copying it. It is available in modern browsers, workers, and Node 17 and later. Use it for plain data. For objects with behaviour, write an explicit clone method.",
    notes: "Ask what happens to a class instance. The answer is a plain object. That separates users from readers of the docs.",
    correct: "structuredClone deep copies Dates, Maps, Sets and cycles. It throws on functions and turns class instances into plain objects",
    wrong: [
      "structuredClone is a shallow copy like the spread operator, but unlike spread it also copies Maps and Sets",
      "structuredClone deep copies everything including functions, and it keeps the original prototype chain intact, so class instances come back with their methods",
      "structuredClone only works inside Web Workers, and it throws a DataCloneError when called on the main thread",
    ],
  }),
  q({
    topic: "explain-set-vs-array-vs-weakset",
    title: "Explain Set vs Array vs WeakSet",
    level: "mid",
    tags: ["javascript", "collections"],
    prompt: "You track which DOM nodes have already been initialised and do not want to leak them. Which collection fits and why?",
    hints: ["A WeakSet holds objects weakly.", "You cannot iterate a WeakSet or read its size."],
    approach: "Contrast uniqueness and lookup cost for Set versus Array, then explain weak references and their limits.",
    solution:
      "An `Array` is ordered and allows duplicates, and `includes` is linear. A `Set` keeps unique values (compared with SameValueZero, so `NaN` equals `NaN`), preserves insertion order, and `has` is constant time on average, which makes it the right tool for deduplication and membership checks. A `WeakSet` stores only objects and holds them weakly: if nothing else references an object, the garbage collector may drop it from the set. Because collection timing is not observable, a WeakSet has no `size`, no iteration, and no `clear`. It supports `add`, `has`, and `delete`. For the initialised-DOM-nodes case a WeakSet is ideal: the set never keeps a removed node alive. Use `WeakMap` when you need to attach data to an object with the same lifetime guarantee. `WeakRef` and `FinalizationRegistry` exist but are rarely the right tool.",
    notes: "Listen for why a WeakSet is not iterable. It shows that the candidate understands garbage collection is non-deterministic.",
    correct: "A WeakSet: it holds nodes weakly so removed nodes can be collected, at the cost of no size or iteration",
    wrong: [
      "An Array: it holds nodes weakly by default and removes them when the node leaves the document, so it never keeps a removed node alive afterwards",
      "A Set: it releases an object automatically as soon as the last outside reference disappears",
      "A WeakSet, because it can store strings and numbers and is iterable like a Set",
    ],
  }),
  q({
    topic: "explain-function-currying-vs-partial-application",
    title: "Explain function currying vs partial application",
    level: "mid",
    tags: ["javascript", "functions"],
    prompt: "What is the difference between `curry(add)(1)(2)(3)` and `add.bind(null, 1)`?",
    hints: ["One always produces a chain of single-argument functions.", "The other fixes some arguments and leaves the rest open."],
    approach: "Define each in one line, show an example, then say when each is useful.",
    solution:
      "Currying transforms a function of several arguments into a chain of functions that each take one argument: `add(1, 2, 3)` becomes `add(1)(2)(3)`. Partial application fixes some arguments up front and returns a function that takes the remaining ones in one call: `const add1 = add.bind(null, 1)` then `add1(2, 3)`. They are related, since a curried function makes partial application easy, but they are not the same. Currying is mostly about shape, and it composes well in point-free pipelines. Partial application is about presetting configuration, such as a logger with a fixed prefix or an event handler with a fixed id. A generic `curry` helper reads `fn.length` to know how many arguments to collect, which fails with default and rest parameters. In JavaScript, closures or `bind` are usually clearer than a curry helper unless the codebase is functional in style.",
    notes: "Candidates often use the words as synonyms. A crisp contrast and the fn.length caveat show depth.",
    correct: "Currying makes a chain of one-argument functions. Partial application fixes some arguments and takes the rest together",
    wrong: [
      "They are the same technique, and bind is simply the older name that JavaScript used for currying",
      "Currying fixes some arguments immediately, while partial application delays all arguments until the final call, which is the reverse of how bind works",
      "Currying only works on async functions, while partial application only works on class constructors",
    ],
  }),
  q({
    topic: "what-is-object-assign-vs-spread",
    title: "What is Object.assign vs spread?",
    level: "mid",
    tags: ["javascript", "objects"],
    prompt: "What is different between `Object.assign(target, src)` and `{ ...target, ...src }`?",
    hints: ["One mutates its first argument.", "Setters on the target behave differently."],
    approach: "Compare mutation, setters versus defining properties, and what both copy and skip.",
    solution:
      "Both copy own enumerable properties, including symbol keys, and both are shallow. `Object.assign(target, src)` writes onto the existing `target` and returns it, so it mutates, and it uses assignment, which invokes setters on the target. The object spread expression builds a new object and defines each property directly, so it does not invoke setters and leaves the sources alone. Neither copies non-enumerable properties, the prototype, or class private fields. `Object.assign({}, a, b)` and `{ ...a, ...b }` give the same result in most cases. Prefer spread for immutable updates in React or Redux, since a new reference tells the framework something changed. Use `Object.assign` when you intentionally want to mutate an existing object, such as filling options on a prototype. For a deep copy use `structuredClone`.",
    notes: "The setter difference is the detail that separates a memorised answer from an understood one.",
    correct: "assign mutates the target and runs its setters. spread builds a new object and defines properties without setters",
    wrong: [
      "spread mutates the first object and returns it, while Object.assign always creates a deep copy of every source",
      "assign copies non-enumerable and inherited properties, while spread copies only the object’s own properties",
      "They are identical in every case, including mutation and setters, and differ only in how the syntax looks",
    ],
  }),
  q({
    topic: "explain-garbage-collection-basics-in-v8",
    title: "Explain garbage collection basics in V8",
    level: "senior",
    tags: ["javascript", "memory"],
    prompt: "An object is no longer used by your code but memory keeps growing. How does V8 decide what is garbage, and why might this object survive?",
    hints: ["Collection is based on reachability from roots, not on whether code will use the object again.", "V8 splits the heap by object age."],
    approach: "Explain reachability, the young and old generations, and the main causes of retained objects.",
    solution:
      "V8 does not count references. It marks everything reachable from roots (the global object, the current stack, and active closures) and frees the rest, which also means reference cycles are not a problem. The heap is generational. New objects go into a small young generation that is collected often with a fast copying scavenger, since most objects die young. Objects that survive are promoted to the old generation, which is collected with mark-sweep and compaction, using incremental and concurrent work to keep pauses short. An object stays in memory while anything reachable still references it: a long-lived array, a global cache, a forgotten event listener, a timer callback, or a closure that captured it. Detached DOM nodes held by a variable are a classic case. To investigate, take heap snapshots in DevTools and compare the retainers. Fix leaks by removing the reference, not by trying to trigger collection.",
    notes: "Listen for reachability and the generational split. A candidate who says reference counting has the wrong model.",
    correct: "V8 frees objects not reachable from roots. A closure, cache, listener or timer can keep it reachable",
    wrong: [
      "V8 frees an object when its reference count hits zero, so a reference cycle always leaks",
      "V8 frees objects after a fixed time, so a surviving object must have been created recently",
      "V8 frees objects when you set the variable to null, so leaks come only from forgetting to do so",
    ],
  }),
  q({
    topic: "what-is-requestidlecallback",
    title: "What is requestIdleCallback?",
    level: "mid",
    tags: ["browser", "performance"],
    prompt: "You want to send low-priority analytics without hurting input responsiveness. What does requestIdleCallback offer, and what do you need to watch for?",
    hints: ["The callback receives a deadline object.", "Not every browser supports it."],
    approach: "Describe when callbacks run, the deadline API, the timeout option, and the fallback.",
    solution:
      "`requestIdleCallback(fn, { timeout })` schedules work for when the main thread has nothing urgent to do, typically after a frame has been produced with time to spare. The callback receives an `IdleDeadline` with `timeRemaining()`, so you can do small units of work in a loop and stop when time runs out, then schedule the rest again. If the page is always busy the callback may never run, so pass a `timeout` to force it to run eventually. Do not touch the DOM in it in ways that force layout, since that can blow the budget. It is good for analytics, prefetching, and non-urgent parsing. Support is not universal (Safari has lagged), so feature-detect and fall back to `setTimeout`. For prioritised scheduling, the newer `scheduler.postTask` and `scheduler.yield` offer more control. Idle callbacks are not suitable for work that must complete before the user acts.",
    notes: "Good answers mention the timeout for starvation and a fallback. Weak answers say it runs after load.",
    correct: "It runs work when the main thread is idle, gives a deadline to check, and needs a timeout to avoid starvation",
    wrong: [
      "It runs the callback exactly 16 ms later, just before the next frame is painted, like requestAnimationFrame",
      "It runs the callback in a background thread so it can freely update the DOM without blocking anything",
      "It runs the callback immediately after the load event and is supported identically in every browser",
    ],
  }),
  q({
    topic: "explain-dynamic-import",
    title: "Explain dynamic import()",
    level: "mid",
    tags: ["javascript", "modules", "performance"],
    prompt: "A heavy chart library is only needed on one tab. How does `import()` help, and what does it return?",
    hints: ["It is an expression, not a statement.", "It returns a Promise."],
    approach: "Contrast static and dynamic import, say what the promise resolves to, and tie it to code splitting and error handling.",
    solution:
      "A static `import` is hoisted and evaluated before the module runs, so the whole graph loads up front. `import('./chart.js')` is an expression that loads the module on demand and returns a Promise for the module namespace object, so you read `const { render } = await import('./chart.js')`. Bundlers treat each dynamic import as a split point and emit a separate chunk, which keeps the initial bundle small. It also works in classic scripts, accepts a computed specifier (although bundlers then cannot analyse it statically and may include more than you want), and each module is evaluated only once and cached. A failed network request rejects the promise, so handle a chunk-load error with a retry or a fallback UI. In React, `React.lazy(() => import(...))` wraps this with Suspense. Prefetching the chunk on hover or when idle hides the latency.",
    notes: "Listen for the error handling and the namespace-object return value.",
    correct: "It loads a module on demand and returns a Promise of its namespace, creating a separate chunk when bundled",
    wrong: [
      "It loads the module synchronously and returns its default export directly, which blocks the main thread",
      "It is only available inside ES module files, and cannot be called from classic non-module scripts at all",
      "It loads the module again on every call and re-runs its top-level code each time it is called",
    ],
  }),
  q({
    topic: "what-are-bigint-numbers",
    title: "What are BigInt numbers?",
    level: "mid",
    tags: ["javascript", "numbers"],
    prompt: "Why does `9007199254740993 + 1` look wrong, and what happens if you try `10n + 1`?",
    hints: ["Number is a 64-bit float with a safe integer limit.", "BigInt and Number do not mix in arithmetic."],
    approach: "State the safe integer limit, how BigInt fixes it, and the type-mixing and JSON restrictions.",
    solution:
      "`Number` is an IEEE 754 double, so integers are exact only up to `Number.MAX_SAFE_INTEGER` (2^53 − 1). Beyond that, neighbouring integers collapse to the same float, so large IDs and money in minor units can silently corrupt. `BigInt` stores arbitrary-precision integers, written with an `n` suffix or `BigInt(value)`. `10n + 1` throws a TypeError because mixing BigInt and Number in arithmetic is not allowed, so convert explicitly. Division truncates toward zero (`7n / 2n` is `3n`). `typeof` returns `\"bigint\"`, `Math` functions do not accept it, and `JSON.stringify` throws on it, so serialise as a string. Comparison with `==` and `<` works across types, but `===` does not. Use BigInt for IDs from APIs that exceed 53 bits. It is slower than Number and should not be the default for ordinary maths.",
    notes: "The TypeError on mixed arithmetic and the JSON.stringify failure are the practical points.",
    correct: "10n + 1 throws a TypeError. BigInt is arbitrary-precision and must be converted explicitly to mix with Number",
    wrong: [
      "10n + 1 returns 11n because the plain number is promoted to BigInt automatically during arithmetic",
      "10n + 1 returns 11 because BigInt values are converted to Number whenever they appear in arithmetic",
      "BigInt only supports values up to 2^64, and JSON.stringify serialises it to a plain number without error",
    ],
  }),
  q({
    topic: "explain-service-workers-basics",
    title: "Explain Service Workers basics",
    level: "senior",
    tags: ["browser", "offline"],
    prompt: "You ship a new service worker and some users keep seeing the old version of your app. What is happening?",
    hints: ["A new worker installs and then waits for old clients to close.", "skipWaiting and clients.claim change that."],
    approach: "Cover the lifecycle, scope, fetch interception, and how updates are activated.",
    solution:
      "A service worker is a script that runs in its own thread, has no DOM access, and acts as a programmable proxy for network requests within its scope. It needs HTTPS (localhost is exempt). The lifecycle is register, install (a good time to pre-cache), then waiting, then activate (a good time to delete old caches). When you deploy a new worker, the browser installs it but keeps the old one in control until every tab using it closes, so some users keep the old assets. `self.skipWaiting()` skips the waiting phase and `clients.claim()` lets the new worker control open pages immediately, but swapping code under a running page can cause version mismatches, so many apps instead show an update prompt. The browser checks for a new worker file on navigation and treats a byte difference as an update, so never cache the worker script itself aggressively. The worker can be killed at any time, so keep no state in globals and use `event.waitUntil` for async work.",
    notes: "The waiting phase and the version-mismatch trade-off of skipWaiting are the points to listen for.",
    correct: "The new worker is waiting. It does not take control until all tabs using the old one close, unless you skipWaiting and claim",
    wrong: [
      "The browser caches the worker script forever, so nothing can update it without a manual reset of site data",
      "The new worker replaces the old one instantly on deploy, so the stale pages must be coming from the CDN",
      "Service workers update only when the user clears site data or reinstalls the browser, never on navigation",
    ],
  }),
  q({
    topic: "explain-intersectionobserver",
    title: "Explain IntersectionObserver",
    level: "mid",
    tags: ["browser", "performance"],
    prompt: "You implement infinite scroll and lazy loading with a scroll listener and getBoundingClientRect, and it janks. What is the better API?",
    hints: ["It reports visibility changes asynchronously.", "Options include root, rootMargin, and threshold."],
    approach: "Explain the API, its options, and why it avoids layout thrashing, then list typical uses.",
    solution:
      "`IntersectionObserver` calls your callback when a target element crosses given visibility thresholds relative to a root (the viewport by default). It delivers entries asynchronously with `isIntersecting` and `intersectionRatio`, so you do not run code on every scroll event and you avoid calling `getBoundingClientRect`, which forces layout. `rootMargin` expands or shrinks the root box, which is how you start loading an image before it reaches the viewport, and `threshold` sets the ratios that trigger the callback. Typical uses are lazy loading, infinite scroll with a sentinel element at the end of the list, viewability analytics, and pausing offscreen animations or video. Call `unobserve` after the first hit for one-shot work and `disconnect` on cleanup. Native `loading=\"lazy\"` covers simple images without any script. The observer reports geometry, not whether the element is covered by another element.",
    notes: "Look for rootMargin for prefetching and the sentinel pattern.",
    correct: "IntersectionObserver reports visibility asynchronously, avoiding scroll listeners and forced layout",
    wrong: [
      "IntersectionObserver fires on every scroll event but debounces it so layout is cheaper",
      "IntersectionObserver reports when an element is covered by another element in the stacking order, so it replaces z-index debugging in DevTools",
      "IntersectionObserver reports when an element’s size changes, replacing ResizeObserver",
    ],
  }),
  q({
    topic: "what-is-mutationobserver",
    title: "What is MutationObserver?",
    level: "mid",
    tags: ["browser", "dom"],
    prompt: "A third-party widget injects nodes into your page and you need to react. What does MutationObserver give you, and what is the trap?",
    hints: ["Callbacks are batched and delivered as microtasks.", "Mutating inside the callback can re-trigger it."],
    approach: "Describe the config options, batching, and the infinite-loop and performance pitfalls.",
    solution:
      "`MutationObserver` watches a DOM subtree and reports changes in batches. You call `observe(node, { childList, attributes, characterData, subtree })` and the callback receives a list of `MutationRecord`s describing what changed. It replaced the old Mutation Events, which fired synchronously and were slow. Records are delivered as a microtask after the current script finishes, so several changes arrive together. The trap is that changing the observed nodes inside the callback creates new records and can cause an endless loop, so disconnect first or filter your own changes. Observing `subtree` on `document.body` with every option set is expensive on busy pages, so scope it narrowly and use `attributeFilter`. Call `disconnect()` on cleanup, and `takeRecords()` to drain pending records. For element size changes use `ResizeObserver`, and for visibility use `IntersectionObserver`.",
    notes: "The re-entrancy trap is the key. Mention microtask batching for extra credit.",
    correct: "It reports batched DOM changes as microtasks. Mutating observed nodes inside the callback can cause a loop",
    wrong: [
      "It reports each DOM change synchronously, so you can block the change from happening",
      "It reports CSS layout changes such as resizing and is the recommended way to watch element size",
      "It reports network requests made by the page and can cancel them before they are sent",
    ],
  }),
  q({
    topic: "explain-passive-event-listeners",
    title: "Explain passive event listeners",
    level: "mid",
    tags: ["browser", "events", "performance"],
    prompt: "Scrolling feels laggy on mobile because of a touchmove handler. What does `{ passive: true }` change?",
    hints: ["The browser normally waits to learn if the handler calls preventDefault.", "A passive handler promises not to."],
    approach: "Explain scroll blocking, what passive promises, what happens if you break the promise, and the default for some events.",
    solution:
      "For touch and wheel events, the browser cannot start scrolling until it knows whether a handler will call `preventDefault()` to cancel the scroll, so a slow handler delays every scroll. Registering with `{ passive: true }` is a promise that the handler will not call `preventDefault()`, so the browser can scroll on the compositor thread without waiting. If a passive handler calls `preventDefault()` anyway it is ignored and the console warns. Browsers make `touchstart`, `touchmove`, and `wheel` listeners passive by default when attached to `window`, `document`, or `body`. If you really need to cancel scrolling, set `passive: false` and keep the handler fast, and prefer the CSS property `touch-action` to declare which gestures the element handles. Passive listeners are about scroll responsiveness, not about handler order or propagation.",
    notes: "Check that the candidate knows preventDefault is ignored, and that touch-action is the declarative alternative.",
    correct: "It promises the handler will not call preventDefault, so the browser can scroll without waiting for it",
    wrong: [
      "It makes the handler run after every other listener so it cannot slow down the event",
      "It runs the handler once and then removes it, so it cannot fire repeatedly during scroll, which is the main reason it improves scrolling performance",
      "It stops the event bubbling, so parent elements are not blocked from scrolling",
    ],
  }),
  q({
    topic: "what-is-pointer-events-vs-mouse-events",
    title: "What are pointer events vs mouse events?",
    level: "mid",
    tags: ["browser", "events"],
    prompt: "You support mouse, touch, and pen for a drawing canvas. Why use pointer events instead of separate mouse and touch handlers?",
    hints: ["One event model covers all input types.", "Pointer capture keeps events flowing during a drag."],
    approach: "Describe the unified model, the extra properties, pointer capture, and touch-action.",
    solution:
      "Pointer events (`pointerdown`, `pointermove`, `pointerup`, `pointercancel`) provide one model for mouse, touch, and pen, so you write one handler instead of two. Each event has a `pointerId` for tracking several fingers, a `pointerType`, and pressure and tilt for pens. `setPointerCapture(pointerId)` routes later events to one element even if the pointer leaves it, which is the right way to build drags and sliders. Handle `pointercancel`, which fires when the browser takes over a gesture such as scrolling. For touch, the CSS `touch-action` property (for example `none` on a canvas) tells the browser not to scroll or zoom, otherwise it will cancel your pointer stream. Mouse events still exist, and browsers fire compatibility mouse events after touch, which is why mixing both causes double handling. Pointer events are widely supported in current browsers.",
    notes: "Pointer capture and touch-action are the practical details. Pointercancel is a common miss.",
    correct: "Pointer events unify mouse, touch and pen, with pointer capture and touch-action to control gestures",
    wrong: [
      "Pointer events only fire for pens, and mouse and touch need their own separate handlers, so pointer capture and touch-action are not needed for gestures",
      "Pointer events fire only after the finger is lifted, so they cannot support dragging",
      "Pointer events replace CSS hover, so :hover rules stop working on touch devices",
    ],
  }),
  q({
    topic: "what-is-iframe-sandbox-attribute",
    title: "What is the iframe sandbox attribute?",
    level: "senior",
    tags: ["security", "html"],
    prompt: "You embed user-supplied HTML in an iframe with `sandbox=\"allow-scripts allow-same-origin\"` and it is served from your own origin. What is the problem?",
    hints: ["An empty sandbox attribute applies every restriction.", "Each token re-enables a capability."],
    approach: "Explain default restrictions, how tokens loosen them, and why scripts plus same-origin is dangerous for same-origin content.",
    solution:
      "An iframe with a bare `sandbox` attribute is heavily restricted: it runs in a unique opaque origin, cannot run scripts, submit forms, open popups, or navigate the top page. Each token such as `allow-scripts`, `allow-forms`, `allow-popups`, or `allow-same-origin` lifts one restriction. Combining `allow-scripts` with `allow-same-origin` on content from the same origin as the parent is unsafe, because the framed script can reach the parent through `window.parent`, or simply remove the sandbox attribute from its own iframe element and reload without restrictions. The safe pattern for untrusted content is to serve it from a separate origin (a different domain, not just a subdomain you share cookies with) and give it the fewest tokens it needs. Pair it with a Content Security Policy on the framed document and `postMessage` with strict origin checks to talk to it.",
    notes: "The scripts plus same-origin escape is the question’s core. Separate origin is the real fix.",
    correct: "The framed script can reach the parent or remove its own sandbox, so untrusted content needs a separate origin",
    wrong: [
      "Nothing; allow-scripts and allow-same-origin together is the recommended secure setup for user content, because the sandbox still blocks the framed script from reaching the parent",
      "allow-same-origin forces the iframe to share cookies with every other website open in the browser",
      "The combination is ignored by browsers, so the iframe stays fully sandboxed whatever the tokens say",
    ],
    refs: [{ site: "mdn", url: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#sandbox" }],
  }),
  q({
    topic: "explain-subresource-integrity-sri",
    title: "Explain Subresource Integrity (SRI)",
    level: "mid",
    tags: ["security", "html"],
    prompt: "You load a library from a CDN. How does SRI protect you, and what must you add besides the hash?",
    hints: ["The browser compares the file against a hash you provide.", "Cross-origin loads need CORS."],
    approach: "Describe the integrity attribute, what happens on mismatch, the crossorigin requirement, and the limits.",
    solution:
      "Subresource Integrity lets you pin the exact contents of a script or stylesheet. You add `integrity=\"sha384-...\"` (a base64 hash) and for cross-origin files also `crossorigin=\"anonymous\"`, which makes the request use CORS so the browser can read the bytes to hash them. If the downloaded file does not match, the browser refuses to execute or apply it, so a compromised or tampered CDN cannot inject code. The trade-offs are that any change to the file, even a harmless CDN edit, breaks loading, so it only suits versioned, immutable URLs. It covers external files you reference, not scripts those files load later, and it does nothing for first-party code you control. It also does not protect against a malicious but correctly hashed version, so it complements dependency review rather than replacing it. Generate hashes in the build and fail the build when they drift.",
    notes: "The crossorigin requirement is the common miss. Versioned URLs are the usage rule.",
    correct: "The integrity hash makes the browser refuse a tampered file. Cross-origin loads also need the crossorigin attribute",
    wrong: [
      "The hash encrypts the file in transit, so the crossorigin attribute is not needed for cross-origin loads",
      "The browser repairs a file that fails the hash check by fetching a fresh copy from the origin server",
      "The hash also covers every script that the loaded library later injects or imports at runtime",
    ],
    refs: [{ site: "mdn", url: "https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity" }],
  }),
  q({
    topic: "what-is-trusted-types",
    title: "What is Trusted Types?",
    level: "senior",
    tags: ["security", "xss"],
    prompt: "A code review keeps finding innerHTML assignments. How can Trusted Types make DOM XSS harder to introduce?",
    hints: ["It is enforced through CSP.", "Dangerous sinks accept only special typed values."],
    approach: "Explain the CSP directive, the sinks, policies, and the migration strategy.",
    solution:
      "Trusted Types is a browser feature that locks down DOM XSS sinks. With the CSP directive `require-trusted-types-for 'script'`, sinks such as `innerHTML`, `outerHTML`, `document.write`, `eval`, and `script.src` reject plain strings and accept only `TrustedHTML`, `TrustedScript`, or `TrustedScriptURL` objects. Those objects can only be created by a named policy that you define, for example one that runs DOMPurify, so the places that can produce markup shrink to a few reviewable functions rather than every assignment in the codebase. A `trusted-types` directive lists allowed policy names. Rollout uses report-only mode first to find offenders, then enforcement. Frameworks and libraries must support it, and browser support has been uneven, so check current compatibility and treat it as defence in depth next to output encoding, sanitisation, and a strict CSP. A bad policy that trusts everything defeats the point.",
    notes: "Good answers say it narrows the review surface and mention report-only rollout.",
    correct: "It requires typed values from named policies at sinks like innerHTML, shrinking where unsafe HTML can be created",
    wrong: [
      "It automatically sanitises every string assigned to innerHTML without any policy or code changes, so existing innerHTML assignments need no review at all",
      "It signs scripts with a certificate so only scripts from trusted domains are allowed to run",
      "It blocks all network requests to domains not listed in an allowlist maintained by the browser vendor",
    ],
    refs: [{ site: "mdn", url: "https://developer.mozilla.org/en-US/docs/Web/API/Trusted_Types_API" }],
  }),
  q({
    topic: "explain-feature-detection-vs-browser-sniffing",
    title: "Explain feature detection vs browser sniffing",
    level: "beginner",
    tags: ["browser", "compat"],
    prompt: "Your code checks `navigator.userAgent.includes(\"Chrome\")` to decide whether to use an API. What is a better approach?",
    hints: ["Ask whether the capability exists, not who the browser is.", "User agent strings are unreliable."],
    approach: "Contrast the two, give detection examples, and explain why UA sniffing breaks.",
    solution:
      "Browser sniffing infers capabilities from the user agent string, which is brittle: strings are spoofed, shared (every Chromium browser says Chrome), and increasingly frozen or reduced by vendors. Feature detection tests for the capability itself, so it keeps working when a new browser adds it or an old one is updated. Examples: `'IntersectionObserver' in window`, `typeof structuredClone === 'function'`, `CSS.supports('display', 'grid')`, or `@supports (display: grid)` in CSS. Detect, then use the API or load a fallback or polyfill. Detection can be wrong when an API exists but is buggy, in which case you test the behaviour, or as a last resort, narrow sniffing for a known bug. Progressive enhancement builds on detection: a working baseline, then extra features where supported. Server-side, use client hints or `Accept` headers instead of parsing the user agent.",
    notes: "Check that the candidate can name a concrete detection call, not just the principle.",
    correct: "Test whether the capability exists, for example with `in window` or `CSS.supports`, instead of parsing the user agent",
    wrong: [
      "Parse the user agent more carefully with a regular expression, since it is the only reliable signal",
      "Check `navigator.appVersion` against a list of versions, which is updated by the browser on each release, so it is more dependable than the user agent string",
      "Use `try/catch` around the whole page script and reload the page if it throws once",
    ],
  }),
  q({
    topic: "what-is-polyfill-vs-transpile",
    title: "What is a polyfill vs transpiling?",
    level: "mid",
    tags: ["tooling", "compat"],
    prompt: "Your bundle targets older browsers. Optional chaining and `Array.prototype.at` both fail there. Which fix applies to which?",
    hints: ["One is new syntax. The other is a new runtime API.", "A parser error cannot be patched at runtime."],
    approach: "Define each, map syntax to transpiling and APIs to polyfills, and mention how build targets control both.",
    solution:
      "Transpiling rewrites newer syntax into older syntax at build time. `a?.b` becomes a conditional expression, so old engines can parse it. A polyfill adds a missing runtime API by defining it on the global or prototype if it does not exist, such as `Array.prototype.at` or `Promise.allSettled`. Syntax cannot be polyfilled, because an engine that cannot parse the file throws before any code runs. Most APIs cannot be transpiled, because they are library features and not grammar. In practice Babel or SWC handle syntax, driven by a browserslist target, and `core-js` supplies polyfills, injected per usage or per entry. Polyfilling globals can conflict across libraries, so prefer pure or ponyfill versions in libraries. Raising the browser target removes transform and polyfill weight, which is one of the cheapest bundle-size wins.",
    notes: "Listen for the syntax versus API split and for browserslist as the control point.",
    correct: "Transpile the syntax (optional chaining) at build time. Polyfill the missing API (Array.prototype.at) at runtime",
    wrong: [
      "Polyfill the syntax and transpile the API, since polyfills rewrite code and transpilers add missing methods",
      "Both are fixed by a transpiler alone, so no extra runtime code is ever needed for the older browsers",
      "Both are fixed by a polyfill alone, because polyfills can add new grammar to the parser at runtime",
    ],
  }),
  q({
    topic: "explain-error-types-typeerror-referenceerror-rangeerror",
    title: "Explain error types: TypeError, ReferenceError, RangeError",
    level: "beginner",
    tags: ["javascript", "errors"],
    prompt: "Which error does each of these throw: `undefinedVar`, `null.x`, and `new Array(-1)`?",
    hints: ["One name is not declared. One value is the wrong type. One number is out of range.", "Infinite recursion also hits one of these."],
    approach: "Map each snippet to its error and say what condition each class represents.",
    solution:
      "`ReferenceError` means a name cannot be resolved: an undeclared variable, or a `let` or `const` read before its declaration (the temporal dead zone). `TypeError` means a value is not of the type an operation needs: reading a property of `null` or `undefined`, calling something that is not a function, or assigning to a read-only property in strict mode. `RangeError` means a value is outside the allowed range: `new Array(-1)`, `toFixed(101)`, or exceeding the call stack with unbounded recursion (`Maximum call stack size exceeded`). `SyntaxError` is thrown at parse time, for example by `JSON.parse` on bad text, and `URIError` by malformed `decodeURIComponent`. All extend `Error`, so `instanceof` and the `name` property let you branch. Catch narrowly and rethrow what you do not handle, because swallowing a TypeError often hides a real bug.",
    notes: "Stack overflow as RangeError and TDZ as ReferenceError are the typical stumbling points.",
    correct: "ReferenceError, TypeError, RangeError",
    wrong: [
      "TypeError, ReferenceError, SyntaxError",
      "ReferenceError, ReferenceError, TypeError",
      "SyntaxError, TypeError, RangeError",
    ],
  }),

  q({
    topic: "what-is-typescript-structural-typing",
    title: "What is TypeScript structural typing?",
    level: "mid",
    tags: ["typescript", "types"],
    prompt: "You pass a `{ x: 1, y: 2, z: 3 }` variable to a function that expects `{ x: number; y: number }` and it compiles, but the object literal version errors. Why?",
    hints: ["Compatibility depends on shape, not on declared names.", "Excess property checks apply only to fresh object literals."],
    approach: "Explain structural compatibility, then excess property checking and the exceptions such as private members.",
    solution:
      "TypeScript compares types by structure: a value is assignable to a type if it has at least the required members with compatible types, regardless of what the types are called. That is why a variable with extra properties is fine: it still has `x` and `y`. When you write an object literal directly where a type is expected, TypeScript applies an extra check, excess property checking, to catch typos such as `{ x: 1, yy: 2 }`, so the same data errors in a literal but not through a variable. Classes with `private` or `protected` members are effectively nominal, since only the same declaration can satisfy them. Structural typing makes mocks and test doubles easy but means two unrelated types with the same shape are interchangeable, which is why branded types exist when you need to keep IDs apart.",
    notes: "Check that the candidate separates freshness from structure. Branding is a good follow-up.",
    correct: "Types match by shape, so extra properties are allowed, but fresh object literals get an excess property check",
    wrong: [
      "Types match by declared name, so a variable with extra properties is always rejected by the compiler",
      "Excess property checks apply only to variables and never to object literals written inline",
      "Types match by shape only for interfaces, and type aliases are always compared by their declared name",
    ],
    refs: tsRefs,
  }),
  q({
    topic: "what-are-generics-in-typescript",
    title: "What are generics in TypeScript?",
    level: "mid",
    tags: ["typescript", "generics"],
    prompt: "Why write `function first<T>(items: T[]): T | undefined` instead of using `any`?",
    hints: ["A type parameter links the input type to the output type.", "Constraints narrow what T may be."],
    approach: "Explain type parameters, inference, constraints with extends, and defaults.",
    solution:
      "A generic is a function or type with a type parameter that the compiler fills in per use. In `first<T>(items: T[]): T | undefined`, calling `first([1, 2])` infers `T` as `number`, so the result is `number | undefined`. With `any` the link between input and output is lost and every check is turned off. Constraints restrict the parameter: `function pick<T, K extends keyof T>(obj: T, key: K): T[K]` ensures `key` is a real key of `obj` and returns the precise property type. Defaults (`<T = string>`) and generic types, classes, and interfaces (`Promise<T>`, `Array<T>`) follow the same idea. Let inference work and avoid passing type arguments by hand where the compiler can infer them. A type parameter that appears only once in a signature is usually a sign you do not need a generic.",
    notes: "A good tip is the used-once rule. Check that they know constraints with extends keyof.",
    correct: "A type parameter ties the result type to the input type while keeping full checking, which any cannot do",
    wrong: [
      "Generics make the function run faster because the compiler emits specialised code for each type, since each call site gets its own compiled copy",
      "Generics are erased and checked at runtime, so a wrong type throws when the function is called",
      "Generics are the same as any but allow the compiler to print nicer hover text",
    ],
    refs: tsRefs,
  }),
  q({
    topic: "explain-const-assertions",
    title: "Explain const assertions",
    level: "mid",
    tags: ["typescript", "types"],
    prompt: "`const roles = ['admin', 'user']` infers `string[]`. How do you derive a union of the literal values from it?",
    hints: ["`as const` makes literals narrow and arrays readonly tuples.", "Index into the type with number."],
    approach: "Show the inferred type with and without as const, then derive the union with typeof and indexed access.",
    solution:
      "Without help, TypeScript widens `['admin', 'user']` to `string[]`. A const assertion, `as const`, tells the compiler to keep the narrowest type: the array becomes `readonly ['admin', 'user']`, string literals stay literal, and object properties become `readonly`. Then `type Role = (typeof roles)[number]` yields `'admin' | 'user'`, so the list is the single source of truth for both runtime values and the type. It works for objects too: `const routes = { home: '/', about: '/about' } as const` then `keyof typeof routes`. Note `as const` is a compile-time assertion only and does not freeze the value at runtime, so use `Object.freeze` if you need that. The `satisfies` operator pairs well, since it checks the shape without widening. `as const` only applies to literal expressions, not to arbitrary variables.",
    notes: "Typeof plus indexed access is the essential trick. Mention that as const does not freeze at runtime.",
    correct: "Use `as const`, then `(typeof roles)[number]` to get the union of the literal values",
    wrong: [
      "Use `as const`, which also freezes the array at runtime so the union cannot change",
      "Use `keyof roles`, which returns the union of the strings stored inside the array",
      "Use `typeof roles`, which already evaluates to 'admin' | 'user' without any assertion",
    ],
    refs: tsRefs,
  }),
  q({
    topic: "what-are-conditional-types",
    title: "What are conditional types?",
    level: "senior",
    tags: ["typescript", "types"],
    prompt: "What does `type ToArray<T> = T extends any ? T[] : never` produce for `string | number`, and why?",
    hints: ["Conditional types distribute over naked type parameters that are unions.", "Wrapping in a tuple turns that off."],
    approach: "Define the syntax, explain distribution with the example, and show how to disable it and how infer works.",
    solution:
      "A conditional type has the form `T extends U ? X : Y` and chooses a type based on a relationship. When `T` is a naked type parameter and you pass a union, the condition distributes: it is applied to each member separately and the results are unioned. So `ToArray<string | number>` is `string[] | number[]`, not `(string | number)[]`. To prevent distribution, wrap both sides in tuples: `[T] extends [any] ? T[] : never` gives `(string | number)[]`. The `infer` keyword captures a type inside the true branch, for example `T extends Promise<infer R> ? R : T` unwraps a promise, and built-ins such as `Exclude`, `Extract`, `NonNullable`, `ReturnType`, and `Awaited` are written this way. Distribution over `never` yields `never`, which surprises people. Deep conditional types slow the compiler, so keep them shallow and tested.",
    notes: "Distribution is the discriminator. A candidate who can also write Awaited-style infer is strong.",
    correct: "string[] | number[], because the condition distributes over each member of the union",
    wrong: [
      "(string | number)[], because the condition evaluates once on the whole union",
      "never, because string | number does not extend any in a conditional type",
      "string[] & number[], because distribution intersects the results instead of uniting them",
    ],
    refs: tsRefs,
  }),
  q({
    topic: "explain-mapped-types",
    title: "Explain mapped types",
    level: "senior",
    tags: ["typescript", "types"],
    prompt: "How would you write a type that makes every property of `T` optional and nullable, and drops `readonly`?",
    hints: ["Iterate keys with `[K in keyof T]`.", "Modifiers use + and - prefixes."],
    approach: "Show the basic form, modifiers, key remapping with `as`, and name the built-ins that use it.",
    solution:
      "A mapped type creates a new object type by iterating keys: `type Loose<T> = { -readonly [K in keyof T]?: T[K] | null }`. The `?` makes properties optional, `| null` widens the value, and `-readonly` removes the readonly modifier (`+readonly` adds it, `-?` removes optionality, which is how `Required<T>` works). Key remapping uses `as`: `{ [K in keyof T as `get${Capitalize<string & K>}`]: () => T[K] }` renames keys, and mapping a key to `never` filters it out. Built-ins such as `Partial`, `Readonly`, `Pick`, and `Record` are mapped types. Mapped types over a union of keys (not `keyof T`) build lookup types. They are homomorphic, preserving modifiers, when written over `keyof T`. They are shallow, so nested objects need a recursive version.",
    notes: "Look for modifiers with + and -, and for `as` remapping.",
    correct: "`{ -readonly [K in keyof T]?: T[K] | null }`",
    wrong: [
      "`{ readonly [K in keyof T]: T[K] | null }`",
      "`{ [K of keyof T]?: T[K] | null }`",
      "`Partial<T> & Nullable<T> & Mutable<T>` using built-in utility types with no custom code",
    ],
    refs: tsRefs,
  }),
  q({
    topic: "explain-branded-types",
    title: "Explain branded types",
    level: "senior",
    tags: ["typescript", "types"],
    prompt: "A function takes `userId: string` and `orderId: string` and you keep swapping them. How do branded types help, and what do they cost at runtime?",
    hints: ["Intersect the base type with a phantom property.", "The brand exists only in the type system."],
    approach: "Show the pattern, how values acquire the brand safely, and say it has no runtime cost.",
    solution:
      "Because TypeScript is structural, two string aliases are interchangeable. A brand adds a phantom property so they are not: `type UserId = string & { readonly __brand: 'UserId' }` and `type OrderId = string & { readonly __brand: 'OrderId' }`. Now passing an `OrderId` where a `UserId` is expected is a compile error. A value gets the brand through a single constructor or validator: `function toUserId(s: string): UserId { if (!s) throw ...; return s as UserId }`, so the cast lives in one reviewed place. At runtime nothing changes: the value is still a plain string and the `__brand` property never exists, so there is no cost. Brands suit IDs, validated emails, sanitised HTML, and units such as `Meters`. They give no protection against code that casts freely, and they need care when you serialise and parse values from the network, since parsed data is unbranded until validated.",
    notes: "Check that the cast is centralised and that the candidate knows the brand is erased.",
    correct: "Intersect the base type with a phantom brand so swapped IDs fail to compile. There is no runtime cost",
    wrong: [
      "Wrap each ID in a class instance, which adds an object allocation and a runtime check on every call",
      "Declare both IDs as the same string alias, since TypeScript already compares aliases by name",
      "Use `enum` members as the ID values, which are checked at runtime and rejected if mixed",
    ],
    refs: tsRefs,
  }),
  q({
    topic: "what-is-the-difference-between-void-and-never",
    title: "What is the difference between void and never?",
    level: "mid",
    tags: ["typescript", "types"],
    prompt: "A function `fail(msg): never` throws, and `log(msg): void` prints. Why do they have different types, and what is `never` useful for?",
    hints: ["void means the return value should be ignored.", "never means the function cannot return normally."],
    approach: "Define each, give examples, and show never in exhaustiveness checks.",
    solution:
      "`void` is the return type of a function that completes but returns nothing useful. A callback typed `() => void` may actually return a value, which is ignored, so `arr.forEach(x => results.push(x))` type-checks. `never` is the type of something that cannot happen: a function that always throws or loops forever, or an impossible intersection such as `string & number`. Code after a call to a `never` function is unreachable. `never` is assignable to every type, and nothing except `never` is assignable to it. That makes it the tool for exhaustiveness checking: in the default branch of a switch over a union, `const _x: never = value` errors if a new member is added and not handled. In conditional types `never` acts as the empty union, which is why it filters members out.",
    notes: "Exhaustiveness checking is the practical payoff. Candidates should also know void callbacks can return values.",
    correct: "void is a completed call with an ignorable result. never is a call that cannot return, used for exhaustiveness checks",
    wrong: [
      "void is for functions that throw and never is for functions that return undefined, so the two are swapped",
      "They are aliases, and the compiler treats void and never identically in every position where a type is used",
      "never is the type of null and undefined values, and void is the type of an empty object literal",
    ],
    refs: tsRefs,
  }),
  q({
    topic: "explain-enum-pitfalls-in-typescript",
    title: "Explain enum pitfalls in TypeScript",
    level: "senior",
    tags: ["typescript", "enums"],
    prompt: "Your team debates banning `enum`. What are the real pitfalls, and what is the usual alternative?",
    hints: ["Enums emit runtime code.", "const enum interacts badly with some build tools."],
    approach: "List the runtime emit, numeric looseness, const enum and isolatedModules issues, and the union-of-literals alternative.",
    solution:
      "Unlike most TypeScript features, an `enum` is not erased: it compiles to a runtime object, adding code and a construct that type-stripping tools such as Node’s type stripping do not support. Numeric enums create a reverse mapping, so `Object.keys` returns both names and numbers, and before TypeScript 5.0 any number was assignable to a numeric enum. `const enum` inlines values and avoids the object, but breaks with `isolatedModules` and with Babel or esbuild per-file compilation, and it is awkward across package boundaries. Enum members from different enums are never interchangeable even when values match, which is sometimes wanted and sometimes a nuisance. The common alternative is a union of literals plus an `as const` object: `const Status = { Active: 'active', Off: 'off' } as const; type Status = (typeof Status)[keyof typeof Status]`. It is erased, works with plain JavaScript, and gives you iteration and values for free.",
    notes: "Strong answers mention emit and the isolatedModules constraint, not just ‘enums are bad’.",
    correct: "Enums emit runtime code and const enum breaks per-file compilers. A const object with a literal union avoids both",
    wrong: [
      "Enums are erased at compile time like interfaces, so you cannot iterate their members or read values at runtime",
      "Enums always use less memory than unions, so replacing them with literal unions makes bundles larger",
      "Enums cannot hold string values, so they cannot be used to represent an API status such as active",
    ],
    refs: tsRefs,
  }),
];
