import type { Question } from "@/lib/types";

const refs = [{ site: "mdn", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript" }];

function q(
  canonicalTopic: string,
  title: string,
  level: Question["level"],
  tags: string[],
  prompt: string,
  hints: string[],
  approach: string,
  solution: string,
  interviewerNotes: string,
  correct: string,
  wrong: [string, string, string],
): Question {
  return {
    id: `wave-${canonicalTopic}`,
    track: "quiz",
    level,
    title,
    tags,
    status: "ready",
    canonicalTopic,
    prompt,
    hints,
    approach,
    solution,
    interviewerNotes,
    sourceRefs: refs,
    options: [
      { id: "a", label: wrong[0] },
      { id: "b", label: correct, correct: true },
      { id: "c", label: wrong[1] },
      { id: "d", label: wrong[2] },
    ],
  };
}

export const quizWave: Question[] = [
  q(
    "explain-scope-chain-and-lexical-environment",
    "Explain scope chain and lexical environment",
    "beginner",
    ["javascript", "scope"],
    "Where does a function look up a free variable, and what does “lexical” mean?",
    ["Look at where the function was written, not where it was called.", "Inner scopes shadow outer bindings."],
    "Define lexical environment, then walk a nested function that reads an outer binding.",
    "A lexical environment is a scope’s bindings plus a link to its outer environment. When a function reads a name it does not declare, lookup walks that chain. The chain is fixed by where the function is written, so a callback still sees its outer locals after the outer function returns. An inner binding with the same name shadows the outer one.",
    "They want lexical lookup, not “the call stack decides this.”",
    "Lookup follows the environments where the function was written, walking outward until the binding is found",
    ["Variables are resolved from the call site only", "Every function shares one global scope", "The scope chain is rebuilt on every property access"],
  ),
  q(
    "what-is-the-difference-between-var-let-and-const",
    "What is the difference between var, let, and const?",
    "beginner",
    ["javascript", "scope"],
    "Contrast scope, redeclaration, and reassignment.",
    ["var is function-scoped.", "const blocks reassignment, not object mutation."],
    "Three-column answer: scope, temporal dead zone, reassignment.",
    "`var` is function-scoped (or global), hoisted as `undefined`, and can be redeclared in the same scope. `let` and `const` are block-scoped and throw if read before their declaration. `let` allows reassignment; `const` does not. A `const` object can still have its properties mutated because the binding, not the value’s internals, is frozen. Prefer `const`, then `let`.",
    "Mention mutation vs reassignment or the answer looks memorized.",
    "`var` is function-scoped; `let`/`const` are block-scoped; `const` forbids reassignment of the binding",
    ["const makes the object deeply immutable", "let is function-scoped like var", "const is hoisted as undefined and can be redeclared"],
  ),
  q(
    "explain-temporal-dead-zone",
    "Explain the temporal dead zone",
    "mid",
    ["javascript", "scope"],
    "Why does reading a `let` before its line throw, even though the binding was created?",
    ["The binding exists but is uninitialized.", "The zone ends when the declaration runs."],
    "Separate creation from initialization, then contrast with `var`.",
    "For `let`, `const`, and `class`, the binding is created when the scope is entered but stays uninitialized until the declaration statement executes. That gap is the temporal dead zone. Reading or assigning in it throws `ReferenceError`. `typeof` on that name also throws, unlike an undeclared variable. This catches accidental use-before-init that `var` would hide as `undefined`.",
    "Say uninitialized, not “the variable does not exist yet.”",
    "The binding exists but is uninitialized until its declaration runs, so an early access throws",
    ["The variable is deleted until the line runs", "TDZ only exists in strict mode", "let is initialized to undefined like var"],
  ),
  q(
    "what-are-iifes-and-why-were-they-used",
    "What are IIFEs and why were they used?",
    "beginner",
    ["javascript"],
    "What problem did an immediately invoked function expression solve before modules?",
    ["Scripts shared one global scope.", "A function creates a private scope."],
    "Show the pattern, then say what replaced it.",
    "An IIFE is a function expression that runs as soon as it is defined, often `(function () { /* private */ })()`. Before modules, it kept helpers off the global object so two scripts did not clobber each other’s names, and it captured loop values in older `var` code. ES modules, block scope, and bundlers cover those cases now. You still see IIFEs in legacy bundles and some one-off isolation, but they are not the default structure for new app code.",
    "Tie the pattern to a real problem (globals), not just the syntax.",
    "A function run immediately to create a private scope, historically used to avoid globals",
    ["A class that constructs itself", "A replacement for async/await", "A way to disable hoisting entirely"],
  ),
  q(
    "explain-call-apply-and-bind",
    "Explain call, apply, and bind",
    "mid",
    ["javascript", "this"],
    "How do these set `this`, and when is each one the right tool?",
    ["call and apply invoke now.", "bind returns a function."],
    "One sentence each, then a callback example for bind.",
    "`fn.call(thisArg, a, b)` and `fn.apply(thisArg, [a, b])` invoke `fn` immediately with an explicit `this`. The difference is argument shape: a list versus an array-like list. `fn.bind(thisArg, ...partial)` does not call now; it returns a function with `this` and any leading arguments fixed. Use `bind` (or an arrow) when passing a method as a callback so it does not lose its receiver. Arrow functions ignore these because they have no own `this`.",
    "They should know bind is delayed and arrows are unaffected.",
    "call/apply invoke immediately with a chosen this; bind returns a function with this fixed",
    ["All three always run the function immediately", "bind changes the prototype", "apply takes arguments one by one and call takes an array"],
  ),
  q(
    "what-is-the-difference-between-arrow-functions-and-function-declarations",
    "Arrow functions vs function declarations",
    "beginner",
    ["javascript"],
    "Name the differences that matter in UI code: `this`, `arguments`, constructors, and hoisting.",
    ["Arrows do not have their own this.", "You cannot use new on an arrow."],
    "List behavioral differences, then pick a React example.",
    "A function declaration is hoisted and has its own `this`, `arguments`, and `prototype`, so it can be constructed with `new`. An arrow function is an expression: it is not hoisted as a declaration, captures `this` and `arguments` from the enclosing scope, and cannot be used as a constructor. In components, arrows are convenient for handlers that should keep component `this` historically, and regular functions are better when you need a prototype method or a hoisted helper.",
    "Own `this` vs lexical `this` is the distinction they are grading.",
    "Arrows capture this lexically, are not constructible, and are not declaration-hoisted",
    ["Arrows are always faster", "Function declarations cannot close over variables", "Arrows automatically bind every argument by name"],
  ),
  q(
    "explain-rest-and-spread-operators",
    "Explain rest and spread",
    "beginner",
    ["javascript"],
    "Where do `...` mean different things, and do they deep-copy?",
    ["Rest collects the remainder.", "Spread expands an iterable or object’s own enumerable properties."],
    "Show three positions: function params, array, object. Call out shallow copy.",
    "Rest gathers remaining items into a real array, as in `function f(first, ...rest)`. Spread expands values: `[...items]` copies an iterable one level, `{...obj}` copies enumerable own properties one level, and a call `fn(...args)` passes them as separate arguments. Both are shallow. Nested objects stay shared, so `{...user}` does not clone `user.address`. Use them to avoid mutating inputs, not as a deep clone.",
    "Shallow vs deep is the follow-up they often ask immediately.",
    "Rest collects leftovers; spread expands a collection; both are shallow",
    ["Spread performs a deep clone", "Rest only works on objects", "They mutate the original array in place"],
  ),
  q(
    "explain-destructuring-assignment",
    "Explain destructuring assignment",
    "beginner",
    ["javascript"],
    "How do you pull fields out of objects and arrays, and how do defaults and renaming work?",
    ["The pattern mirrors the shape.", "Defaults apply when the value is undefined."],
    "One object example and one array example, plus a default.",
    "Destructuring assigns parts of a value by matching a pattern. `const { id, name: label = 'guest' } = user` reads `id`, renames `name` to `label`, and uses the default only if `name` is `undefined`. Arrays match by position: `const [first, , third] = list`. Defaults do not replace `null`. Nested patterns are fine when the shape is stable, but optional data is safer with a guard or optional chaining before deep destructuring.",
    "Defaults trigger on undefined, not null.",
    "Patterns pull values by shape; defaults apply only for undefined",
    ["Defaults replace null and undefined", "Destructuring always copies nested objects deeply", "You can only destructure arrays"],
  ),
  q(
    "what-is-a-symbol-and-when-do-you-use-it",
    "What is a Symbol and when do you use it?",
    "mid",
    ["javascript"],
    "Why would a property key be a Symbol instead of a string?",
    ["Symbols are unique.", "Well-known symbols customize language behavior."],
    "Uniqueness for extension keys, then one well-known symbol.",
    "A Symbol is a primitive key that is unique even when its description matches another symbol. `Symbol('id') !== Symbol('id')`. Use one when you need a property that will not collide with string keys from user data or other libraries, such as a hidden cache field on objects you do not own. Well-known symbols like `Symbol.iterator` let an object plug into language protocols. Symbols are not automatically private; `Object.getOwnPropertySymbols` can still see them. True privacy in classes is `#fields`.",
    "Collision avoidance plus protocols, not secrecy.",
    "A unique property key, useful to avoid collisions and to implement language protocols",
    ["A string that the engine encrypts", "A replacement for private class fields that Reflect cannot see", "An integer id generated by the runtime"],
  ),
  q(
    "explain-map-vs-object-vs-weakmap",
    "Map vs Object vs WeakMap",
    "mid",
    ["javascript"],
    "Which collection do you pick for string keys, arbitrary keys, or keys that must not leak memory?",
    ["Map preserves insertion order and accepts any key.", "WeakMap keys are objects and are not enumerable."],
    "State the job of each, then a DOM-node cache example for WeakMap.",
    "Use a plain object or record for a small dictionary of known string keys, especially data you want to JSON-serialize. Use `Map` when keys are not strings, when insertion order matters, or when you frequently add and delete keys; size is explicit and keys are not mixed with prototype properties. Use `WeakMap` when the key is an object (like a DOM node) that should be collectible once nothing else references it. WeakMap entries do not keep the key alive and cannot be iterated.",
    "The WeakMap GC point is the senior tell.",
    "Object for string dictionaries, Map for arbitrary keys, WeakMap for object keys that should not pin memory",
    ["WeakMap can use string keys and be iterated", "Map keys are always strings", "Object cannot store functions as values"],
  ),
  q(
    "what-is-the-difference-between-null-and-undefined",
    "null vs undefined",
    "beginner",
    ["javascript"],
    "Who sets each value, and how does `==` muddy the answer?",
    ["undefined means not assigned.", "null is an explicit empty value."],
    "Intent first, then equality and defaulting.",
    "`undefined` means a binding or property has no value: a missing argument, a missing property, or a variable declared without an initializer. `null` is an assigned value that means “empty on purpose,” often from an API. They are different types (`typeof null` is still the legacy 'object'). `null == undefined` is true, so `value == null` catches both; `===` does not. Optional chaining and `??` treat both as missing for defaults, while `||` also drops other falsy values like `0` and `''`.",
    "Mention `??` versus `||` if they talk about defaults.",
    "undefined is absence; null is an intentional empty value; == treats them as equal",
    ["They are the same value", "typeof null is 'null'", "?? only replaces null, not undefined"],
  ),
  q(
    "explain-nan-and-number-isnan",
    "Explain NaN and Number.isNaN",
    "beginner",
    ["javascript"],
    "Why is `NaN === NaN` false, and which check should you use?",
    ["NaN means an invalid numeric result.", "Global isNaN coerces."],
    "Give one producing operation, then the correct predicate.",
    "`NaN` is the numeric result of an invalid math operation, such as `0/0` or `Number('abc')`. It is the only value that is not strictly equal to itself, so `x !== x` is an old NaN test and `NaN === NaN` is false. The global `isNaN` coerces: `isNaN('foo')` is true because the string becomes `NaN`. `Number.isNaN` does not coerce, so it is true only for the actual `NaN` value. Prefer `Number.isNaN` when validating numbers.",
    "The coercion difference is the whole question.",
    "NaN is not equal to itself; Number.isNaN checks the value without coercion",
    ["NaN === NaN is true", "Number.isNaN('abc') is true", "NaN is the same as null"],
  ),
  q(
    "what-is-type-coercion-in-javascript",
    "What is type coercion?",
    "beginner",
    ["javascript"],
    "When does JavaScript convert types for you, and how do you keep that from surprising you?",
    ["`+` can concatenate or add.", "`==` converts."],
    "Name abstract operations briefly and recommend === and explicit conversion.",
    "Coercion is an automatic type conversion, usually through ToPrimitive, ToNumber, or ToString. `==` uses it, so `'' == 0` and `null == undefined` are true. The `+` operator concatenates if either side is a string after conversion. Prefer `===`, convert explicitly with `Number`, `String`, or `Boolean`, and treat input at the boundary of a form or API. Relying on coercion in business logic makes interview bugs and production bugs look the same: a value that “works” until a string sneaks in.",
    "They want a concrete surprise, not a definition only.",
    "Automatic conversion, especially with == and +, which is why explicit === and conversions are safer",
    ["Only TypeScript performs coercion", "=== also converts types before comparing", "Coercion never happens with the + operator"],
  ),
  q(
    "explain-truthy-and-falsy-values",
    "Truthy and falsy values",
    "beginner",
    ["javascript"],
    "Which values are falsy, and why is `if (count)` a bad check for zero?",
    ["There is a short falsy list.", "Everything else is truthy, including empty objects."],
    "List the falsy values, then show 0 and empty string as the product bugs.",
    "Falsy values are `false`, `0`, `-0`, `0n`, `''`, `null`, `undefined`, and `NaN`. Everything else is truthy, including `[]`, `{}`, and `'0'`. An `if (value)` test is fine for “missing or blank text” only when those empties should fail. It is wrong for a count or index, because `0` is a valid number and a valid index. Check `value == null` or `Number.isFinite(value)` when zero must stay.",
    "Calling out 0, '', and NaN separately is the signal.",
    "Only false, 0, -0, 0n, '', null, undefined, and NaN are falsy; 0 is a real count",
    ["Empty arrays are falsy", "Only false is falsy", "The string '0' is falsy"],
  ),
  q(
    "what-is-optional-chaining",
    "What is optional chaining?",
    "beginner",
    ["javascript"],
    "What does `user?.address?.city` short-circuit, and what does it not protect?",
    ["It stops on null or undefined.", "It does not catch a throw inside a called function after the check."],
    "Show property, call, and index forms.",
    "Optional chaining reads a property, calls a function, or indexes only if the base is neither `null` nor `undefined`; otherwise the expression is `undefined`. `user?.address?.city`, `onClick?.()`, and `rows?.[i]` are the three forms. It does not swallow errors once the call starts, and it does not default the value — pair it with `??` when you want a fallback. Do not use it to hide a required field that should throw in development.",
    "Short-circuit on nullish, not on every falsy value.",
    "It returns undefined instead of throwing when the base is null or undefined",
    ["It treats 0 and '' as missing", "It catches exceptions inside the function you call", "It assigns a default automatically"],
  ),
  q(
    "explain-nullish-coalescing",
    "Explain nullish coalescing",
    "beginner",
    ["javascript"],
    "How is `??` different from `||`?",
    ["?? only replaces null and undefined.", "|| replaces every falsy value."],
    "One example with 0 and one with empty string.",
    "`a ?? b` returns `b` only when `a` is `null` or `undefined`. `0`, `''`, and `false` stay. `a || b` returns `b` for every falsy `a`, which silently drops a real zero or an empty search string. Use `??` for default configuration and `||` only when any falsy value should fall through. You cannot mix `??` with `||` or `&&` without parentheses, because the precedence is intentionally restricted.",
    "The 0 example is the one they remember you for.",
    "`??` defaults only null and undefined, so 0 and '' are kept",
    ["?? treats 0 as missing", "|| keeps empty strings", "?? and || are identical in strict mode"],
  ),
  q(
    "explain-modules-esm-vs-commonjs",
    "ESM vs CommonJS",
    "mid",
    ["javascript", "tooling"],
    "How do import graphs, `this`, and live bindings differ between the two module systems?",
    ["ESM is static and can be analyzed.", "CommonJS require is a function call."],
    "Loading time, bindings, and interop pain.",
    "CommonJS loads with `require` and sets `module.exports` at runtime. Imports are copies of the exported value at require time in the usual case, and a cycle can see a partial `exports` object. ESM uses static `import`/`export`, which bundlers can tree-shake. ESM bindings are live: the importer sees later assignments to an exported `let`. ESM modules are strict, and `require` of an ESM file is not universally synchronous. In apps, pick ESM at the boundary and keep interop wrappers thin.",
    "Live bindings and static structure are the two points worth saying.",
    "ESM imports are static and live; CommonJS require runs at runtime and exports values on module.exports",
    ["Both formats are evaluated identically by every bundler", "CommonJS bindings are live by default", "ESM cannot export named functions"],
  ),
  q(
    "what-is-tree-shaking",
    "What is tree shaking?",
    "mid",
    ["javascript", "tooling"],
    "What has to be true for a bundler to drop unused exports?",
    ["The import graph must be static.", "Side effects block removal."],
    "Define dead-code elimination on module exports, then name one reason it fails.",
    "Tree shaking is dead-code elimination of unused ES module exports. Because `import` is static, a bundler can see that a page uses `formatDate` and omit `parseLegacy` from the same file. It fails when code is CommonJS, when a module has side effects the bundler cannot prove are unused, or when you import a whole namespace and touch it in a dynamic way. Mark packages with `sideEffects: false` only when it is true, or you will delete CSS or polyfills that the graph never “uses” explicitly.",
    "They want the side-effect caveat, not just “webpack removes code.”",
    "Unused ESM exports can be dropped when the bundler can prove they have no required side effects",
    ["It minifies identifiers only", "It works best on dynamic require calls", "It deletes unused CSS class names in the browser"],
  ),
];
