import type { Question } from "@/lib/types";
import { makeQuiz, mdn, nextRefs, owaspRefs, reactRefs, webDevRefs, type QuizInput } from "@/content/quiz-helpers";

const q = (input: QuizInput): Question => makeQuiz("wave4", input);

const wcag = [{ site: "w3c", url: "https://www.w3.org/WAI/WCAG22/quickref/" }];
const apg = [{ site: "w3c-apg", url: "https://www.w3.org/WAI/ARIA/apg/" }];

export const quizWave4: Question[] = [
  // ───────── CSS ─────────
  q({
    topic: "explain-the-cascade-origin-and-importance",
    title: "Explain the cascade: origin and importance",
    level: "mid",
    tags: ["css", "cascade"],
    prompt: "A rule with higher specificity sets `color: red` and a lower-specificity rule sets `color: blue !important`. Which wins, and in what order does the cascade decide?",
    hints: ["Origin and importance are compared before specificity.", "Layers and order of appearance come later."],
    approach: "List the cascade criteria in order, then apply them to the example.",
    solution:
      "The cascade resolves conflicts in a fixed order. First it compares origin and importance: transitions, then `!important` declarations from the user agent, user, and author in that order (important reverses origin precedence), then animations, then normal declarations from author, user, and user agent. Next come context (shadow DOM), then element-attached `style` attributes, then cascade layers, then specificity, then scope proximity, and finally order of appearance. Because importance is decided before specificity, the `blue !important` declaration wins even from a lower-specificity selector. `!important` also reverses layer order, so an important declaration in an earlier layer beats one in a later layer. Overusing `!important` forces the next override to use it as well, so prefer layers or lower specificity to manage conflicts.",
    notes: "Check that specificity is not presented as the first criterion.",
    correct: "blue wins, because importance is compared before specificity",
    wrong: [
      "red wins, because specificity is always compared first and !important only breaks ties",
      "red wins, because the later rule in the file always overrides an earlier one",
      "Neither wins; the browser drops both declarations when they conflict and uses the default colour",
    ],
  }),
  q({
    topic: "what-are-css-custom-properties-variables",
    title: "What are CSS custom properties (variables)?",
    level: "beginner",
    tags: ["css", "variables"],
    prompt: "Why can a CSS custom property change at runtime and cascade, while a Sass variable cannot?",
    hints: ["Custom properties live in the browser and follow the cascade.", "Sass variables are replaced at build time."],
    approach: "Explain inheritance, scoping, fallbacks, JavaScript access, and `@property`.",
    solution:
      "A custom property such as `--accent: #06f` is a real CSS property: it participates in the cascade, inherits down the tree, and is substituted where you write `var(--accent, fallback)` when the browser computes styles. So you can override it on a subtree (`.dark { --accent: #fb0 }`), change it in a media query, or set it from JavaScript with `el.style.setProperty('--accent', value)`, and every use updates. Sass variables are resolved at build time and leave no trace in the output, so they cannot respond to the DOM or to user settings. The fallback in `var()` applies only if the property is not defined. If it is defined but invalid for the property where it is used, the declaration becomes invalid at computed-value time and falls back to inherited or initial. Registering a property with `@property` adds a type, an initial value, and the ability to animate it.",
    notes: "Look for runtime scoping and the `invalid at computed-value time` nuance.",
    correct: "Custom properties are resolved by the browser and follow the cascade, so they can be scoped and changed at runtime",
    wrong: [
      "Custom properties are compiled away at build time, so they only work if the value never changes",
      "Custom properties are global only, so they cannot be overridden inside a component subtree",
      "Custom properties can be read by JavaScript but never written, since the CSSOM exposes them read-only, so scripts have to rewrite the stylesheet instead",
    ],
  }),
  q({
    topic: "explain-calc-and-min-max-clamp",
    title: "Explain calc() and min(), max(), clamp()",
    level: "mid",
    tags: ["css", "responsive"],
    prompt: "You want font size to scale with the viewport but never go below 1rem or above 2rem. What do you write?",
    hints: ["clamp takes minimum, preferred, and maximum.", "Mixing units in the preferred value is the point."],
    approach: "Explain each function, show the clamp example, and note the calc syntax rule and accessibility caveat.",
    solution:
      "`calc()` does arithmetic across mixed units, for example `calc(100% - 2rem)`. Operators `+` and `-` need spaces around them. `min(a, b)` picks the smaller value, `max(a, b)` the larger, and `clamp(min, preferred, max)` is shorthand for `max(min, min(preferred, max))`. For fluid type: `font-size: clamp(1rem, 0.5rem + 2vw, 2rem)`. The preferred value mixes `rem` and `vw` so the text still responds to the user’s font-size settings. Using only `vw` in the preferred value can break zoom and the WCAG requirement that text can be resized up to 200 percent, because pure viewport units do not grow with browser text zoom. These functions can be nested and used in any length, and also for `width`, `padding`, or `gap`. Test at narrow widths and with zoom.",
    notes: "Mixing rem into the preferred value is the accessibility detail to listen for.",
    correct: "`font-size: clamp(1rem, 0.5rem + 2vw, 2rem)`",
    wrong: [
      "`font-size: clamp(2rem, 1rem + 2vw, 1rem)`",
      "`font-size: calc(1rem + 2vw to 2rem)`",
      "`font-size: min(1rem, 0.5rem + 2vw, 2rem)`",
    ],
  }),
  q({
    topic: "what-is-subgrid",
    title: "What is subgrid?",
    level: "senior",
    tags: ["css", "grid"],
    prompt: "A row of cards each has a title, body, and footer, and you want the footers aligned across cards even when titles wrap. How does subgrid solve it?",
    hints: ["A nested grid normally defines its own tracks.", "Subgrid reuses the parent’s tracks."],
    approach: "Contrast nested grids with subgrid, show how a card spans the parent’s rows, and mention gaps and support.",
    solution:
      "A nested grid creates its own independent tracks, so content inside separate cards cannot line up with each other. With `subgrid`, a grid item that is itself a grid declares `grid-template-rows: subgrid` (and or columns), and it adopts the parent’s track sizing for the lines it spans. Make the parent grid have rows for title, body, and footer, make each card span all three rows with `grid-row: span 3`, and give each card `display: grid; grid-template-rows: subgrid`. All titles share one row, so the tallest title sets the height for every card and the footers align. Gaps can be inherited or overridden. Subgrid works on one axis or both and is supported in current evergreen browsers, so use `@supports (grid-template-rows: subgrid)` where older browsers matter. Before it, people used fixed heights or JavaScript.",
    notes: "Listen for spanning the parent rows and the card-footer alignment example.",
    correct: "The card becomes a grid that adopts the parent’s row tracks, so titles and footers align across cards",
    wrong: [
      "The card gets its own row tracks sized to its content, and the browser then syncs those tracks across cards",
      "The card is removed from the grid so it can use flexbox, which aligns the footers automatically",
      "Subgrid copies the parent’s tracks once at load, so they cannot change when content wraps later",
    ],
  }),
  q({
    topic: "explain-will-change-and-when-not-to-use-it",
    title: "Explain will-change and when not to use it",
    level: "senior",
    tags: ["css", "performance"],
    prompt: "A teammate adds `will-change: transform, opacity` to every card ‘for performance’. What is wrong?",
    hints: ["It asks the browser to allocate resources in advance.", "It can change stacking and containing-block behaviour."],
    approach: "Describe what the hint does, its costs, side effects, and the right usage pattern.",
    solution:
      "`will-change` tells the browser which properties are about to change so it can prepare, typically by promoting the element to its own compositor layer. That removes first-frame cost for an animation, but each layer uses GPU memory and adds compositing work, so applying it to many elements can make the page slower. It also has side effects: `will-change: transform` or `opacity` can create a new stacking context and, for transform-like values, a containing block for `position: fixed` descendants, which can break layouts and overlays. It is a last-resort hint, not an optimisation to sprinkle. Apply it just before the change, for example on `:hover` of a container or from a script when an animation is about to start, and remove it afterwards. Animating `transform` and `opacity` is already compositor-friendly without it. Measure with the Layers panel and the Performance panel before and after.",
    notes: "Good answers name the memory cost and the stacking-context side effect.",
    correct: "It reserves layers and memory per element and can alter stacking and fixed positioning, so apply it only briefly before animating",
    wrong: [
      "It is free and always beneficial, so applying it to every element on the page only improves the frame rate",
      "It forces the animation to run on the main thread instead of the compositor, so keep it to short animations",
      "It permanently caches the element’s rendered pixels, so later style changes are ignored until the page reloads, which is why it is applied to every card",
    ],
  }),
  q({
    topic: "explain-css-layers-layer",
    title: "Explain CSS layers (@layer)",
    level: "senior",
    tags: ["css", "cascade"],
    prompt: "A third-party stylesheet has high-specificity selectors that beat your utilities. How can `@layer` help?",
    hints: ["Layer order is checked before specificity for normal declarations.", "Unlayered styles beat layered ones."],
    approach: "Explain declaring layer order, how it interacts with specificity, unlayered rules, and important.",
    solution:
      "`@layer` lets you declare an explicit cascade order. Write `@layer reset, vendor, components, utilities;` once at the top and later layers beat earlier ones, regardless of selector specificity. Put the third-party CSS in `vendor` with `@import url(lib.css) layer(vendor)` and your `utilities` layer wins even against a selector like `#app .btn.primary`. Styles written outside any layer are treated as the highest-priority layer for normal declarations, so unlayered third-party CSS would beat your layered CSS. Within one layer specificity and source order still apply. For `!important` the layer order is reversed: an important declaration in an earlier layer beats important declarations in later layers and normal ones, which keeps resets from being overridden by accident. Layers solve ordering conflicts in design systems and frameworks, and Tailwind v4 uses them. Nested layers and anonymous layers exist, but keep the order list explicit.",
    notes: "Reversed important order and unlayered-wins are the two details to listen for.",
    correct: "Put the vendor CSS in an earlier layer. Later layers beat it regardless of specificity, while unlayered styles beat layered ones",
    wrong: [
      "Layers raise specificity, so adding @layer to a selector makes it beat any selector that has no layer at all",
      "Earlier layers always beat later layers, so the third-party vendor CSS must be placed in the last declared layer, because each later declaration then replaces it",
      "Layers only affect the order in which stylesheet files are downloaded, with no effect on which declaration wins",
    ],
  }),
  q({
    topic: "what-is-has-selector",
    title: "What is the :has() selector?",
    level: "mid",
    tags: ["css", "selectors"],
    prompt: "How would you style a card differently only when it contains an image, without adding a class in JavaScript?",
    hints: ["It is often called the parent selector.", "It takes a relative selector list."],
    approach: "Show the example, other relational uses, specificity, and performance cautions.",
    solution:
      "`:has()` matches an element if the relative selectors inside it match relative to that element, so `.card:has(img)` selects a card that contains an image. It is more general than a parent selector: `label:has(+ input:invalid)` looks at a following sibling, `form:has(:focus-visible)` styles a form when any control inside has keyboard focus, and `section:not(:has(h2))` finds sections without a heading. Its specificity is that of its most specific argument. It cannot contain pseudo-elements, and an invalid selector inside makes the whole rule invalid (it is not forgiving). Because the browser must re-evaluate when descendants change, avoid very broad subjects such as `:has()` on `body` or `*`, and keep the argument simple. It has been supported in all major browsers since late 2023. Use it for state-driven styling that used to need a JavaScript class toggle.",
    notes: "Check that the candidate knows it is not limited to children and can name a sibling case.",
    correct: "`.card:has(img)`, which matches a card that contains an image",
    wrong: [
      "`.card > img:parent`, which selects the parent of any image directly inside a card",
      "`.card:contains(img)`, which matches a card whose text contains the word img",
      "`.card ~ img`, which matches an image that follows the card as a sibling",
    ],
  }),
  q({
    topic: "what-is-is-and-where",
    title: "What are :is() and :where()?",
    level: "mid",
    tags: ["css", "selectors"],
    prompt: "Both let you write `:is(h1, h2, h3) a` as a shorthand. What is the difference, and when use `:where()`?",
    hints: ["The difference is specificity.", "One of them always contributes zero."],
    approach: "Compare specificity, forgiving parsing, and use cases like resets and library defaults.",
    solution:
      "`:is()` and `:where()` both take a selector list and match if any item matches, which shortens long repeated selectors. They differ in specificity. `:is()` takes the specificity of its most specific argument, while `:where()` always contributes zero. That makes `:where()` ideal for defaults that consumers must be able to override easily, such as a CSS reset or a component library’s base styles: `:where(.btn) { padding: 8px }` loses to any later `.btn` rule. Use `:is()` when you want normal specificity. Both use a forgiving selector list: an invalid or unsupported selector inside is ignored instead of invalidating the whole rule, unlike a plain comma list. Neither accepts pseudo-elements. Beware that `:is(#id, .class)` has the specificity of the id even when only the class matches.",
    notes: "Look for the id-specificity gotcha with :is and the zero-specificity default pattern.",
    correct: ":is takes the highest specificity of its arguments, :where always has zero, so :where suits easily overridden defaults",
    wrong: [
      ":where takes the highest specificity of its arguments and :is always has zero, so :is suits resets, so :is is the better choice for easily overridden defaults",
      "Both always have zero specificity; the only difference is that :where accepts pseudo-elements",
      ":is matches only the first selector in the list and :where matches every selector in the list",
    ],
  }),
  q({
    topic: "what-is-the-difference-between-visibility-and-display",
    title: "What is the difference between visibility and display?",
    level: "beginner",
    tags: ["css", "layout", "a11y"],
    prompt: "What happens to layout and to screen readers with `display: none`, `visibility: hidden`, and `opacity: 0`?",
    hints: ["Two of them hide from assistive technology and one does not.", "Only one frees up the space."],
    approach: "Compare layout space, accessibility tree, interactivity, and animation for each.",
    solution:
      "`display: none` removes the element from layout and from the accessibility tree: it takes no space, cannot be focused, and is not read. `visibility: hidden` keeps the space reserved but hides the element and also removes it from the accessibility tree and tab order, and a descendant can opt back in with `visibility: visible`. `opacity: 0` makes the element transparent but it still occupies space, stays in the accessibility tree, and can still receive focus and clicks, so it is not a way to hide content from users who rely on assistive technology. Transitions: `display` cannot be animated directly (newer `transition-behavior: allow-discrete` helps), `visibility` flips at the end or start of a transition, and `opacity` animates smoothly. For visually hidden but readable text use a screen-reader-only utility rather than any of these.",
    notes: "Candidates often assume opacity: 0 hides from screen readers. It does not.",
    correct: "display:none removes it from layout and the accessibility tree. visibility:hidden keeps space but hides it from both. opacity:0 hides nothing from assistive tech",
    wrong: [
      "display:none keeps the space reserved for the element. visibility:hidden removes it from layout entirely. opacity:0 removes it from the accessibility tree and tab order",
      "All three remove the element from both layout and the accessibility tree, and they differ only in whether the change can be smoothly animated",
      "opacity:0 removes the element from the tab order, while visibility:hidden leaves the element focusable by keyboard and screen reader users",
    ],
  }),

  // ───────── Accessibility ─────────
  q({
    topic: "what-is-wcag-and-pour-principles",
    title: "What is WCAG and the POUR principles?",
    level: "beginner",
    tags: ["a11y", "wcag"],
    prompt: "A reviewer says your site fails ‘Operable’ because modals trap keyboard focus. What does POUR stand for, and where does that fit?",
    hints: ["Four principles organise the guidelines.", "Keyboard access is one of them."],
    approach: "Name the four principles with an example each, and mention levels A, AA, and AAA.",
    solution:
      "WCAG, the Web Content Accessibility Guidelines, are organised under four principles, POUR. Perceivable: users must be able to perceive the content, for example text alternatives for images, captions, and sufficient contrast. Operable: users can operate the interface, for example everything works with a keyboard, no keyboard traps, enough time, and no seizure-inducing flashes. Understandable: content and behaviour are predictable and readable, for example clear error messages, consistent navigation, and a declared page language. Robust: content works with assistive technologies, for example valid markup, correct names, roles, and states. Each guideline has success criteria at level A, AA, or AAA, and most legal requirements target AA. A focus trap with no way out fails an Operable criterion. Accessibility testing combines automated tools, which catch only a portion of issues, with manual keyboard and screen reader checks.",
    notes: "Listen for concrete examples per principle and the AA target.",
    correct: "Perceivable, Operable, Understandable, Robust. A keyboard trap fails Operable",
    wrong: [
      "Performance, Operability, Usability, Reliability. A keyboard trap fails Reliability",
      "Perceivable, Optimised, Understandable, Responsive. A keyboard trap fails Optimised",
      "Planned, Observable, Universal, Reviewed. A keyboard trap fails Observable",
    ],
    refs: wcag,
  }),
  q({
    topic: "what-is-aria-hidden-vs-hidden-attribute",
    title: "What is aria-hidden vs the hidden attribute?",
    level: "mid",
    tags: ["a11y", "aria"],
    prompt: "You add `aria-hidden=\"true\"` to a button to hide it from screen readers. What goes wrong?",
    hints: ["aria-hidden changes only the accessibility tree.", "The element is still visible and focusable."],
    approach: "Contrast `hidden`, `aria-hidden`, and `inert`, and name the focusable-element rule.",
    solution:
      "The HTML `hidden` attribute hides an element from everyone by default because the browser style sheet gives it `display: none`, so it leaves layout, the tab order, and the accessibility tree together. `aria-hidden=\"true\"` only removes the element and its subtree from the accessibility tree. It stays visible and, if focusable, still receives keyboard focus, so a screen reader user can land on a control that is announced as nothing. Never put `aria-hidden=\"true\"` on a focusable element or on a container holding one. Valid uses are decorative icons next to text, or the rest of the page behind an open modal (although `inert` on the background is better, since it also blocks focus and clicks). Use `hidden` or `display: none` to hide for everyone, and a screen-reader-only class to hide visually but keep it announced.",
    notes: "The focusable-element rule is the key. Mention inert for modal backgrounds.",
    correct: "The button is still visible and focusable, so keyboard users can reach a control that assistive technology ignores",
    wrong: [
      "The button disappears for all users, because aria-hidden is a stricter version of the hidden attribute",
      "Nothing; browsers remove aria-hidden elements from the tab order automatically, which is why it is safe to put on buttons and links",
      "The button stays focusable but is announced twice, once by the browser and once by the screen reader",
    ],
    refs: [{ site: "mdn", url: "https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-hidden" }],
  }),
  q({
    topic: "what-is-aria-labelledby-vs-aria-label",
    title: "What is aria-labelledby vs aria-label?",
    level: "mid",
    tags: ["a11y", "aria"],
    prompt: "A dialog has a visible heading ‘Delete project’. Which attribute names the dialog best, and why?",
    hints: ["One points to existing visible text. One supplies a hidden string.", "Name computation has a precedence order."],
    approach: "Explain both, the precedence, and why visible text is preferred.",
    solution:
      "`aria-labelledby` references one or more element IDs and uses their text as the accessible name. `aria-label` supplies a literal string that is not visible. In accessible name computation, `aria-labelledby` takes precedence over `aria-label`, which takes precedence over native sources such as a `<label>` or the element content. For the dialog, `aria-labelledby=\"dlg-title\"` pointing at the visible heading is best: the name always matches what sighted users read (which WCAG’s Label in Name criterion asks for), and it stays in sync and gets translated with the page, whereas an `aria-label` string is easy to forget when copy changes and some translation tools skip attributes. Use `aria-label` when there is no visible text, such as an icon-only button. Neither should be placed on elements with no role that supports naming, such as a plain `div` or `span`.",
    notes: "Precedence and Label in Name are the key points. Icon-only button is the correct aria-label case.",
    correct: "aria-labelledby, because it reuses the visible heading text, wins in name computation, and stays in sync with the page",
    wrong: [
      "aria-label, because it is read before aria-labelledby and always overrides any visible text on the page, so the visible heading is never used in the name",
      "aria-label, because screen readers ignore aria-labelledby on elements that have the role dialog",
      "Neither is needed; a dialog is named automatically from the first paragraph of text inside of it",
    ],
    refs: apg,
  }),
  q({
    topic: "what-is-a-roving-tabindex",
    title: "What is a roving tabindex?",
    level: "senior",
    tags: ["a11y", "keyboard"],
    prompt: "A tab list has ten tabs. Tabbing should enter the list once and arrow keys should move between tabs. How is that built?",
    hints: ["Only one item is in the tab sequence at a time.", "Arrow keys move the zero."],
    approach: "Describe tabindex 0 and -1, the key handler, and the alternative with aria-activedescendant.",
    solution:
      "A roving tabindex keeps a composite widget as a single tab stop. The active item has `tabindex=\"0\"` and every other item has `tabindex=\"-1\"`, so Tab enters the widget on the active item and the next Tab leaves it. A key handler listens for arrow keys (plus Home and End), moves `tabindex=\"0\"` to the new item, sets the previous one back to `-1`, and calls `focus()` on the new item. The widget remembers the last active item so returning with Shift+Tab lands where the user left. This pattern suits tabs, toolbars, radio groups, menus, and grids, and follows the ARIA Authoring Practices keyboard interaction models. The alternative is `aria-activedescendant`, where DOM focus stays on the container and the attribute points at the current item’s ID, which is useful for comboboxes and listboxes where focus must stay in an input. Roving tabindex is simpler to make work across screen readers.",
    notes: "Check that the candidate knows the single tab stop goal and mentions Home and End.",
    correct: "Give the active tab tabindex 0 and the others -1, then move the 0 and focus on arrow keys",
    wrong: [
      "Give every tab tabindex 0 so Tab visits each one, and use arrow keys only for scrolling",
      "Give every tab tabindex -1 and use aria-hidden on the inactive ones to remove them from the tab order",
      "Put tabindex 0 on the container only and let the browser choose which child gets focus",
    ],
    refs: apg,
  }),
  q({
    topic: "explain-live-region-politeness-levels",
    title: "Explain live region politeness levels",
    level: "mid",
    tags: ["a11y", "aria"],
    prompt: "A toast appears after saving, but screen readers say nothing. What do you check about the live region?",
    hints: ["The region should exist before the content changes.", "polite waits and assertive interrupts."],
    approach: "Explain aria-live values, the status and alert roles, and the pitfalls of injected regions.",
    solution:
      "A live region is an element whose changes are announced without moving focus. `aria-live=\"polite\"` queues the announcement until the user is idle, `assertive` interrupts, and `off` is silent. The roles `status` (implicit polite) and `alert` (implicit assertive) are shortcuts. The most common bug is injecting the region and its text together: many screen readers only announce changes to a region that was already in the accessibility tree, so render an empty container on page load and then update its text. `aria-atomic=\"true\"` makes the whole region be read instead of only the changed part. Use polite for confirmations and progress, and reserve assertive or `alert` for errors that need immediate attention, since interrupting is disruptive. Do not put focusable content in a toast that vanishes on a timer, and avoid announcing every keystroke or animation frame.",
    notes: "The pre-existing container rule is the practical insight to listen for.",
    correct: "Render the live region empty before updating it, and use polite for status or assertive only for urgent errors",
    wrong: [
      "Create the live region at the same moment as the message, because screen readers only announce new elements",
      "Use aria-live=\"assertive\" for every message so nothing is delayed or missed, because the assertive level never interrupts the user",
      "Move keyboard focus into the toast, because live regions only work when they hold focus",
    ],
    refs: apg,
  }),
  q({
    topic: "what-is-color-contrast-aa-vs-aaa",
    title: "What is color contrast AA vs AAA?",
    level: "beginner",
    tags: ["a11y", "wcag"],
    prompt: "Your design uses grey 16px body text and a thin grey input border. What contrast ratios does WCAG AA require for each?",
    hints: ["Normal text, large text, and UI components have different thresholds.", "AAA is stricter."],
    approach: "State the ratios for normal text, large text, and non-text components, and the AAA values.",
    solution:
      "WCAG 2 measures contrast as a ratio from 1:1 to 21:1. Level AA requires 4.5:1 for normal text and 3:1 for large text, which means at least 18 pt (24 px) regular or 14 pt (about 18.7 px) bold. Non-text contrast, success criterion 1.4.11, requires 3:1 for user interface components such as input borders and focus indicators, and for graphics needed to understand content. Level AAA raises text to 7:1, or 4.5:1 for large text. So the 16px body text needs 4.5:1 and the input border needs 3:1 against its adjacent colour. Logos and purely decorative text are exempt, and disabled controls are exempt. Check ratios with a tool but also in context: text over images or gradients needs the worst-case area checked. Do not rely on colour alone to convey meaning.",
    notes: "The non-text 3:1 rule is the one candidates often forget.",
    correct: "4.5:1 for the body text and 3:1 for the input border at level AA",
    wrong: [
      "3:1 for the body text and 4.5:1 for the input border at level AA",
      "7:1 for the body text and 4.5:1 for the input border at level AA",
      "4.5:1 for both, since non-text elements have no contrast requirement under WCAG",
    ],
    refs: wcag,
  }),
  q({
    topic: "explain-label-association-with-inputs",
    title: "Explain label association with inputs",
    level: "beginner",
    tags: ["a11y", "forms"],
    prompt: "A form uses placeholder text as the only label. What are the problems, and how do you associate a real label?",
    hints: ["Placeholders disappear and have weak contrast.", "`for` and `id` link a label to a control."],
    approach: "Explain explicit and implicit association, the click-target benefit, and why placeholder is not a label.",
    solution:
      "A `<label>` associates text with a form control so assistive technology announces the name when the control is focused and so clicking the label focuses or toggles the control. Explicit association uses matching attributes, `<label for=\"email\">Email</label><input id=\"email\">`. Implicit association wraps the control inside the label. In React use `htmlFor`. A placeholder is not a label: it disappears when typing, often has low contrast, is not reliably announced as a name, and can be mistaken for a pre-filled value. Placeholders can show an example format as a hint alongside a real label. If a design truly has no visible label, such as a search field with an adjacent button, provide an `aria-label` or visually hidden label. Link hints and errors with `aria-describedby` so they are read after the name. Every input needs exactly one clear accessible name.",
    notes: "Check that the candidate mentions the click target and aria-describedby for hints.",
    correct: "Add a label linked with for and id (or wrap the input). Placeholders vanish and are not reliable names",
    wrong: [
      "Placeholders are enough because browsers announce them as the name and keep them after typing",
      "Add a title attribute only, since it creates a visible label and enlarges the click target",
      "Add `aria-hidden` to the placeholder so screen readers read the label from the field value instead",
    ],
    refs: wcag,
  }),

  // ───────── React ─────────
  q({
    topic: "what-is-strict-mode-double-invoking",
    title: "What is Strict Mode double-invoking?",
    level: "mid",
    tags: ["react", "strict-mode"],
    prompt: "In development your effect logs twice on mount and a component body runs twice. Is this a bug?",
    hints: ["Strict Mode is a development-only check.", "It deliberately mounts, unmounts, and remounts."],
    approach: "List what is double-invoked, why, and what it reveals about impure renders and missing cleanups.",
    solution:
      "No, it is Strict Mode doing its job, and it only happens in development. React double-invokes component bodies, state initialisers, updater functions, and reducers to expose impure code, since a pure function gives the same result when called twice. In React 18 and later it also simulates an unmount and remount of every component after the first mount: effects run, are cleaned up, then run again. That reveals missing cleanup, for example a subscription or timer started without teardown, or a fetch that cannot be cancelled. The fix is not to remove Strict Mode, but to make effects symmetrical: whatever setup does, cleanup undoes. Do not guard with a ref to skip the second run, because that hides the real bug and breaks features such as Offscreen. Production builds run once. If a log twice disturbs you, look at what the effect does, not at how often it runs.",
    notes: "A strong answer rejects the ref-guard hack. Mention impure renders as the other target.",
    correct: "No. Strict Mode double-invokes renders and remounts effects in development to expose impurity and missing cleanup",
    wrong: [
      "Yes; it means the component is rendering in an infinite loop and a dependency array is missing somewhere, so the second render is a bug that should be removed",
      "No; React runs every effect twice in production builds too, so concurrent rendering stays safe for users",
      "Yes; Strict Mode is broken in React 18 and should be disabled in new projects until it is fixed",
    ],
    refs: reactRefs,
  }),
  q({
    topic: "explain-why-index-as-key-is-harmful",
    title: "Explain why index as key is harmful",
    level: "mid",
    tags: ["react", "lists"],
    prompt: "A todo list with text inputs uses `key={index}`. After deleting the first item, the second item’s typed text appears in the wrong row. Why?",
    hints: ["Keys identify items between renders.", "With index keys, identity follows position."],
    approach: "Explain reconciliation by key, the failure on reorder, insert, and delete, and when an index is acceptable.",
    solution:
      "React matches elements between renders by key. With `key={index}`, an item’s identity is its position, so after deleting the first item the old second item gets key 0 and React reuses the old first row’s DOM node and component state for it. State that is not derived from props, such as an uncontrolled input’s typed text or a child’s `useState`, stays with the position and appears on the wrong item. The same issue shows up on insert, sort, and filter, and it also causes unneeded updates and breaks animations and focus. Use a stable, unique ID from the data (a database ID or a generated UUID stored with the item). Index keys are acceptable only when the list is static, never reordered, never filtered, and has no item state. Do not generate keys with `Math.random()` in render, since each render creates a new identity and remounts every row.",
    notes: "Check that Math.random is also called out as a bad key.",
    correct: "Identity follows position, so React reuses the wrong row’s state. Use stable IDs from the data",
    wrong: [
      "React caches rendered output by index, and the cache is not cleared when an item is deleted",
      "Index keys are not unique, so React throws away the whole list and rebuilds it with default state",
      "Index keys make React skip rendering of items that did not change, so new values never appear",
    ],
    refs: reactRefs,
  }),
  q({
    topic: "explain-race-conditions-in-useeffect-fetches",
    title: "Explain race conditions in useEffect fetches",
    level: "mid",
    tags: ["react", "effects", "async"],
    prompt: "A search box fires a fetch on each change inside useEffect and sometimes shows results for an older query. How do you fix it?",
    hints: ["Responses can return out of order.", "The effect cleanup runs before the next effect."],
    approach: "Explain the cause, then show an ignore flag and AbortController cleanup, and mention data libraries.",
    solution:
      "When `query` changes quickly, several requests are in flight and a slow earlier response can arrive after a later one and overwrite state. Effects run again whenever dependencies change, and React runs the previous effect’s cleanup first, so use cleanup to invalidate the old request. The simple version is a flag: `let ignore = false; fetch(...).then(r => { if (!ignore) setData(r) }); return () => { ignore = true }`. A better version aborts the request with `const ctrl = new AbortController(); fetch(url, { signal: ctrl.signal }); return () => ctrl.abort()` and ignores `AbortError`. That also saves bandwidth. Handle the loading and error state per request so a cancelled one does not flash an error. In Strict Mode the effect runs twice, so cleanup must be correct. For anything beyond simple cases prefer a data library such as TanStack Query or SWR, or Suspense and the `use` hook, which handle caching, deduplication, and staleness for you.",
    notes: "The cleanup-based fix is expected. Bonus for AbortController and mention of a data library.",
    correct: "Cancel or ignore the previous request in the effect cleanup, using an ignore flag or AbortController",
    wrong: [
      "Add a setTimeout of one second before each fetch so earlier responses always return first",
      "Remove the dependency array so the effect runs once and cannot overlap with itself",
      "Wrap setState in async/await, which guarantees responses are applied in the order they were sent",
    ],
    refs: reactRefs,
  }),
  q({
    topic: "explain-automatic-batching",
    title: "Explain automatic batching",
    level: "mid",
    tags: ["react", "rendering"],
    prompt: "In a `setTimeout` you call `setCount` and `setFlag`. In React 17 that rendered twice. What changes in React 18?",
    hints: ["React 17 batched only inside React event handlers.", "createRoot enables batching everywhere."],
    approach: "State the old and new behaviour, the opt-out, and the effect on rendering counts.",
    solution:
      "Batching groups several state updates into one re-render. In React 17 it only happened inside React event handlers, so updates in a `setTimeout`, a promise callback, or a native event handler each caused a separate render. React 18, when you use `createRoot`, batches updates automatically regardless of where they originate, so the two calls in the timeout produce one render. Updates are also not applied immediately: reading state right after `setCount` still gives the old value, because the new value is for the next render. Use the updater form `setCount(c => c + 1)` when the next state depends on the previous one. In the rare case where you need the DOM to update synchronously, `flushSync(() => setCount(1))` forces a render for that update. Batching does not merge separate event handler invocations, so each user event still flushes before the next.",
    notes: "Check for the createRoot dependency and flushSync as the opt-out.",
    correct: "With createRoot, updates in timeouts, promises and native handlers are batched into one render. flushSync opts out",
    wrong: [
      "React 18 renders once per setState call everywhere, because batching was removed for performance, so every call in a timeout updates the DOM on its own",
      "Batching still only happens inside React event handlers, and createRoot has no effect on it",
      "Batching makes setState synchronous, so state read right after the call is already updated",
    ],
    refs: reactRefs,
  }),
  q({
    topic: "what-is-usetransition-for-search-uis",
    title: "What is useTransition for search UIs?",
    level: "senior",
    tags: ["react", "concurrent"],
    prompt: "Typing in a search box that filters a large list stutters. How does `useTransition` help, and what does it not do?",
    hints: ["It marks a state update as non-urgent.", "It does not delay or debounce network calls."],
    approach: "Separate urgent and non-urgent updates, explain isPending and interruptibility, and the limits.",
    solution:
      "`const [isPending, startTransition] = useTransition()` lets you mark a state update as a transition. Keep the input value in urgent state so typing stays instant, and set the filter query inside `startTransition(() => setQuery(value))`. React renders the urgent update first, then renders the expensive list in the background, and if the user types again it throws away the stale render and starts over, so the UI never blocks on an outdated result. `isPending` lets you dim the old list while the new one is being prepared. It does not make rendering faster, and it does not debounce or cancel network requests: it controls scheduling of React renders only. The updates inside must be state updates in the same call, not async work after an `await`. For a value received as a prop, `useDeferredValue` is the alternative. Memoise the heavy list so it does not rerender when only the input changes.",
    notes: "The key insight is urgent versus non-urgent and interruption. Not a debounce.",
    correct: "It lets the input stay urgent while the list update renders in the background and can be interrupted. It does not debounce requests",
    wrong: [
      "It debounces the state update by a fixed delay, so the list re-renders only after the user has stopped typing for a moment, just like a debounce does",
      "It moves the list rendering to a Web Worker, so the main thread is never used for the expensive update at all",
      "It cancels in-flight fetch requests automatically whenever the query changes, so stale responses never arrive",
    ],
    refs: reactRefs,
  }),
  q({
    topic: "explain-usedeferredvalue",
    title: "Explain useDeferredValue",
    level: "senior",
    tags: ["react", "concurrent"],
    prompt: "A parent passes a fast-changing `query` prop to a heavy results list. How does `useDeferredValue(query)` differ from debouncing?",
    hints: ["It returns a lagging copy of the value.", "There is no fixed delay."],
    approach: "Describe the two-render behaviour, memoisation requirement, and comparison with debounce.",
    solution:
      "`const deferred = useDeferredValue(query)` returns the previous value during an urgent render, then React schedules a background re-render with the new value. The input updates immediately and the heavy list keeps showing the old deferred value until the new render completes. If `query` changes again before then, the in-progress render is abandoned and restarted. Unlike a debounce there is no fixed delay: on a fast device the deferred value catches up almost immediately, and on a slow one it lags more, and the work is interruptible, whereas a debounce still blocks the main thread once the timer fires. For the pattern to help, the child must be wrapped in `memo` so it skips rendering when only the urgent value changed. Compare `query !== deferred` to show a stale indicator. It does not reduce network requests, so combine it with caching or aborting for fetches. Use `useTransition` when you control the setter and `useDeferredValue` when you only receive the value.",
    notes: "Candidates should say there is no timer and mention memo as the requirement.",
    correct: "It returns a lagging copy re-rendered in the background and interruptible, with no fixed delay. The child should be memoised",
    wrong: [
      "It waits a fixed 300 ms after the last change before updating the value, which makes it work just like a debounce, so it needs a timer in your code",
      "It permanently skips every intermediate value and only ever renders the first and the last value it receives",
      "It memoises the heavy list automatically, so wrapping the child component in memo is never needed with it",
    ],
    refs: reactRefs,
  }),
  q({
    topic: "what-is-the-use-client-boundary",
    title: "What is the 'use client' boundary?",
    level: "senior",
    tags: ["react", "server-components", "nextjs"],
    prompt: "You add `'use client'` to a layout to use one `useState`. What is the impact on the bundle, and how do you limit it?",
    hints: ["The directive marks a module as the entry to the client graph.", "Everything it imports comes along."],
    approach: "Explain the boundary, what crosses it, how to keep it at the leaves, and the children pattern.",
    solution:
      "In the App Router components are Server Components by default. `'use client'` at the top of a module marks it as a boundary: that module and everything it imports become part of the client bundle and are hydrated in the browser. Putting it on a layout therefore ships the layout and all its imported components to the client. Props passed from a server component to a client component must be serialisable (plain data, not functions, class instances, or non-serialisable values), though Server Actions are an exception. To limit the cost, push the boundary down to small leaf components (a button, a dropdown) and keep data fetching and heavy libraries on the server. A client component can still render server content passed as `children` or other props, because those are rendered on the server and slotted in, so a client layout wrapper can contain server pages. Keep secrets out of client modules with `server-only`. The directive is not needed in files imported by an existing client module.",
    notes: "The children-as-slot pattern and leaf-first guidance are the senior points.",
    correct: "It and everything it imports ship to the client. Keep it on small leaves and pass server content in as children",
    wrong: [
      "Only that single file ships to the client; its imports stay on the server and are fetched on demand",
      "It makes the component render only on the server and never hydrate, so it reduces bundle size",
      "It allows passing functions and class instances as props from server components, since they are serialised automatically",
    ],
    refs: nextRefs,
  }),

  // ───────── Performance ─────────
  q({
    topic: "what-is-fcp-vs-lcp",
    title: "What is FCP vs LCP?",
    level: "mid",
    tags: ["performance", "web-vitals"],
    prompt: "Your First Contentful Paint is fast but users say the page feels slow. Which metric captures the main content appearing, and what is a good value?",
    hints: ["FCP fires on the first text or image, even a spinner or header.", "LCP tracks the largest element in the viewport."],
    approach: "Define both, give the Core Web Vitals threshold, and list the common LCP fixes.",
    solution:
      "First Contentful Paint (FCP) is when the browser first renders any content from the DOM, which could be just a header or logo. Largest Contentful Paint (LCP) is when the largest image, video poster, or text block in the viewport finishes rendering, which better approximates when the main content is visible. LCP is a Core Web Vital, with a good threshold of 2.5 seconds or less at the 75th percentile of real users. FCP is a useful diagnostic but not a Core Web Vital. The other vitals are Interaction to Next Paint (INP, good at 200 ms or less) and Cumulative Layout Shift (CLS, good at 0.1 or less). To improve LCP: make the LCP resource discoverable early in the HTML, preload it with high `fetchpriority`, avoid lazy-loading it, reduce server response time and render-blocking CSS and JavaScript, and serve right-sized modern image formats.",
    notes: "Check that LCP is named as the Core Web Vital and the 2.5s threshold. Do not accept ‘LCP is load time’.",
    correct: "LCP measures the largest content element rendering, with a good value of 2.5 seconds or less. FCP only measures the first paint of anything",
    wrong: [
      "FCP measures the largest element and is the Core Web Vital, with a good value of 1 second or less at p75, and LCP is only a lab metric that Lighthouse reports",
      "LCP measures when the page becomes fully interactive, with a good value of 200 ms or less for most users",
      "FCP and LCP are the same metric reported under different names in Lighthouse and the browser’s own tools",
    ],
    refs: webDevRefs,
  }),
  q({
    topic: "what-is-preload-vs-prefetch-vs-preconnect",
    title: "What is preload vs prefetch vs preconnect?",
    level: "mid",
    tags: ["performance", "resource-hints"],
    prompt: "You want the hero image fetched early, the next page’s JavaScript fetched when idle, and the connection to an API origin warmed up. Which hint is each?",
    hints: ["One is for this page, one is for the next navigation, one opens a connection only.", "dns-prefetch is the lighter cousin."],
    approach: "Map each hint to its purpose and priority, and mention misuse costs.",
    solution:
      "`<link rel=\"preload\" as=\"image\" href=\"hero.avif\">` fetches a resource needed for the current page at high priority, so use it for the LCP image, a font, or a late-discovered critical script. `<link rel=\"prefetch\" href=\"next.js\">` fetches a resource likely needed for a future navigation at the lowest priority during idle time, and keeps it in the HTTP cache. `<link rel=\"preconnect\" href=\"https://api.example.com\">` performs the DNS lookup, TCP connection, and TLS handshake early, without fetching anything, so the first real request is faster. `dns-prefetch` does only the DNS step and is a cheap fallback. Misuse hurts: preloading something not used within a few seconds wastes bandwidth and the console warns, fonts need the `crossorigin` attribute even for same-origin, and preconnecting to many origins wastes sockets, so limit it to the two or three that matter. Frameworks such as Next.js add prefetching for visible links.",
    notes: "Look for the fonts-need-crossorigin gotcha and the limit on preconnect.",
    correct: "preload for the hero, prefetch for the next page’s script, preconnect for the API origin",
    wrong: [
      "prefetch for the hero, preconnect for the next page’s script, preload for the API origin",
      "preconnect for the hero, preload for the next page’s script, prefetch for the API origin",
      "preload for all three, since preload handles images, scripts, and connections alike",
    ],
    refs: webDevRefs,
  }),
  q({
    topic: "what-is-bfcache-and-why-unload-breaks-it",
    title: "What is bfcache and why unload breaks it?",
    level: "senior",
    tags: ["performance", "browser"],
    prompt: "Back navigation reloads your page instead of restoring it instantly. A script registers an `unload` handler. Why does that matter?",
    hints: ["bfcache keeps a frozen snapshot of the whole page.", "Some handlers and headers make pages ineligible."],
    approach: "Explain bfcache, the eligibility blockers, the better events, and how to test it.",
    solution:
      "The back/forward cache (bfcache) keeps a complete, frozen snapshot of a page, including its JavaScript heap, when the user navigates away, so pressing Back restores it instantly without a network request. Several things make a page ineligible, historically including any `unload` handler, `Cache-Control: no-store` on the main document, open connections such as WebSockets or IndexedDB transactions, and `window.opener` references. Because `unload` is unreliable (it does not fire on mobile when the page is backgrounded) and blocks bfcache in many browsers, use `pagehide` to send final analytics and `visibilitychange` to detect the user leaving, and use `pageshow` with `event.persisted` to refresh stale data when a page is restored. Browsers are moving to deprecate `unload`. To check eligibility use the Back/forward cache test in Chrome DevTools’ Application panel. Restored pages keep their state, so handle timers and sockets on `pagehide` and `pageshow`.",
    notes: "Listen for pagehide and pageshow persisted. Mention of no-store is a plus.",
    correct: "unload handlers can make the page ineligible for bfcache. Use pagehide and visibilitychange, and pageshow with persisted to refresh",
    wrong: [
      "unload handlers are required for bfcache, because they tell the browser when it is safe to freeze the page, which is why every page should register one",
      "bfcache stores only the HTML and re-runs every script on restore, so unload handlers have no effect on it",
      "bfcache is controlled only by the Cache-Control max-age header that is set on the page’s static assets",
    ],
    refs: webDevRefs,
  }),

  // ───────── Network and APIs ─────────
  q({
    topic: "explain-pagination-offset-vs-cursor",
    title: "Explain pagination: offset vs cursor",
    level: "mid",
    tags: ["api", "pagination"],
    prompt: "A feed uses `?page=5&limit=20`. New posts arrive while users scroll and they see duplicates. What is the cause, and what is the alternative?",
    hints: ["Offset counts rows from the start at the time of the query.", "A cursor points at a specific item."],
    approach: "Compare consistency, performance, and navigation ability of each approach.",
    solution:
      "Offset pagination (`LIMIT 20 OFFSET 80`) asks for rows by position. If new items are inserted at the top between requests, every position shifts and the next page repeats items already seen; deletes cause skipped items. It is also slow at depth, because the database still scans and discards all the earlier rows. Cursor (keyset) pagination asks for items after a specific one: `?after=<opaque cursor>` translates to `WHERE (created_at, id) < (:ts, :id) ORDER BY created_at DESC, id DESC LIMIT 20`, so it is stable under inserts and uses an index for constant-time seeks. The cursor should be opaque to clients and include a unique tie-breaker such as `id`. The cost is that you cannot jump to page 37 or show a total page count cheaply. Use cursors for feeds and infinite scroll, and offset for small, mostly static data where page numbers matter. The response should include the next cursor and a `hasMore` flag.",
    notes: "Check that the candidate mentions the tie-breaker and the loss of random page access.",
    correct: "Offset shifts when items are inserted, causing duplicates. Cursor pagination anchors to an item and is stable and indexable",
    wrong: [
      "Cursor pagination shifts when items are inserted and offset anchors to an item, so offset is better for feeds, because inserted rows are skipped",
      "The duplicates come from caching, and both approaches return identical results once the CDN cache is purged",
      "Offset is always faster at any depth, because the database skips the earlier rows without reading them",
    ],
  }),
  q({
    topic: "explain-cache-control-directives",
    title: "Explain Cache-Control directives",
    level: "mid",
    tags: ["http", "caching"],
    prompt: "Which Cache-Control values would you use for a fingerprinted `app.3f9a.js` and for `index.html`, and what does `no-cache` actually mean?",
    hints: ["no-cache does not mean do not store.", "Fingerprinted files can be cached for a year."],
    approach: "Explain max-age, no-cache, no-store, immutable, public and private, and stale-while-revalidate with the two examples.",
    solution:
      "`max-age=N` lets a cache reuse the response without asking the server for N seconds. `no-cache` allows storing but requires revalidation (a conditional request with `ETag` or `Last-Modified`) before every reuse, so the server can answer 304. `no-store` forbids storing at all and suits sensitive data. `public` allows shared caches such as CDNs, `private` restricts to the user’s browser, and `s-maxage` sets a lifetime only for shared caches. `immutable` tells the browser not to revalidate even on reload. `stale-while-revalidate=N` serves a stale copy while fetching a fresh one in the background. For a fingerprinted asset whose name changes with its content use `public, max-age=31536000, immutable`. For `index.html`, which references those names, use `no-cache` (or a short `max-age` with revalidation) so new deploys are picked up immediately. A response with no directive may be cached heuristically, so set it explicitly.",
    notes: "The no-cache misconception is the usual trap. Check for the immutable asset plus no-cache HTML pattern.",
    correct: "app.3f9a.js: public, max-age=31536000, immutable. index.html: no-cache. no-cache means store but revalidate before reuse",
    wrong: [
      "app.3f9a.js: no-store. index.html: max-age=31536000. no-cache means the response must never be stored anywhere",
      "app.3f9a.js: no-cache. index.html: immutable. no-cache means the response is cached forever without any checks",
      "Both: no-store, since fingerprinted names make caching unnecessary and no-store is always the fastest option",
    ],
  }),
  q({
    topic: "what-is-retry-with-exponential-backoff",
    title: "What is retry with exponential backoff?",
    level: "mid",
    tags: ["api", "resilience"],
    prompt: "A flaky request fails and a client retries immediately in a loop, and the server gets worse. What retry strategy is safer?",
    hints: ["Wait longer after each failure.", "Add randomness so clients do not retry together."],
    approach: "Describe backoff, jitter, caps, which errors to retry, and idempotency.",
    solution:
      "Exponential backoff waits longer after each failed attempt, for example 0.5 s, 1 s, 2 s, 4 s, up to a cap, which gives a struggling server time to recover instead of hammering it. Add jitter, a random fraction of the delay, so thousands of clients that failed together do not all retry in the same instant (a thundering herd). Limit the number of attempts and the total time. Retry only errors that may succeed later: network failures, `502`, `503`, `504`, and `429` (honour a `Retry-After` header if present). Do not retry `400`-class client errors such as `401`, `403`, or `422`. Only retry operations that are safe to repeat: `GET` is fine, but a `POST` that charges a card needs an idempotency key so that a retry cannot double-charge. Show the user progress or a manual retry after the budget is spent, and stop retrying when the tab is hidden or the user navigates away.",
    notes: "Jitter and idempotency are the two points that separate strong answers.",
    correct: "Increase the wait after each failure with jitter and a cap, retrying only transient errors and idempotent requests",
    wrong: [
      "Retry immediately three times, since a short delay always lets the server recover before the next attempt",
      "Double the number of parallel requests after each failure so one of them is likely to succeed",
      "Retry every failed request forever at a fixed one-second interval so no user action is ever lost",
    ],
  }),

  // ───────── Security ─────────
  q({
    topic: "what-is-sanitization-vs-escaping",
    title: "What is sanitization vs escaping?",
    level: "mid",
    tags: ["security", "xss"],
    prompt: "You render a user’s display name and also a rich-text comment that may include bold and links. Which technique does each need?",
    hints: ["Escaping makes data inert for one output context.", "Sanitising removes dangerous parts of markup you intend to render."],
    approach: "Define each, tie them to the two cases, and note context-specific escaping.",
    solution:
      "Escaping converts characters that have meaning in a given output context into harmless text, so `<` becomes `&lt;` and the browser displays the characters instead of parsing a tag. It is context-specific: HTML body, HTML attribute, JavaScript string, URL, and CSS each need different rules, which is why frameworks such as React escape interpolated text by default. Sanitising takes markup that you do intend to render as HTML and strips what is dangerous (scripts, event-handler attributes, `javascript:` URLs) while keeping an allowed subset, usually with a maintained library such as DOMPurify. So the display name needs escaping (render it as text), and the rich comment needs sanitising before use with `dangerouslySetInnerHTML` or `innerHTML`. Prefer escaping by default and sanitise only when you must render user HTML, on a strict allowlist, ideally with a Content Security Policy as a backstop. Do not hand-roll regex sanitisers.",
    notes: "Listen for context-specific escaping and the advice to use a maintained library.",
    correct: "Escape the display name by rendering it as text. Sanitise the rich comment with an allowlist library before inserting it as HTML",
    wrong: [
      "Sanitise the display name and escape the rich comment, since escaping preserves bold and links in HTML",
      "Neither is needed, because a Content Security Policy makes user input safe in every output context",
      "Strip every angle bracket from both values with a regular expression, which handles all injection cases, and works for HTML, URL, and CSS contexts alike",
    ],
    refs: owaspRefs,
  }),
  q({
    topic: "what-is-csp-nonce-vs-hash",
    title: "What is CSP nonce vs hash?",
    level: "senior",
    tags: ["security", "csp"],
    prompt: "You want a strict CSP that blocks injected scripts but still allows your own inline bootstrap script. What are the two options?",
    hints: ["One value changes on every response. One is a digest of the script content.", "unsafe-inline defeats the purpose."],
    approach: "Describe both, when each fits, and how strict-dynamic helps with loaded scripts.",
    solution:
      "A strict CSP avoids `'unsafe-inline'`, which would allow any injected inline script. A nonce is a random, unguessable value generated per response and set in the header (`script-src 'nonce-r4nd0m'`) and on each trusted tag (`<script nonce=\"r4nd0m\">`). It allows dynamic pages, but needs a server or edge step on every request to generate and inject it, and a cached HTML page would reuse one nonce, which breaks the guarantee. A hash allows an exact inline script: `script-src 'sha256-<base64>'` matches only content whose digest equals it, so it fits static pages where the inline code does not change, but any edit needs a new hash. Add `'strict-dynamic'` so scripts loaded by a trusted script are also trusted, without listing hosts. Use report-only mode to find breakages first. Never reuse a nonce across responses, and do not rely on a nonce in a page that a CDN caches.",
    notes: "Look for per-response generation and the caching pitfall.",
    correct: "A per-response random nonce on trusted tags, or a hash of the exact inline script, instead of unsafe-inline",
    wrong: [
      "Add 'unsafe-inline' to script-src, since a nonce is only needed for external scripts, which is the simplest way to keep inline scripts working",
      "Use a fixed nonce stored in the codebase, because a stable value is easier for caches to reuse",
      "Use a hash of the page URL, which the browser compares against every script’s source address",
    ],
    refs: owaspRefs,
  }),
  q({
    topic: "explain-oauth-pkce-for-spas",
    title: "Explain OAuth PKCE for SPAs",
    level: "senior",
    tags: ["security", "oauth"],
    prompt: "A single-page app cannot keep a client secret. How does PKCE protect the authorization code flow?",
    hints: ["The app creates a one-time secret before redirecting.", "Only a hash of it is sent at first."],
    approach: "Walk through the verifier and challenge, the redirect, and the token exchange, and say what attack it stops.",
    solution:
      "A public client such as a SPA cannot protect a client secret, so a stolen authorization code could be exchanged by an attacker. PKCE (Proof Key for Code Exchange, pronounced ‘pixy’) binds the code to the app instance that started the flow. Before redirecting, the app generates a high-entropy random `code_verifier`, keeps it (in memory or session storage), and sends `code_challenge = BASE64URL(SHA256(verifier))` with `code_challenge_method=S256` in the authorize request. The authorization server stores the challenge and returns a code to the redirect URI. When the app exchanges the code at the token endpoint it sends the original `code_verifier`, and the server hashes it and compares with the stored challenge. An attacker who intercepts only the code (for example through a malicious app on the redirect or a leaked URL) cannot redeem it without the verifier. PKCE is now recommended for all clients. Also use the `state` parameter against CSRF, exact redirect URI matching, short-lived tokens with rotation, and avoid the implicit flow.",
    notes: "Check that the candidate can explain verifier versus challenge and name the interception attack.",
    correct: "The app sends a hash of a one-time verifier at authorize time and the verifier at token exchange, so a stolen code is useless alone",
    wrong: [
      "The app stores a long-lived client secret in the bundle, and PKCE encrypts it so users cannot read it there, which is why PKCE never needs a code verifier",
      "The server sends the access token straight to the browser and skips the code step, so nothing can be stolen",
      "The app signs the redirect URI with a private key held in localStorage, which the server then verifies",
    ],
    refs: owaspRefs,
  }),
];
