import type { Question } from "@/lib/types";

export const quizQuestions: Question[] = [
  {
    id: "js-closures",
    track: "quiz",
    level: "mid",
    title: "What is a closure, and when do you use one in UI code?",
    tags: ["javascript", "closures"],
    status: "ready",
    canonicalTopic: "closures",
    prompt:
      "In one or two sentences, define a closure. Then give a concrete frontend example (e.g. event handlers, hooks, or module privacy).",
    hints: [
      "Think about a function that remembers variables from the scope where it was created.",
      "React hooks and event listeners are full of closures.",
    ],
    approach:
      "Define: a function bundled with its lexical environment.\nCall out: private state, partial application, stable callbacks.\nExample: a click handler that increments a counter closed over from outer scope, or useState updater forms.",
    solution:
      "A closure is a function that retains access to variables from its outer lexical scope even after that outer function has returned.\n\nUI example: `function makeClickLogger(label) { return () => console.log(label); }` — each returned handler closes over its `label`. In React, effects and event handlers routinely close over props/state; stale closures are the bug when dependencies are wrong.",
    interviewerNotes:
      "They want precision (lexical scope) plus a practical UI example, and awareness of stale-closure pitfalls.",
    sourceRefs: [
      { site: "toptal-js", url: "https://www.toptal.com/developers/javascript/interview-questions" },
      { site: "gfg", url: "https://www.geeksforgeeks.org/interview-prep/front-end-developer-interview-questions/" },
    ],
    options: [
      { id: "a", label: "A function that runs only once when the page loads" },
      { id: "b", label: "A function that retains access to its outer lexical scope", correct: true },
      { id: "c", label: "A method of forcing garbage collection" },
      { id: "d", label: "A CSS containment strategy" },
    ],
  },
  {
    id: "js-event-loop",
    track: "quiz",
    level: "mid",
    title: "Explain the browser event loop: call stack, microtasks, macrotasks",
    tags: ["javascript", "event-loop"],
    status: "ready",
    canonicalTopic: "event-loop",
    prompt: "Order of execution: what runs before paint? Where do promises vs setTimeout land?",
    hints: ["Microtasks drain before the next macrotask.", "Promise.then is a microtask; setTimeout is a macrotask."],
    approach:
      "Sketch: stack → when empty, run all microtasks → then one macrotask → repeat.\nRelate to UI jank: long tasks block rendering.",
    solution:
      "JS runs on a single call stack. When the stack is clear, the engine empties the microtask queue (Promise jobs, queueMicrotask, MutationObserver) before taking the next macrotask (timers, I/O, UI events). That is why `Promise.resolve().then(fn)` runs before `setTimeout(fn, 0)`. Long sync work on the stack delays both microtasks and paint.",
    interviewerNotes: "Look for microtask vs macrotask distinction and tie-in to responsiveness.",
    sourceRefs: [
      { site: "toptal-js", url: "https://www.toptal.com/developers/javascript/interview-questions" },
    ],
    options: [
      { id: "a", label: "setTimeout always runs before Promise.then" },
      { id: "b", label: "Microtasks run before the next macrotask after the stack clears", correct: true },
      { id: "c", label: "Macrotasks and microtasks are the same queue" },
      { id: "d", label: "requestAnimationFrame is a microtask" },
    ],
  },
  {
    id: "js-this",
    track: "quiz",
    level: "beginner",
    title: "How is `this` determined in JavaScript?",
    tags: ["javascript", "this"],
    status: "ready",
    canonicalTopic: "this-binding",
    prompt: "Compare default, implicit, explicit, and arrow-function binding.",
    hints: ["Arrow functions inherit `this` lexically.", "call/apply/bind set `this` explicitly."],
    approach: "List four binding rules; show why class methods lose `this` when passed as callbacks.",
    solution:
      "`this` is set by how a function is called: default (undefined/global in strict), implicit (obj.method), explicit (call/apply/bind), and `new`. Arrow functions do not have their own `this` — they close over the enclosing scope. That is why you bind handlers or use arrows in React class components historically.",
    interviewerNotes: "Want clear rules + a React/DOM callback example.",
    sourceRefs: [{ site: "gfg", url: "https://www.geeksforgeeks.org/interview-prep/front-end-developer-interview-questions/" }],
    options: [
      { id: "a", label: "`this` is always the global object" },
      { id: "b", label: "`this` depends on call site; arrows use lexical this", correct: true },
      { id: "c", label: "`this` is fixed at function definition for all functions" },
      { id: "d", label: "`this` only exists inside classes" },
    ],
  },
  {
    id: "js-promises",
    track: "quiz",
    level: "beginner",
    title: "Promise states and error handling with async/await",
    tags: ["javascript", "async"],
    status: "ready",
    canonicalTopic: "promises",
    prompt: "What are the three Promise states? How do you avoid unhandled rejections with async/await?",
    hints: ["pending, fulfilled, rejected", "try/catch around await"],
    approach: "Define states; show try/catch; mention Promise.all vs allSettled.",
    solution:
      "A Promise is pending, fulfilled, or rejected (settled once). With async/await, wrap `await` in try/catch (or attach .catch). Prefer `Promise.all` when any failure should fail fast; `allSettled` when you need every result. Unhandled rejections surface as runtime errors and hurt reliability.",
    interviewerNotes: "Basic correctness plus when to use all vs allSettled.",
    sourceRefs: [{ site: "toptal-js", url: "https://www.toptal.com/developers/javascript/interview-questions" }],
    options: [
      { id: "a", label: "Promises have five states including cancelled" },
      { id: "b", label: "pending, fulfilled, rejected — use try/catch with await", correct: true },
      { id: "c", label: "async/await cannot catch Promise errors" },
      { id: "d", label: "rejected Promises automatically retry" },
    ],
  },
  {
    id: "css-box-model",
    track: "quiz",
    level: "beginner",
    title: "Describe the CSS box model and box-sizing",
    tags: ["css", "layout"],
    status: "ready",
    canonicalTopic: "box-model",
    prompt: "What is included in width with content-box vs border-box?",
    hints: ["content-box: width = content only", "border-box: width includes padding + border"],
    approach: "Draw content → padding → border → margin; contrast box-sizing.",
    solution:
      "Every element has content, padding, border, and margin. With `content-box` (default in raw CSS), `width`/`height` size the content box only. With `border-box`, width includes padding and border — usually what you want for UI layouts. Margin is always outside.",
    interviewerNotes: "Expect border-box preference for app CSS.",
    sourceRefs: [
      { site: "greatfrontend", url: "https://www.greatfrontend.com/interviews/gfe75" },
      { site: "gfg", url: "https://www.geeksforgeeks.org/interview-prep/front-end-developer-interview-questions/" },
    ],
    options: [
      { id: "a", label: "border-box width includes margin" },
      { id: "b", label: "border-box width includes content, padding, and border", correct: true },
      { id: "c", label: "padding is outside the border" },
      { id: "d", label: "box-sizing only applies to flex items" },
    ],
  },
  {
    id: "css-specificity",
    track: "quiz",
    level: "mid",
    title: "How does CSS specificity work?",
    tags: ["css"],
    status: "ready",
    canonicalTopic: "specificity",
    prompt: "Rank inline styles, IDs, classes, elements. Where do !important and cascade layers fit?",
    hints: ["Inline > id > class/attr/pseudo-class > elements", "!important is a nuclear option"],
    approach: "Give the (a,b,c,d) mental model; mention @layer and source order.",
    solution:
      "Specificity compares inline styles, then IDs, then classes/attributes/pseudo-classes, then type/pseudo-elements. Equal specificity → later rule wins (cascade). `!important` overrides normal declarations but hurts maintainability. Cascade layers (@layer) let you control priority without specificity wars.",
    interviewerNotes: "Want practical debugging advice, not just the numbers.",
    sourceRefs: [{ site: "gfg", url: "https://www.geeksforgeeks.org/interview-prep/front-end-developer-interview-questions/" }],
    options: [
      { id: "a", label: "Classes always beat IDs" },
      { id: "b", label: "Inline > ID > class > element, then source order", correct: true },
      { id: "c", label: "Only !important matters" },
      { id: "d", label: "Specificity ignores pseudo-classes" },
    ],
  },
  {
    id: "css-flex-grid",
    track: "quiz",
    level: "beginner",
    title: "When do you choose Flexbox vs Grid?",
    tags: ["css", "layout"],
    status: "ready",
    canonicalTopic: "flex-vs-grid",
    prompt: "One-dimensional vs two-dimensional layout — give examples.",
    hints: ["Flex: row/column of items", "Grid: rows and columns together"],
    approach: "Flex for nav bars, toolbars; Grid for page shells and card matrices.",
    solution:
      "Flexbox shines for one-dimensional distribution (nav, button groups, centering). CSS Grid shines when you need both rows and columns (dashboards, magazine layouts). They compose: grid for page structure, flex inside cells.",
    interviewerNotes: "Look for composition mindset, not dogma.",
    sourceRefs: [{ site: "gfg", url: "https://www.geeksforgeeks.org/interview-prep/front-end-developer-interview-questions/" }],
    options: [
      { id: "a", label: "Never use Grid in production" },
      { id: "b", label: "Flex for 1D; Grid when you need 2D tracks", correct: true },
      { id: "c", label: "Flex cannot wrap" },
      { id: "d", label: "Grid cannot nest Flex" },
    ],
  },
  {
    id: "browser-reflow-repaint",
    track: "quiz",
    level: "senior",
    title: "Reflow vs repaint — what triggers each?",
    tags: ["browser", "performance"],
    status: "ready",
    canonicalTopic: "reflow-repaint",
    prompt: "Which style changes cause layout? How do you reduce layout thrashing?",
    hints: ["Geometry changes → reflow", "Color/visibility → often repaint only"],
    approach: "Pipeline: JS → style → layout → paint → composite. Batch reads/writes.",
    solution:
      "Reflow (layout) recalculates geometry when size/position-affecting properties change. Repaint updates pixels without layout. Prefer transforms/opacity for animations (compositor-friendly). Avoid interleaving layout reads (offsetHeight) with writes — batch DOM mutations and use rAF.",
    interviewerNotes: "Senior signal: layout thrashing + compositor properties.",
    sourceRefs: [{ site: "greatfrontend", url: "https://www.greatfrontend.com/interviews/gfe75" }],
    options: [
      { id: "a", label: "Changing color always causes reflow" },
      { id: "b", label: "Geometry changes reflow; color often only repaints", correct: true },
      { id: "c", label: "Repaint is more expensive than reflow always" },
      { id: "d", label: "transform always triggers layout" },
    ],
  },
  {
    id: "react-keys",
    track: "quiz",
    level: "mid",
    title: "Why do React lists need stable keys?",
    tags: ["react"],
    status: "ready",
    canonicalTopic: "react-keys",
    prompt: "What goes wrong with index keys when the list reorders?",
    hints: ["Keys identity reconcile components", "Index keys remount or reuse wrong state"],
    approach: "Reconciliation identity; local state and animations break with unstable keys.",
    solution:
      "Keys tell React which item is which across renders. Stable IDs preserve component state and DOM. Index keys are unsafe when items insert/delete/reorder — state can attach to the wrong row. Prefer business IDs.",
    interviewerNotes: "Classic mid-level React question.",
    sourceRefs: [{ site: "toptal-react", url: "https://www.toptal.com/developers/react/interview-questions" }],
    options: [
      { id: "a", label: "Keys improve CSS specificity" },
      { id: "b", label: "Stable keys preserve identity during reconciliation", correct: true },
      { id: "c", label: "Keys are required only for Fragments" },
      { id: "d", label: "Index keys are always best" },
    ],
  },
  {
    id: "react-hooks-rules",
    track: "quiz",
    level: "mid",
    title: "Rules of Hooks — why do they exist?",
    tags: ["react", "hooks"],
    status: "ready",
    canonicalTopic: "rules-of-hooks",
    prompt: "Why no conditional hooks? What does the hook call order represent?",
    hints: ["Hooks rely on call order", "Conditionals break the linked-list of hook state"],
    approach: "Explain fiber memoized state slots keyed by call order.",
    solution:
      "React associates hook state with call order in a component. Conditional or looped hooks change that order between renders and corrupt state. Always call hooks at the top level of React functions.",
    interviewerNotes: "Want the 'why', not just the lint rule.",
    sourceRefs: [{ site: "toptal-react", url: "https://www.toptal.com/developers/react/interview-questions" }],
    options: [
      { id: "a", label: "Hooks are slower inside conditions so React bans them" },
      { id: "b", label: "Call order maps to hook state slots", correct: true },
      { id: "c", label: "You can call hooks in class methods" },
      { id: "d", label: "Rules only apply in Strict Mode" },
    ],
  },
  {
    id: "react-useeffect",
    track: "quiz",
    level: "mid",
    title: "What belongs in useEffect vs render?",
    tags: ["react", "effects"],
    status: "ready",
    canonicalTopic: "useeffect",
    prompt: "Synchronize with an external system — examples and dependency arrays.",
    hints: ["Effects are for sync after paint", "Derive data during render when possible"],
    approach: "Contrast pure render calculation vs subscriptions/network/DOM.",
    solution:
      "Render should be pure: derive values from props/state. useEffect synchronizes with external systems — network, timers, subscriptions, non-React DOM. Dependency arrays declare reactive inputs; missing deps → stale closures; excess deps → extra runs. Prefer event handlers for user-triggered work when possible.",
    interviewerNotes: "Modern React: fewer effects, more derived state.",
    sourceRefs: [{ site: "toptal-react", url: "https://www.toptal.com/developers/react/interview-questions" }],
    options: [
      { id: "a", label: "Put all data transforms in useEffect" },
      { id: "b", label: "Effects sync with externals; derive pure values in render", correct: true },
      { id: "c", label: "Empty deps means run every render" },
      { id: "d", label: "useEffect runs on the server by default" },
    ],
  },
  {
    id: "react-memo",
    track: "quiz",
    level: "senior",
    title: "When does React.memo / useMemo actually help?",
    tags: ["react", "performance"],
    status: "ready",
    canonicalTopic: "react-memo",
    prompt: "Cost of memoization vs benefit. What must be true about props?",
    hints: ["Referential equality", "Measure before memoizing"],
    approach: "Memo helps when render is expensive and props are stable.",
    solution:
      "memo/useMemo/useCallback help when (1) render or child work is expensive and (2) inputs are referentially stable. Unstable object/array props defeat memo. Prefer fixing state locality and component splits first; profile with React DevTools.",
    interviewerNotes: "Senior: skepticism of blanket memo.",
    sourceRefs: [{ site: "toptal-react", url: "https://www.toptal.com/developers/react/interview-questions" }],
    options: [
      { id: "a", label: "Always wrap every component in React.memo" },
      { id: "b", label: "Memo helps when work is expensive and props stay stable", correct: true },
      { id: "c", label: "useMemo replaces useState" },
      { id: "d", label: "memo forces SSR" },
    ],
  },
  {
    id: "a11y-semantics",
    track: "quiz",
    level: "mid",
    title: "Accessibility: semantics, focus, and ARIA",
    tags: ["a11y"],
    status: "ready",
    canonicalTopic: "accessibility",
    prompt: "When do you use a button vs a div with onClick? What is a focus trap?",
    hints: ["Prefer native elements", "ARIA only when no native"],
    approach: "Keyboard, screen readers, focus management for modals.",
    solution:
      "Use native `<button>`, `<a>`, inputs — they come with keyboard and semantics. ARIA supplements when you build custom widgets; do not override good native roles. Modals need focus trap + Escape + restore focus. Label every control.",
    interviewerNotes: "Practical a11y over buzzwords.",
    sourceRefs: [{ site: "greatfrontend", url: "https://www.greatfrontend.com/interviews/gfe75" }],
    options: [
      { id: "a", label: "div+onClick is fine for all actions" },
      { id: "b", label: "Prefer native interactive elements; ARIA when needed", correct: true },
      { id: "c", label: "ARIA always beats native semantics" },
      { id: "d", label: "Focus management is optional for modals" },
    ],
  },
  {
    id: "web-vitals",
    track: "quiz",
    level: "senior",
    title: "Core Web Vitals: LCP, INP, CLS",
    tags: ["performance", "vitals"],
    status: "ready",
    canonicalTopic: "web-vitals",
    prompt: "Define each metric and one frontend mitigation.",
    hints: ["LCP: largest contentful paint", "INP: interaction latency", "CLS: layout shift"],
    approach: "Map metric → cause → fix (images, long tasks, reserved space).",
    solution:
      "LCP: time to largest content — optimize hero image, fonts, server TTFB, avoid late-loading LCP element.\nINP: responsiveness to interactions — break up long tasks, defer hydration work.\nCLS: visual stability — size attributes, reserve space for ads/embeds, avoid inserting above existing content.",
    interviewerNotes: "Senior FE must connect metrics to concrete fixes.",
    sourceRefs: [{ site: "greatfrontend", url: "https://www.greatfrontend.com/interviews/gfe75" }],
    options: [
      { id: "a", label: "CLS measures time to first byte" },
      { id: "b", label: "LCP paint, INP interactivity, CLS shift stability", correct: true },
      { id: "c", label: "INP replaced only FID on the server" },
      { id: "d", label: "Web Vitals only apply to SPAs" },
    ],
  },
  {
    id: "security-xss",
    track: "quiz",
    level: "mid",
    title: "XSS in frontend apps — vectors and defenses",
    tags: ["security"],
    status: "ready",
    canonicalTopic: "xss",
    prompt: "Stored vs reflected vs DOM XSS. How does React help? Where does it not?",
    hints: ["dangerouslySetInnerHTML", "URL sinks, href javascript:"],
    approach: "Explain escaping defaults; list sinks; CSP as defense in depth.",
    solution:
      "XSS executes attacker script in your origin. React escapes text content by default, but `dangerouslySetInnerHTML`, unsanitized markdown, and some URL/`href` patterns remain sinks. Sanitize HTML, validate URLs, use CSP, HttpOnly cookies for session tokens.",
    interviewerNotes: "Want awareness beyond 'React is safe'.",
    sourceRefs: [{ site: "gfg", url: "https://www.geeksforgeeks.org/interview-prep/front-end-developer-interview-questions/" }],
    options: [
      { id: "a", label: "React makes XSS impossible" },
      { id: "b", label: "Escape by default; watch HTML sinks and URLs", correct: true },
      { id: "c", label: "XSS only happens on the server" },
      { id: "d", label: "CSP replaces input validation entirely" },
    ],
  },
  {
    id: "ts-narrowing",
    track: "quiz",
    level: "mid",
    title: "TypeScript narrowing and discriminated unions",
    tags: ["typescript"],
    status: "ready",
    canonicalTopic: "ts-narrowing",
    prompt: "How do you model API success/error results safely?",
    hints: ["Shared discriminant field like `status`", "switch exhaustiveness"],
    approach: "Show `{type:'ok',data} | {type:'err',error}` pattern.",
    solution:
      "Discriminated unions share a literal tag. TypeScript narrows in switch/if so you access the right fields safely. Prefer this over optional fields everywhere. `satisfies` and exhaustive checks catch missing cases.",
    interviewerNotes: "Common mid/senior TS interview topic.",
    sourceRefs: [{ site: "toptal-js", url: "https://www.toptal.com/developers/javascript/interview-questions" }],
    options: [
      { id: "a", label: "Use any for all API responses" },
      { id: "b", label: "Discriminated unions enable safe narrowing", correct: true },
      { id: "c", label: "TypeScript cannot narrow in switch" },
      { id: "d", label: "Unions require runtime reflection" },
    ],
  },
  {
    id: "http-caching",
    track: "quiz",
    level: "senior",
    title: "HTTP caching for frontend assets and APIs",
    tags: ["networking", "caching"],
    status: "ready",
    canonicalTopic: "http-caching",
    prompt: "Cache-Control, ETag, hashed filenames — how do you ship immutable assets?",
    hints: ["contenthash → long cache", "HTML short cache"],
    approach: "Fingerprinted JS/CSS immutable; HTML revalidates; APIs vary.",
    solution:
      "Build tools emit content-hashed bundles → `Cache-Control: public, max-age=31536000, immutable`. HTML stays short-lived or negotiated so clients discover new hashes. APIs use ETag/If-None-Match or app-level cache (SWR). Service workers add another cache layer — version carefully.",
    interviewerNotes: "Staff+ often ask how deploys stay safe with CDNs.",
    sourceRefs: [{ site: "greatfrontend", url: "https://www.greatfrontend.com/interviews/gfe75" }],
    options: [
      { id: "a", label: "Never cache JavaScript" },
      { id: "b", label: "Hash assets for long cache; keep HTML fresh", correct: true },
      { id: "c", label: "ETag only works for images" },
      { id: "d", label: "immutable means the file can change anytime" },
    ],
  },
  {
    id: "csr-ssr-rsc",
    track: "quiz",
    level: "senior",
    title: "CSR vs SSR vs RSC — trade-offs",
    tags: ["architecture", "react"],
    status: "ready",
    canonicalTopic: "rendering-strategies",
    prompt: "When is client-only rendering wrong? What problem do React Server Components solve?",
    hints: ["SEO/TTFB vs interactivity", "RSC: zero-bundle server composition"],
    approach: "Map product needs to rendering mode; mention hydration cost.",
    solution:
      "CSR ships an empty shell then hydrates — fine for apps behind auth, weaker for content SEO and LCP. SSR/SSG send HTML first for faster first paint/SEO, then hydrate. RSC (in Next etc.) keep heavy data components on the server to shrink client JS. Trade-offs: TTFB, caching, interactivity boundaries, hosting complexity.",
    interviewerNotes: "Senior system-design adjacent.",
    sourceRefs: [{ site: "toptal-react", url: "https://www.toptal.com/developers/react/interview-questions" }],
    options: [
      { id: "a", label: "CSR is always fastest for LCP" },
      { id: "b", label: "Pick CSR/SSR/RSC based on SEO, data, and JS budget", correct: true },
      { id: "c", label: "RSC run only in the browser" },
      { id: "d", label: "SSR eliminates all JavaScript" },
    ],
  },
  {
    id: "staff-design-systems",
    track: "quiz",
    level: "staff",
    title: "What makes a design system succeed across teams?",
    tags: ["design-systems", "platform"],
    status: "ready",
    canonicalTopic: "design-system-governance",
    prompt: "Tokens, components, contribution model, versioning — what fails first?",
    hints: ["Adoption > perfection", "Governance and migration paths"],
    approach: "Talk ownership, RFC process, breaking changes, metrics.",
    solution:
      "A design system is a product: tokens, components, docs, and a contribution/RFC path. Success = adoption and consistency metrics, not component count. Version semver carefully, provide codemods, staff a rotating ownership model, and partner with design. Premature abstraction and no escape hatches kill adoption.",
    interviewerNotes: "Staff/principal: org leverage, not just Button API.",
    sourceRefs: [{ site: "greatfrontend", url: "https://www.greatfrontend.com/questions/system-design" }],
    options: [
      { id: "a", label: "Ship 200 components before docs" },
      { id: "b", label: "Treat it as a product with governance and adoption metrics", correct: true },
      { id: "c", label: "Never allow team-local overrides" },
      { id: "d", label: "Avoid versioning to move faster" },
    ],
  },
  {
    id: "principal-platform",
    track: "quiz",
    level: "principal",
    title: "Frontend platform strategy at org scale",
    tags: ["platform", "strategy"],
    status: "ready",
    canonicalTopic: "fe-platform-strategy",
    prompt: "How do you decide monorepo vs polyrepo, shared CI, and framework standards?",
    hints: ["Optimize for team throughput and risk", "Standards with paved roads"],
    approach: "Paved road, golden paths, migration economics, measurable outcomes.",
    solution:
      "Principal FE platform work sets golden paths (framework, lint, CI, observability) that make the right thing easy. Choose monorepo when shared ownership and atomic changes dominate; polyrepo when team autonomy and release cadence differ. Drive migrations with adoption metrics, dual-running, and executive alignment — not mandates alone.",
    interviewerNotes: "Looking for systems thinking and org impact.",
    sourceRefs: [{ site: "greatfrontend", url: "https://www.greatfrontend.com/questions/system-design" }],
    options: [
      { id: "a", label: "Force one repo overnight with no migration plan" },
      { id: "b", label: "Golden paths + migrations measured by adoption/risk", correct: true },
      { id: "c", label: "Platform teams should avoid docs" },
      { id: "d", label: "Standards never need exceptions" },
    ],
  },
  {
    id: "js-hoisting",
    track: "quiz",
    level: "beginner",
    title: "What is hoisting in JavaScript?",
    tags: ["javascript"],
    status: "ready",
    canonicalTopic: "hoisting",
    prompt: "Explain how `var`, function declarations, and `let`/`const` behave before their line in the source.",
    hints: ["Creation phase vs execution phase", "`let`/`const` are in TDZ until initialized"],
    approach: "Distinguish compile-time binding from runtime initialization. `var` and function declarations get hoisted differently than `let`/`const`.",
    solution:
      "During compilation, bindings are created for all declarations in a scope. `var` is hoisted and initialized as `undefined`. Function declarations are hoisted with their full body. `let` and `const` are hoisted but stay in the temporal dead zone until the declaration line runs — accessing them before that throws.",
    interviewerNotes: "Want TDZ mention, not just 'var is undefined'.",
    sourceRefs: [
      { site: "gfg", url: "https://www.geeksforgeeks.org/interview-prep/front-end-developer-interview-questions/" },
      { site: "toptal-js", url: "https://www.toptal.com/developers/javascript/interview-questions" },
    ],
    options: [
      { id: "a", label: "All declarations run at runtime only where written" },
      { id: "b", label: "Bindings are created early; var/functions differ from let/const TDZ", correct: true },
      { id: "c", label: "Hoisting only applies to CSS" },
      { id: "d", label: "let is hoisted and initialized as undefined like var" },
    ],
  },
  {
    id: "js-prototypes",
    track: "quiz",
    level: "mid",
    title: "Prototypal inheritance vs class syntax",
    tags: ["javascript"],
    status: "ready",
    canonicalTopic: "prototypes",
    prompt: "How does JavaScript inheritance work under the hood? What do classes change?",
    hints: ["Objects delegate to [[Prototype]]", "class is mostly syntactic sugar"],
    approach: "Prototype chain lookup; `Object.create`; class still sets `.prototype`.",
    solution:
      "Objects inherit from other objects via the internal [[Prototype]] link. Property lookup walks the chain. ES6 `class` provides familiar syntax but still uses prototypes — methods live on `Constructor.prototype`. `extends` wires the prototype chain and enables `super`.",
    interviewerNotes: "Classes are not a separate inheritance model in JS.",
    sourceRefs: [{ site: "toptal-js", url: "https://www.toptal.com/developers/javascript/interview-questions" }],
    options: [
      { id: "a", label: "Classes replace prototypes entirely in modern JS" },
      { id: "b", label: "Inheritance is prototype delegation; class is sugar", correct: true },
      { id: "c", label: "Only Java can use inheritance" },
      { id: "d", label: "prototype and __proto__ are unrelated" },
    ],
  },
  {
    id: "js-event-delegation",
    track: "quiz",
    level: "mid",
    title: "What is event delegation?",
    tags: ["dom", "javascript"],
    status: "ready",
    canonicalTopic: "event-delegation",
    prompt: "Why attach one listener on a parent instead of many on children?",
    hints: ["Bubbling phase", "Dynamic lists"],
    approach: "Explain bubbling, `event.target` vs `currentTarget`, memory and dynamic nodes.",
    solution:
      "Events bubble from target to ancestors. A single listener on a stable parent handles clicks on current and future children by inspecting `event.target`. This reduces listener count and keeps dynamic lists simple. Use `closest()` when nested structure matters.",
    interviewerNotes: "Bonus: when to use capture phase.",
    sourceRefs: [{ site: "toptal-js", url: "https://www.toptal.com/developers/javascript/interview-questions" }],
    options: [
      { id: "a", label: "Events never bubble in the DOM" },
      { id: "b", label: "Parent listener + bubbling handles dynamic children", correct: true },
      { id: "c", label: "Delegation disables default actions" },
      { id: "d", label: "Only works with React synthetic events" },
    ],
  },
  {
    id: "js-cors",
    track: "quiz",
    level: "mid",
    title: "Explain CORS and preflight requests",
    tags: ["networking"],
    status: "ready",
    canonicalTopic: "cors",
    prompt: "Why does the browser block some cross-origin fetches? When is OPTIONS sent?",
    hints: ["Same-origin policy", "Simple vs non-simple requests"],
    approach: "Browser enforces; server opts in with headers; preflight for non-simple methods/headers.",
    solution:
      "Browsers restrict cross-origin reads unless the server allows them via `Access-Control-Allow-Origin` (and related headers). Simple GET requests may skip preflight. Non-simple requests (custom headers, PUT, JSON content-type) trigger an OPTIONS preflight. CORS is a browser constraint — servers still need auth.",
    interviewerNotes: "Distinguish CORS from CSRF.",
    sourceRefs: [{ site: "greatfrontend", url: "https://www.greatfrontend.com/interviews/gfe75" }],
    options: [
      { id: "a", label: "CORS is enforced by Node.js on the server only" },
      { id: "b", label: "Browser checks server headers; preflight for non-simple requests", correct: true },
      { id: "c", label: "All cross-origin requests always fail" },
      { id: "d", label: "OPTIONS replaces GET for APIs" },
    ],
  },
  {
    id: "js-web-storage",
    track: "quiz",
    level: "beginner",
    title: "Cookies vs localStorage vs sessionStorage",
    tags: ["browser"],
    status: "ready",
    canonicalTopic: "web-storage",
    prompt: "Compare capacity, lifetime, and whether data is sent on every request.",
    hints: ["HttpOnly cookies", "Tab-scoped sessionStorage"],
    approach: "Cookies: server round-trip, expiry, flags. Web Storage: same-origin, larger, no auto HTTP send.",
    solution:
      "Cookies are small, sent with HTTP requests unless restricted, and can be HttpOnly/Secure/SameSite. localStorage persists until cleared. sessionStorage is per-tab and cleared when the tab closes. Neither storage API sends data automatically — good for client-only prefs, bad for secrets in localStorage.",
    interviewerNotes: "Mention XSS impact on non-HttpOnly storage.",
    sourceRefs: [{ site: "gfg", url: "https://www.geeksforgeeks.org/interview-prep/front-end-developer-interview-questions/" }],
    options: [
      { id: "a", label: "localStorage is sent on every HTTP request" },
      { id: "b", label: "Cookies ride HTTP; web storage stays in the browser", correct: true },
      { id: "c", label: "sessionStorage is shared across all tabs forever" },
      { id: "d", label: "Cookies cannot have expiry" },
    ],
  },
  {
    id: "react-virtual-dom",
    track: "quiz",
    level: "beginner",
    title: "What is the virtual DOM?",
    tags: ["react"],
    status: "ready",
    canonicalTopic: "virtual-dom",
    prompt: "Why does React keep an in-memory representation of the UI?",
    hints: ["Reconciliation", "Batch updates"],
    approach: "Describe render → diff → commit; not always faster than direct DOM but predictable.",
    solution:
      "React renders UI descriptions to a lightweight tree, diffs against the previous tree, and applies minimal DOM updates. This batches work and keeps UI updates declarative. It is a trade-off — not magic performance — but it simplifies state-driven UIs at scale.",
    interviewerNotes: "Modern answer can mention concurrent features and alternatives (signals).",
    sourceRefs: [{ site: "gfg", url: "https://www.geeksforgeeks.org/interview-prep/front-end-developer-interview-questions/" }],
    options: [
      { id: "a", label: "A second physical DOM in the GPU" },
      { id: "b", label: "In-memory UI tree used to compute minimal DOM updates", correct: true },
      { id: "c", label: "Virtual DOM removes the need for JavaScript" },
      { id: "d", label: "Only used during SSR" },
    ],
  },
  {
    id: "js-equality",
    track: "quiz",
    level: "beginner",
    title: "Difference between == and ===",
    tags: ["javascript"],
    status: "ready",
    canonicalTopic: "equality",
    prompt: "When does loose equality coerce types? Why prefer === in app code?",
    hints: ["Abstract equality algorithm", "null == undefined"],
    approach: "Give 1–2 coercion examples; default to === unless you intentionally want coercion.",
    solution:
      "`==` applies type coercion (e.g. `'1' == 1` is true). `===` checks type and value without coercion. Prefer `===` to avoid subtle bugs. Known exception: `x == null` matches both `null` and `undefined` — some codebases allow that idiom.",
    interviewerNotes: "Object.is for NaN edge cases is a plus.",
    sourceRefs: [{ site: "toptal-js", url: "https://www.toptal.com/developers/javascript/interview-questions" }],
    options: [
      { id: "a", label: "They are identical in strict mode only" },
      { id: "b", label: "== coerces types; === does not", correct: true },
      { id: "c", label: "=== coerces strings to numbers" },
      { id: "d", label: "== is always faster so prefer it" },
    ],
  },
  {
    id: "js-async-await",
    track: "quiz",
    level: "beginner",
    title: "How does async/await relate to Promises?",
    tags: ["javascript", "async"],
    status: "ready",
    canonicalTopic: "async-await",
    prompt: "What does `async` return? What happens when you `await` a rejected Promise?",
    hints: ["async functions always return a Promise", "await unwraps or throws"],
    approach: "Syntax over Promises; try/catch; sequential vs parallel with Promise.all.",
    solution:
      "An `async` function always returns a Promise. `await` pauses within the async function until the Promise settles — fulfillment returns the value, rejection throws (catch with try/catch). Parallel work still needs Promise.all rather than awaiting in a loop serially when independence allows.",
    interviewerNotes: "Mention not awaiting fire-and-forget tasks accidentally.",
    sourceRefs: [{ site: "toptal-js", url: "https://www.toptal.com/developers/javascript/interview-questions" }],
    options: [
      { id: "a", label: "async functions return plain values synchronously" },
      { id: "b", label: "async wraps in a Promise; await pauses until settle", correct: true },
      { id: "c", label: "await works only on arrays" },
      { id: "d", label: "async/await replaces the event loop" },
    ],
  },
  {
    id: "html-semantic",
    track: "quiz",
    level: "beginner",
    title: "Why use semantic HTML?",
    tags: ["html", "a11y"],
    status: "ready",
    canonicalTopic: "semantic-html",
    prompt: "What do `<main>`, `<nav>`, `<article>`, and `<button>` give you beyond `<div>`?",
    hints: ["Accessibility tree", "SEO and maintainability"],
    approach: "Roles for assistive tech, keyboard defaults, document outline.",
    solution:
      "Semantic elements expose meaning to browsers, assistive technologies, and readers. Landmarks (`main`, `nav`) aid screen reader navigation. `<button>` is focusable and activates with keyboard by default. Div soup forces ARIA patches and hurts accessibility and SEO.",
    interviewerNotes: "Connect to real component choices in React.",
    sourceRefs: [{ site: "gfg", url: "https://www.geeksforgeeks.org/interview-prep/front-end-developer-interview-questions/" }],
    options: [
      { id: "a", label: "Semantics only affect CSS color" },
      { id: "b", label: "Meaning for a11y, SEO, and default behavior", correct: true },
      { id: "c", label: "div is always better for performance" },
      { id: "d", label: "Semantic tags are deprecated in HTML5" },
    ],
  },
  {
    id: "react-context-api",
    track: "quiz",
    level: "mid",
    title: "When is the Context API enough?",
    tags: ["react", "state"],
    status: "ready",
    canonicalTopic: "context-api",
    prompt: "What problems does Context solve? When does it cause performance issues?",
    hints: ["Prop drilling", "All consumers re-render when value changes"],
    approach: "Good for low-frequency global data (theme, locale); split contexts; not a full Redux replacement.",
    solution:
      "Context shares data across deep trees without prop drilling. It fits theme, auth session, locale — data that changes infrequently. When the context value changes, all consuming components re-render unless memoized carefully. High-frequency updates need colocated state, external stores, or split contexts.",
    interviewerNotes: "Mention composition as alternative to context.",
    sourceRefs: [{ site: "toptal-react", url: "https://www.toptal.com/developers/react/interview-questions" }],
    options: [
      { id: "a", label: "Context replaces all local useState" },
      { id: "b", label: "Good for low-churn global data; watch re-renders", correct: true },
      { id: "c", label: "Context values never trigger re-renders" },
      { id: "d", label: "Context only works in class components" },
    ],
  },
];
