import { carouselGuide, chatGuide, photoGuide, storefrontGuide, editorGuide, analyticsGuide } from "@/content/sd-articles";
import type { Question } from "@/lib/types";

const refs = [{ site: "web-platform", url: "https://web.dev" }];

/** Third authoring wave: curated frontend system-design exercises. */
export const authoredSystemDesignStubs: Question[] = [
  {
    id: "sd-image-carousel", track: "system-design", level: "mid", title: "Design an image carousel", tags: ["widgets", "a11y", "performance"], status: "ready", canonicalTopic: "image-carousel",
    prompt: "Design a reusable, accessible image carousel for a commerce product page. Cover rendering, controls, touch interaction, media delivery, and failure states.",
    hints: ["A carousel should never be the only way to access content.", "Treat the active slide as state; images are delivery concerns."],
    approach: "Establish the content and accessibility contract before animation. Separate the controller, slide viewport, navigation, and responsive image component; then set a performance budget.",
    solution: "Use a `Carousel` controller with an explicit active index, previous/next controls, and an optional thumbnail or numbered slide picker. Render the active slide plus one neighboring slide where preloading is justified; use `img`/`picture` with intrinsic dimensions, responsive `srcset`, lazy loading below the fold, and CDN variants. Buttons need clear labels, keyboard support, visible focus, and disabled/wrapped behavior that matches the product decision. Do not auto-advance by default; if it must auto-advance, provide pause and respect reduced motion. Keep image failures local with an alt-state and do not shift layout while assets arrive.",
    interviewerNotes: "Strong answers question whether a carousel solves a user need and handle focus, swipe, image sizing, and reduced motion without prompting.", sourceRefs: refs,
    systemDesignGuide: carouselGuide,
    radioSteps: {
      requirements: ["Number and type of images; whether video is in scope", "Looping, thumbnails, zoom, auto-advance, and mobile swipe policy", "Keyboard, screen-reader, reduced-motion, and localization requirements", "Image quality and first-product-paint budget"],
      architecture: ["Controlled active-index state and a small imperative API only if parent control is needed", "Slide viewport separated from controls, indicators, thumbnails, and media renderer", "Gesture layer with pointer events; do not make swipe the only navigation", "Error boundary/fallback at the individual media item"],
      data: ["Media item: stable id, alt text, responsive sources, aspect ratio, optional poster/video", "Current index in component state; URL synchronization only when shareable deep links are required", "Prefetch current-adjacent media, not the full gallery by default"],
      interface: ["Native buttons labeled Previous image / Next image and a current-slide announcement", "Visible focus; arrow keys only when the carousel itself has focus", "Reserve aspect ratio to prevent CLS; responsive image sizes and lazy loading", "Disable or wrap controls consistently; pause any motion and honor reduced motion"],
      observability: ["Image load/error rate by CDN rendition and device", "Largest-contentful-paint candidate and layout-shift attribution", "Control and swipe use, abandonment after image errors", "Accessibility regression tests for keyboard and announced state"],
    },
  },
  {
    id: "sd-chat-ui", track: "system-design", level: "senior", title: "Design a chat application UI", tags: ["realtime", "messaging", "offline"], status: "ready", canonicalTopic: "sd-chat-app--design-the-frontend-for",
    prompt: "Design the frontend for a multi-conversation chat application with text, attachments, typing indicators, read receipts, optimistic sending, and intermittent connectivity.",
    hints: ["The server is authoritative, but the composer must feel instant.", "A message timeline is a paginated, ordered data structure—not an unbounded DOM list."],
    approach: "Define delivery and ordering semantics, then separate normalized message data from the virtualized conversation view. Design the connection state and retry path before adding presence polish.",
    solution: "Use a conversation list, a virtualized message timeline, and a composer backed by a message domain store. Fetch an initial window by cursor; pages older messages upward while preserving the reader’s scroll anchor. On send, create a client-generated id and an optimistic message with `sending` status. The server acknowledgement maps that id to the canonical message; failures become explicit retryable states rather than silently disappearing. A websocket (with reconnect, resume cursor, and backoff) delivers new messages, receipts, and typing events; HTTP remains the fallback for history and sends. Treat ordering as server-sequenced, dedupe by stable ids, upload attachments separately, and never let a reconnect overwrite local unsent drafts.",
    interviewerNotes: "Senior signal: scroll anchoring, idempotent optimistic sends, reconnect/replay, and a clear distinction between durable messages and ephemeral typing/presence.", sourceRefs: refs,
    systemDesignGuide: chatGuide,
    radioSteps: {
      requirements: ["One-to-one versus group chats, edit/delete policy, attachment limits", "Expected delivery, ordering, and read-receipt semantics", "Offline draft/send behavior and multi-device expectations", "Accessibility for an updating message log and keyboard-first composition"],
      architecture: ["Conversation shell, virtualized timeline, composer, attachment uploader, presence layer", "Normalized message/conversation store plus server cache for paged history", "Websocket connection manager with exponential backoff, auth refresh, resume cursor", "Optimistic send state machine: draft → uploading → sending → sent / failed"],
      data: ["Stable server message id plus client mutation id for dedupe/acknowledgement", "Cursor history contract and monotonic server sequence/order field", "Separate durable messages from ephemeral typing and presence events", "Attachment metadata and upload-session state kept independent of message text"],
      interface: ["Maintain scroll position when prepending history; only auto-scroll if reader is at the tail", "Announce new messages appropriately without interrupting composition", "Retry, cancel, and clear failure states; preserve draft after reconnect", "Virtualize long timelines and render media placeholders with fixed dimensions"],
      observability: ["Send-to-ack latency, failed-send/retry rate, duplicate-event rate", "Socket connect/reconnect duration and dropped-event recovery", "Timeline render time, memory use, scroll jank, and attachment failures", "Unread-count and read-receipt consistency diagnostics"],
    },
  },
  {
    id: "sd-photo-share", track: "system-design", level: "senior", title: "Design a photo sharing app UI", tags: ["media", "feed", "uploads"], status: "ready", canonicalTopic: "sd-photo-sharing--design-the-frontend-for",
    prompt: "Design a photo-sharing web app with a personalized feed, uploads, captions, likes, comments, profile grids, and responsive media.",
    hints: ["Media uploads and feed reads have very different lifecycles.", "The feed must remain usable when one asset or mutation fails."],
    approach: "Split the system into feed delivery, media upload, and interaction mutations. Use cursor pagination and responsive media, then cover privacy and failure recovery.",
    solution: "Render the initial feed server-side where it improves first contentful value, then use a cursor-based client cache for subsequent pages. Each post carries stable ids, author summary, media variants, caption, and aggregate interaction state. The uploader creates a local preview, requests a short-lived direct-upload session, reports progress, and creates the post only after media processing succeeds; failed uploads remain recoverable drafts. Use responsive image variants and intrinsic dimensions, virtualize only when measurements show a need, and defer below-the-fold media. Likes can be optimistic with rollback; comments need idempotency keys, local pending state, pagination, and moderation/error states. Privacy checks belong in API/media authorization, not only hidden client controls.",
    interviewerNotes: "Listen for direct-to-object-storage uploads, media dimensions to avoid CLS, and optimistic interactions that can be reconciled after reconnect.", sourceRefs: refs,
    systemDesignGuide: photoGuide,
    radioSteps: {
      requirements: ["Feed ordering and freshness, private/public account rules, and media formats", "Upload size, processing time, drafts, retry, editing, and moderation flows", "Comment volume and notification expectations", "Mobile network, data-saver, and accessibility requirements"],
      architecture: ["Route-level feed/profile shells; post card and media renderer as isolated units", "Server cache for paginated feed; normalized post mutations for likes/comments", "Direct upload session to storage/CDN with client preview and processing status", "Per-post error boundaries so one broken asset does not collapse the feed"],
      data: ["Cursor feed contract with post ids, author snapshot, media rendition metadata, and engagement counts", "Upload state separate from published post state; idempotency key on post creation", "Optimistic mutation version or mutation id for conflict/retry reconciliation", "Profile grid pagination keyed separately from home feed"],
      interface: ["Intrinsic media ratio and responsive `srcset`; lazy-load below fold", "Accessible image alt text/caption, labeled like/comment controls, and keyboard-safe dialogs", "Upload progress, processing, retry, cancellation, and failed-draft affordances", "Load-more fallback in addition to intersection-triggered pagination"],
      observability: ["Upload completion, processing failure, and time-to-publish", "Feed LCP/INP/CLS segmented by media type and connection", "Mutation rollback and comment-post failure rate", "CDN media errors, cache hit rate, and moderation queue latency"],
    },
  },
  {
    id: "sd-ecommerce-storefront", track: "system-design", level: "senior", title: "Design an e-commerce storefront", tags: ["commerce", "performance", "checkout"], status: "ready", canonicalTopic: "ecommerce-storefront",
    prompt: "Design a resilient storefront for browse, search, product detail, cart, and checkout. Focus on the frontend boundary with pricing, inventory, and payment systems.",
    hints: ["Product discovery can be cached aggressively; price, inventory, and checkout require fresher truth.", "A cart is an intent record, not a final order."],
    approach: "Draw the customer path and its consistency needs. Then split static catalog delivery from cart/checkout mutation flows, preserving an explicit order state machine.",
    solution: "Server-render/cache category and product pages close to the user, with structured product data, responsive images, and progressive enhancement for filters. Treat price, promotion eligibility, shipping, and stock as server-authoritative at add-to-cart and checkout; the UI can show an optimistic cart but must reconcile a pricing or inventory change visibly. Persist an anonymous cart with a server-side cart id, merge it carefully on sign-in, and use idempotency keys for checkout creation. The checkout route should keep payment fields in the payment provider’s hosted/secure elements, survive refresh with a resumable order token, and expose a clear state machine: cart, review, payment pending, confirmed, failed/retry. Never declare an order complete from a client redirect alone.",
    interviewerNotes: "A complete answer distinguishes cacheable browsing from transactional truth, and treats payment confirmation as an asynchronous server-verified outcome.", sourceRefs: refs,
    systemDesignGuide: storefrontGuide,
    radioSteps: {
      requirements: ["Catalog/search/filter scope, regions/currencies/tax, and logged-out cart behavior", "Inventory reservation and price/promotion freshness expectations", "Checkout payment methods, 3DS/redirect flows, and order confirmation semantics", "SEO, accessibility, performance, and degraded-network requirements"],
      architecture: ["Cached route shell for browse/PDP; client islands only for interactive controls", "Cart domain API with server cart id and merge-on-auth policy", "Checkout orchestration route isolated from catalog UI; payment provider secure fields", "Feature flags and error boundaries around search, recommendations, and payments"],
      data: ["Catalog snapshot/version for browse; authoritative quote on cart/checkout operations", "Cart lines with product/variant ids, quantity, pricing timestamp, and validation results", "Idempotency key for order/payment intent creation and resumable checkout token", "Explicit order status from the server, not inferred from browser navigation"],
      interface: ["Fast category/PDP skeletons with image aspect ratio and filter URL state", "Clearly surface price, stock, shipping, and promotion changes during reconciliation", "Keyboard-accessible cart drawer and form errors tied to fields", "Checkout recovery after refresh, redirect, timeout, and payment failure"],
      observability: ["Product-page LCP and search/filter INP", "Add-to-cart, checkout-start, payment-success, and confirmation funnel drop-off", "Price/inventory reconciliation and payment error reasons", "Cart merge conflicts, order idempotency collisions, and client/server status mismatch"],
    },
  },
  {
    id: "sd-rich-text-editor", track: "system-design", level: "staff", title: "Design a collaborative rich text editor", tags: ["collab", "realtime", "editor"], status: "ready", canonicalTopic: "sd-docs-collaborative-editor--design-the-frontend-for",
    prompt: "Design a collaborative rich-text editor with presence, cursors, offline edits, comments, version history, and reliable recovery from concurrent changes.",
    hints: ["The hard problem is converging document operations, not rendering a toolbar.", "Presence is ephemeral; document operations are durable."],
    approach: "Start by defining the document model and concurrency algorithm boundary. Then discuss editor abstraction, operation transport, local persistence, and a recovery strategy.",
    solution: "Choose a mature editor core with a structured document model and use an operational-transform or CRDT collaboration layer rather than inventing merge logic in UI components. The client applies local operations immediately, persists an offline queue, and sends operations with document version/vector metadata. The collaboration service acknowledges, rebases/transforms, broadcasts canonical operations, and periodically compacts snapshots; clients can resync from a snapshot if they detect a gap. Presence, selections, and cursors travel as rate-limited ephemeral events and should never block document saves. Comments anchor to stable document positions/ranges with a strategy for movement as text changes. Keep autosave state visible, provide conflict/recovery messaging, and store version history server-side with permissions and audit events.",
    interviewerNotes: "At staff level, name the collaboration abstraction, its operational ownership, offline/recovery behavior, and why presence cannot share the same reliability assumptions as edits.", sourceRefs: refs,
    systemDesignGuide: editorGuide,
    radioSteps: {
      requirements: ["Document schema, formatting/embed support, permissions, comments, and audit/history needs", "Concurrent-edit semantics, offline duration, expected document size, and collaborator count", "Presence/cursor freshness versus durable-save guarantees", "Accessibility of editor, toolbar, comments, and keyboard shortcuts"],
      architecture: ["Structured editor core plus OT/CRDT collaboration adapter—not bespoke DOM diffing", "Document session manager, local operation queue, websocket transport, snapshot/resync path", "Ephemeral presence channel separated from durable operation stream", "Server ownership for authorization, canonical history, compaction, and export"],
      data: ["Versioned document snapshot plus ordered operations/vector metadata", "Client operation id for idempotency and acknowledgement", "Anchored comments with author, permission, resolution, and range-rebase strategy", "Local encrypted/persistent draft queue policy and retention rules"],
      interface: ["Immediate local edits with clear synchronizing/offline/error status", "Remote cursors and selections throttled to avoid rendering churn", "Keyboard-first formatting and accessible semantic output/export", "Recovery UI for resync, permission changes, unsupported content, and version restore"],
      observability: ["Operation latency, rebase/conflict/resync frequency, queue depth, and dropped socket events", "Document render/selection latency and memory cost on large documents", "Autosave durability and offline recovery success rate", "Permission denials, history restore events, and collaboration session health"],
    },
  },
  {
    id: "sd-analytics-dashboard", track: "system-design", level: "staff", title: "Design an analytics dashboard", tags: ["data-viz", "performance", "permissions"], status: "ready", canonicalTopic: "sd-analytics-dashboard--design-the-frontend-for",
    prompt: "Design a multi-tenant analytics dashboard with saved filters, time-series charts, drill-down tables, export, role-based access, and data that refreshes at different cadences.",
    hints: ["Chart pixels are not the data model.", "Each query must be reproducible from explicit filter and time-zone state."],
    approach: "Define the query contract and freshness tiers first. Then isolate chart rendering, cache keys, URL/saved-view state, permissions, and progressive loading for expensive panels.",
    solution: "Model the dashboard as a queryable view: tenant, metric, dimensions, filter predicates, time range, comparison range, timezone, and granularity form a canonical query key. Keep shareable filter state in the URL and named views server-side, while panels independently request or stream their data through a server cache/BFF that enforces tenant and role policy. Render high-value summary metrics first, defer expensive drill-down tables and lower-priority charts, and request pre-aggregated/bucketed data rather than raw events. Use chart components with stable dimensions, accessible tables or summaries, sensible empty/loading/error states, and a download job for large exports. Make freshness explicit per panel—last updated, manual refresh, and stale data state—rather than implying all numbers are real time.",
    interviewerNotes: "Staff-level depth means query identity, authorization on every data path, panel isolation, aggregation strategy, and an accessible non-chart representation.", sourceRefs: refs,
    systemDesignGuide: analyticsGuide,
    radioSteps: {
      requirements: ["Tenant roles, metric definitions, timezone/currency, and data-retention rules", "Realtime versus scheduled freshness per metric and acceptable staleness", "Saved views, sharing/export, drill-down, and maximum result-set expectations", "Accessibility, print/download, and responsive layout needs"],
      architecture: ["Dashboard shell with independently loaded panel boundaries and query-state provider", "BFF/server cache enforces auth, shapes data, batches requests, and hides warehouse details", "Chart/table components consume typed panel results; export runs as an async job", "Feature flags and performance budgets for expensive visualization types"],
      data: ["Canonical query key: tenant, metric, dimensions, filters, range, timezone, granularity", "Panel result includes data version/freshness timestamp, units, formatting metadata, and permissions", "URL state for shareable filters; server-saved view for durable named configurations", "Cursor/page contract for drill-down tables and job id for exports"],
      interface: ["Render summary KPIs first; skeleton and independent error/retry per panel", "Accessible table/summary alternative for every chart and non-color-only encodings", "Clear last-updated/stale state, timezone, comparison range, and query loading status", "Virtualize large tables, debounce filter input, and preserve URL state across reloads"],
      observability: ["Per-panel query latency, cache hit rate, timeout, and stale-data rate", "Dashboard LCP/INP, chart render duration, long-task and memory signals", "Export queue duration/failure, query cardinality, and rate-limit events", "Authorization denials, tenant-isolation checks, and metric-definition/version usage"],
    },
  },
];
