/**
 * Generate a large curated catalog of frontend interview topic titles.
 * Titles + source attribution only — no third-party article bodies.
 *
 * Usage: npx tsx scripts/generate-bulk-catalog.ts
 */
import fs from "node:fs";
import path from "node:path";

type Level = "beginner" | "mid" | "senior" | "staff" | "principal";
type Track = "quiz" | "dsa" | "system-design" | "behaviour" | "negotiation";

type Entry = {
  id: string;
  track: Track;
  level: Level;
  canonicalTopic: string;
  title: string;
  status: "stub";
  tags: string[];
  sourceRefs: { site: string; url: string }[];
};

const SOURCES = {
  gfg: {
    site: "gfg",
    url: "https://www.geeksforgeeks.org/interview-prep/front-end-developer-interview-questions/",
  },
  toptalJs: {
    site: "toptal-js",
    url: "https://www.toptal.com/developers/javascript/interview-questions",
  },
  toptalReact: {
    site: "toptal-react",
    url: "https://www.toptal.com/developers/react/interview-questions",
  },
  gfe75: {
    site: "greatfrontend",
    url: "https://www.greatfrontend.com/interviews/gfe75",
  },
  gfeSd: {
    site: "greatfrontend",
    url: "https://www.greatfrontend.com/questions/system-design",
  },
  blind75: {
    site: "blind75",
    url: "https://www.techinterviewhandbook.org/grind75",
  },
  tihBeh: {
    site: "tech-interview-handbook",
    url: "https://www.techinterviewhandbook.org/behavioral-interview/",
  },
  helloNeg: {
    site: "hellointerview",
    url: "https://www.hellointerview.com/learn/salary-negotiation/introduction",
  },
} as const;

function slugify(input: string) {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 72);
}

function entry(
  track: Track,
  level: Level,
  title: string,
  tags: string[],
  refs: (keyof typeof SOURCES)[],
  topic?: string,
): Entry {
  const canonicalTopic = topic ?? slugify(title);
  return {
    id: `bulk-${track}-${canonicalTopic}`,
    track,
    level,
    canonicalTopic,
    title,
    status: "stub",
    tags,
    sourceRefs: refs.map((k) => SOURCES[k]),
  };
}

function main() {
  const out: Entry[] = [];
  const seen = new Set<string>();

  function add(e: Entry) {
    const key = `${e.track}:${e.canonicalTopic}`;
    if (seen.has(key)) return;
    seen.add(key);
    out.push(e);
  }

  // --- Quiz: JavaScript ---
  const jsTopics: [string, Level, string[]][] = [
    ["Explain scope chain and lexical environment", "beginner", ["javascript"]],
    ["What is the difference between var, let, and const?", "beginner", ["javascript"]],
    ["Explain temporal dead zone", "mid", ["javascript"]],
    ["What are IIFEs and why were they used?", "beginner", ["javascript"]],
    ["Explain call, apply, and bind", "mid", ["javascript"]],
    ["What is the difference between arrow functions and function declarations?", "beginner", ["javascript"]],
    ["Explain rest and spread operators", "beginner", ["javascript"]],
    ["What are default parameters?", "beginner", ["javascript"]],
    ["Explain destructuring assignment", "beginner", ["javascript"]],
    ["What is a Symbol and when do you use it?", "mid", ["javascript"]],
    ["Explain Map vs Object vs WeakMap", "mid", ["javascript"]],
    ["Explain Set vs Array vs WeakSet", "mid", ["javascript"]],
    ["What are generators and iterators?", "senior", ["javascript"]],
    ["Explain Proxy and Reflect", "senior", ["javascript"]],
    ["What is Object.freeze vs Object.seal?", "mid", ["javascript"]],
    ["Explain property descriptors", "senior", ["javascript"]],
    ["What is the difference between null and undefined?", "beginner", ["javascript"]],
    ["Explain NaN and Number.isNaN", "beginner", ["javascript"]],
    ["What is type coercion in JavaScript?", "beginner", ["javascript"]],
    ["Explain truthy and falsy values", "beginner", ["javascript"]],
    ["What is optional chaining?", "beginner", ["javascript"]],
    ["Explain nullish coalescing", "beginner", ["javascript"]],
    ["What are tagged template literals?", "mid", ["javascript"]],
    ["Explain modules: ESM vs CommonJS", "mid", ["javascript"]],
    ["What is tree shaking?", "mid", ["javascript", "tooling"]],
    ["Explain dynamic import()", "mid", ["javascript"]],
    ["What is the difference between for...of and for...in?", "beginner", ["javascript"]],
    ["Explain Array methods: map, filter, reduce", "beginner", ["javascript"]],
    ["What does Array.prototype.sort mutate?", "beginner", ["javascript"]],
    ["Explain flatMap", "mid", ["javascript"]],
    ["What is structuredClone?", "mid", ["javascript"]],
    ["Explain AbortController", "mid", ["javascript", "networking"]],
    ["What is queueMicrotask?", "mid", ["javascript"]],
    ["Explain requestAnimationFrame", "mid", ["javascript", "performance"]],
    ["What is requestIdleCallback?", "senior", ["javascript", "performance"]],
    ["Explain Web Workers", "senior", ["javascript"]],
    ["What is SharedArrayBuffer and Atomics?", "staff", ["javascript"]],
    ["Explain Service Workers basics", "senior", ["javascript", "pwa"]],
    ["What is the Fetch API vs XMLHttpRequest?", "beginner", ["javascript", "networking"]],
    ["Explain ReadableStream and streaming responses", "senior", ["javascript", "networking"]],
    ["What are BigInt numbers?", "mid", ["javascript"]],
    ["Explain Intl APIs for formatting", "mid", ["javascript", "i18n"]],
    ["What is Temporal (stage proposal awareness)?", "senior", ["javascript"]],
    ["Explain error types: TypeError, ReferenceError, RangeError", "beginner", ["javascript"]],
    ["What is a custom Error subclass?", "mid", ["javascript"]],
    ["Explain try/catch/finally and throw", "beginner", ["javascript"]],
    ["What is the difference between stack and heap in JS?", "mid", ["javascript"]],
    ["Explain garbage collection basics in V8", "senior", ["javascript"]],
    ["What are memory leaks in SPAs?", "senior", ["javascript", "performance"]],
    ["Explain function currying vs partial application", "mid", ["javascript"]],
    ["What is a higher-order function?", "beginner", ["javascript"]],
    ["Explain immutability patterns in JS", "mid", ["javascript"]],
    ["What is Object.assign vs spread?", "beginner", ["javascript"]],
    ["Explain ArrayBuffer and TypedArrays", "senior", ["javascript"]],
    ["What is Blob vs File?", "mid", ["javascript"]],
    ["Explain URL and URLSearchParams", "beginner", ["javascript"]],
    ["What is the History API?", "mid", ["javascript", "browser"]],
    ["Explain IntersectionObserver", "mid", ["javascript", "browser"]],
    ["What is MutationObserver?", "mid", ["javascript", "browser"]],
    ["Explain ResizeObserver", "mid", ["javascript", "browser"]],
    ["What is PerformanceObserver?", "senior", ["javascript", "performance"]],
    ["Explain Content Visibility CSS + JS interplay", "senior", ["javascript", "css"]],
    ["What is the difference between sync and async scripts?", "beginner", ["javascript", "browser"]],
    ["Explain defer vs async attributes", "beginner", ["javascript", "browser"]],
    ["What is document.readyState?", "beginner", ["javascript", "dom"]],
    ["Explain event capturing vs bubbling", "beginner", ["javascript", "dom"]],
    ["What is stopPropagation vs preventDefault?", "beginner", ["javascript", "dom"]],
    ["Explain passive event listeners", "mid", ["javascript", "performance"]],
    ["What is pointer events vs mouse events?", "mid", ["javascript", "dom"]],
    ["Explain drag and drop API", "mid", ["javascript", "dom"]],
    ["What is the Clipboard API?", "mid", ["javascript", "browser"]],
    ["Explain Notification API permissions", "mid", ["javascript", "browser"]],
    ["What is IndexedDB vs localStorage?", "mid", ["javascript", "browser"]],
    ["Explain Cache API for offline", "senior", ["javascript", "pwa"]],
    ["What is WebSocket vs SSE?", "senior", ["javascript", "networking"]],
    ["Explain WebRTC at a high level for FE", "staff", ["javascript", "realtime"]],
    ["What is the difference between cookie SameSite values?", "mid", ["javascript", "security"]],
    ["Explain HttpOnly and Secure cookie flags", "mid", ["javascript", "security"]],
    ["What is JWT storage risk on the frontend?", "mid", ["javascript", "security"]],
    ["Explain postMessage and origin checks", "senior", ["javascript", "security"]],
    ["What is iframe sandbox attribute?", "senior", ["javascript", "security"]],
    ["Explain Subresource Integrity (SRI)", "mid", ["javascript", "security"]],
    ["What is Trusted Types?", "staff", ["javascript", "security"]],
    ["Explain feature detection vs browser sniffing", "beginner", ["javascript", "browser"]],
    ["What is polyfill vs transpile?", "mid", ["javascript", "tooling"]],
    ["Explain Babel presets vs plugins", "mid", ["javascript", "tooling"]],
    ["What is TypeScript structural typing?", "mid", ["typescript"]],
    ["Explain unknown vs any", "beginner", ["typescript"]],
    ["What are generics in TypeScript?", "mid", ["typescript"]],
    ["Explain utility types: Partial, Pick, Omit, Record", "mid", ["typescript"]],
    ["What is satisfies operator?", "mid", ["typescript"]],
    ["Explain const assertions", "mid", ["typescript"]],
    ["What are conditional types?", "senior", ["typescript"]],
    ["Explain mapped types", "senior", ["typescript"]],
    ["What is declaration merging?", "senior", ["typescript"]],
    ["Explain module augmentation", "senior", ["typescript"]],
    ["What is type vs interface?", "beginner", ["typescript"]],
    ["Explain enum pitfalls in TypeScript", "mid", ["typescript"]],
    ["What is zod or runtime validation with TS?", "mid", ["typescript"]],
    ["Explain branded types", "senior", ["typescript"]],
    ["What is the difference between void and never?", "mid", ["typescript"]],
  ];

  for (const [title, level, tags] of jsTopics) {
    add(entry("quiz", level, title, tags, ["toptalJs", "gfg", "gfe75"]));
  }

  // --- Quiz: CSS ---
  const cssTopics: [string, Level][] = [
    ["Explain the cascade origin and importance", "mid"],
    ["What is CSS inheritance?", "beginner"],
    ["Explain rem vs em vs px", "beginner"],
    ["What are CSS custom properties (variables)?", "beginner"],
    ["Explain calc() and min/max/clamp", "beginner"],
    ["What is container queries?", "senior"],
    ["Explain media queries best practices", "beginner"],
    ["What is mobile-first CSS?", "beginner"],
    ["Explain position: relative, absolute, fixed, sticky", "beginner"],
    ["What is z-index stacking context?", "mid"],
    ["Explain overflow and scroll containment", "mid"],
    ["What is aspect-ratio property?", "beginner"],
    ["Explain object-fit and object-position", "beginner"],
    ["What is CSS Grid auto-fit vs auto-fill?", "mid"],
    ["Explain fr units in Grid", "beginner"],
    ["What is subgrid?", "senior"],
    ["Explain flex-grow, flex-shrink, flex-basis", "beginner"],
    ["What is gap in Flexbox and Grid?", "beginner"],
    ["Explain CSS transitions vs animations", "beginner"],
    ["What is @keyframes?", "beginner"],
    ["Explain will-change and when not to use it", "senior"],
    ["What is contain and content-visibility?", "senior"],
    ["Explain CSS layers (@layer)", "senior"],
    ["What is :has() selector?", "mid"],
    ["Explain :focus-visible vs :focus", "mid"],
    ["What is :is() and :where()?", "mid"],
    ["Explain logical properties (inline/block)", "mid"],
    ["What is writing-mode and internationalization CSS?", "senior"],
    ["Explain CSS Modules", "mid"],
    ["What is CSS-in-JS trade-offs?", "senior"],
    ["Explain Tailwind utility-first approach", "mid"],
    ["What is PostCSS?", "mid"],
    ["Explain critical CSS extraction", "senior"],
    ["What is FOUC and how do you prevent it?", "mid"],
    ["Explain font-display strategies", "mid"],
    ["What is variable fonts?", "mid"],
    ["Explain CSS nesting", "mid"],
    ["What is color-mix and relative colors?", "senior"],
    ["Explain OKLCH color spaces", "senior"],
    ["What is prefers-color-scheme?", "beginner"],
    ["Explain print stylesheets", "mid"],
    ["What is scroll-snap?", "mid"],
    ["Explain overscroll-behavior", "mid"],
    ["What is backdrop-filter?", "mid"],
    ["Explain mask and clip-path", "senior"],
    ["What is SVG vs icon fonts?", "mid"],
    ["Explain CSS filters vs SVG filters", "mid"],
    ["What is the difference between visibility and display?", "beginner"],
    ["Explain opacity and compositing", "mid"],
    ["What is currentColor?", "beginner"],
  ];

  for (const [title, level] of cssTopics) {
    add(entry("quiz", level, title, ["css"], ["gfg", "gfe75"]));
  }

  // --- Quiz: React ---
  const reactTopics: [string, Level][] = [
    ["Explain React reconciliation", "mid"],
    ["What is a pure component?", "beginner"],
    ["Explain controlled components in depth", "beginner"],
    ["What is lifting state up?", "beginner"],
    ["Explain composition vs inheritance in React", "mid"],
    ["What are render props?", "mid"],
    ["Explain higher-order components", "mid"],
    ["What is useLayoutEffect vs useEffect?", "mid"],
    ["Explain useRef use cases", "beginner"],
    ["What is useImperativeHandle?", "senior"],
    ["Explain useReducer patterns", "mid"],
    ["What is useId for?", "mid"],
    ["Explain useDeferredValue", "senior"],
    ["What is useSyncExternalStore?", "senior"],
    ["Explain Suspense for data fetching", "senior"],
    ["What are Error Boundaries?", "mid"],
    ["Explain React portals for modals", "mid"],
    ["What is Strict Mode double-invoking?", "mid"],
    ["Explain key remounting tricks and risks", "mid"],
    ["What is forwardRef?", "mid"],
    ["Explain children as a function", "mid"],
    ["What is React.lazy and code splitting?", "mid"],
    ["Explain server components data fetching patterns", "senior"],
    ["What is the 'use client' boundary?", "senior"],
    ["Explain streaming SSR with Suspense", "senior"],
    ["What is partial prerendering?", "staff"],
    ["Explain React Query / TanStack Query caching", "mid"],
    ["What is SWR stale-while-revalidate?", "mid"],
    ["Explain optimistic updates in React", "mid"],
    ["What is form library trade-offs (RHF vs Formik)?", "mid"],
    ["Explain Zustand vs Redux Toolkit", "mid"],
    ["What is Jotai / Recoil mental model?", "senior"],
    ["Explain derived state anti-patterns", "mid"],
    ["What is prop drilling and alternatives?", "beginner"],
    ["Explain compound components pattern", "senior"],
    ["What is headless UI?", "mid"],
    ["Explain testing React with Testing Library philosophy", "mid"],
    ["What is MSW for API mocking?", "mid"],
    ["Explain snapshot testing pitfalls", "mid"],
    ["What is React DevTools Profiler?", "mid"],
    ["Explain why index as key is harmful", "beginner"],
    ["What is flushing updates in React 18?", "senior"],
    ["Explain automatic batching", "mid"],
    ["What is useTransition for search UIs?", "senior"],
    ["Explain race conditions in useEffect fetches", "mid"],
    ["What is cleanup in useEffect?", "beginner"],
    ["Explain dependency array exhaustive-deps", "mid"],
    ["What is React Compiler awareness?", "staff"],
    ["Explain Next.js App Router layouts", "mid"],
    ["What is Next.js route handlers?", "mid"],
    ["Explain Next.js middleware", "senior"],
    ["What is ISR and on-demand revalidation?", "senior"],
    ["Explain edge runtime constraints", "staff"],
  ];

  for (const [title, level] of reactTopics) {
    add(entry("quiz", level, title, ["react"], ["toptalReact", "gfe75"]));
  }

  // Expand quiz with systematic HTML / a11y / perf / networking / security / tooling prompts
  const quizBanks: { tag: string; level: Level; titles: string[]; refs: (keyof typeof SOURCES)[] }[] = [
    {
      tag: "html",
      level: "beginner",
      refs: ["gfg", "gfe75"],
      titles: [
        "What is the difference between <section> and <div>?",
        "Explain <header>, <footer>, <aside> landmarks",
        "What is the document outline?",
        "Explain forms: GET vs POST",
        "What are input types useful for mobile keyboards?",
        "Explain label association with inputs",
        "What is autocomplete attribute?",
        "Explain novalidate and constraint validation API",
        "What is the difference between button types?",
        "Explain meta viewport tag",
        "What is Open Graph meta for sharing?",
        "Explain canonical URLs",
        "What is preload vs prefetch vs preconnect?",
        "Explain img srcset and sizes",
        "What is the picture element?",
        "Explain lazy loading images native attribute",
        "What is decoding=async on images?",
        "Explain iframe security concerns",
        "What is the dialog element?",
        "Explain details/summary disclosure",
      ],
    },
    {
      tag: "a11y",
      level: "mid",
      refs: ["gfe75", "gfg"],
      titles: [
        "What is WCAG and POUR principles?",
        "Explain accessibility tree",
        "What is role=button risks vs native button?",
        "Explain skip links",
        "What is aria-expanded?",
        "Explain aria-controls and aria-owns",
        "What is aria-hidden vs hidden attribute?",
        "Explain screen reader only CSS patterns",
        "What is color contrast AA vs AAA?",
        "Explain focus order vs visual order",
        "What is a roving tabindex?",
        "Explain accessible name computation",
        "What is aria-labelledby vs aria-label?",
        "Explain live region politeness levels",
        "What is reduced motion testing?",
        "Explain keyboard traps and how to avoid them",
        "What is accessible drag and drop alternatives?",
        "Explain form error announcement patterns",
        "What is landmark navigation?",
        "Explain heading hierarchy rules",
      ],
    },
    {
      tag: "performance",
      level: "senior",
      refs: ["gfe75"],
      titles: [
        "Explain TTFB and how FE influences it",
        "What is FCP vs LCP?",
        "Explain TTI and why it was replaced in focus",
        "What is Total Blocking Time?",
        "Explain long tasks and scheduler.yield",
        "What is code splitting strategy?",
        "Explain route-based vs component-based splitting",
        "What is bundle analysis with source maps?",
        "Explain tree-shaking failures with sideEffects",
        "What is hydration cost?",
        "Explain islands architecture",
        "What is resumability (Qwik-style awareness)?",
        "Explain image CDNs and transforms",
        "What is AVIF vs WebP?",
        "Explain font subsetting",
        "What is preloading LCP image?",
        "Explain third-party script budgets",
        "What is facade pattern for embeds?",
        "Explain caching service worker strategies",
        "What is bfcache and why unload breaks it?",
      ],
    },
    {
      tag: "networking",
      level: "mid",
      refs: ["gfe75", "gfg"],
      titles: [
        "Explain HTTP/1.1 vs HTTP/2 vs HTTP/3 for FE",
        "What is multiplexing?",
        "Explain header compression (HPACK/QPACK) impact",
        "What is REST idempotency?",
        "Explain GraphQL overfetching/underfetching",
        "What is gRPC-web?",
        "Explain WebSocket reconnection strategies",
        "What is heartbeat/ping for realtime?",
        "Explain pagination: offset vs cursor",
        "What is ETag and If-None-Match?",
        "Explain Cache-Control directives",
        "What is Vary header?",
        "Explain CORS credentials mode",
        "What is preflight caching?",
        "Explain rate limiting UX",
        "What is retry with exponential backoff?",
        "Explain idempotency keys for POSTs",
        "What is request deduplication?",
        "Explain BFF pattern for frontends",
        "What is API versioning strategies?",
      ],
    },
    {
      tag: "security",
      level: "senior",
      refs: ["gfg", "gfe75"],
      titles: [
        "Explain XSS reflected vs stored vs DOM",
        "What is sanitization vs escaping?",
        "Explain DOMPurify role",
        "What is CSP nonce vs hash?",
        "Explain clickjacking and X-Frame-Options",
        "What is CSRF token pattern?",
        "Explain SameSite=Lax vs Strict vs None",
        "What is open redirect vulnerability?",
        "Explain dependency supply chain risks",
        "What is lockfile integrity?",
        "Explain prototype pollution awareness",
        "What is postMessage XSS?",
        "Explain secret leakage in frontend bundles",
        "What is safe Markdown rendering?",
        "Explain OAuth PKCE for SPAs",
        "What is token refresh rotation?",
        "Explain session fixation basics",
        "What is mixed content?",
        "Explain Subresource Integrity failures",
        "What is permission policy headers?",
      ],
    },
    {
      tag: "tooling",
      level: "mid",
      refs: ["gfg", "gfe75"],
      titles: [
        "Explain webpack vs Vite mental model",
        "What is esbuild?",
        "Explain Rollup for libraries",
        "What is package.json exports field?",
        "Explain dual ESM/CJS packages pitfalls",
        "What is peerDependencies?",
        "Explain monorepo tools: pnpm workspaces, nx, turborepo",
        "What is changesets for versioning?",
        "Explain ESLint flat config",
        "What is Prettier vs ESLint responsibilities?",
        "Explain husky and lint-staged",
        "What is CI caching strategies?",
        "Explain Dockerizing a Next.js app basics",
        "What is environment variable exposure in Next.js?",
        "Explain source maps in production trade-offs",
        "What is feature flags tooling?",
        "Explain Storybook for design systems",
        "What is Chromatic / visual regression?",
        "Explain Playwright vs Cypress",
        "What is component testing vs E2E?",
      ],
    },
  ];

  for (const bank of quizBanks) {
    for (const title of bank.titles) {
      add(entry("quiz", bank.level, title, [bank.tag], bank.refs));
    }
  }

  // Systematic quiz expansions via topic × angle templates (still real interview angles)
  const quizSubjects: { subject: string; tag: string; level: Level; refs: (keyof typeof SOURCES)[] }[] = [
    { subject: "closures", tag: "javascript", level: "mid", refs: ["toptalJs", "gfe75"] },
    { subject: "promises", tag: "javascript", level: "mid", refs: ["toptalJs"] },
    { subject: "event loop", tag: "javascript", level: "mid", refs: ["toptalJs", "gfe75"] },
    { subject: "this binding", tag: "javascript", level: "mid", refs: ["toptalJs"] },
    { subject: "prototypes", tag: "javascript", level: "mid", refs: ["toptalJs"] },
    { subject: "modules", tag: "javascript", level: "mid", refs: ["gfg"] },
    { subject: "async/await", tag: "javascript", level: "beginner", refs: ["toptalJs"] },
    { subject: "TypeScript generics", tag: "typescript", level: "mid", refs: ["toptalJs"] },
    { subject: "React hooks", tag: "react", level: "mid", refs: ["toptalReact"] },
    { subject: "React context", tag: "react", level: "mid", refs: ["toptalReact"] },
    { subject: "React suspense", tag: "react", level: "senior", refs: ["toptalReact"] },
    { subject: "virtual DOM", tag: "react", level: "beginner", refs: ["gfg"] },
    { subject: "SSR hydration", tag: "react", level: "senior", refs: ["toptalReact"] },
    { subject: "Next.js routing", tag: "react", level: "mid", refs: ["gfe75"] },
    { subject: "CSS Grid", tag: "css", level: "beginner", refs: ["gfg"] },
    { subject: "Flexbox", tag: "css", level: "beginner", refs: ["gfg"] },
    { subject: "specificity", tag: "css", level: "mid", refs: ["gfg"] },
    { subject: "stacking context", tag: "css", level: "mid", refs: ["gfe75"] },
    { subject: "responsive design", tag: "css", level: "beginner", refs: ["gfg"] },
    { subject: "CSS animations", tag: "css", level: "mid", refs: ["gfe75"] },
    { subject: "accessibility", tag: "a11y", level: "mid", refs: ["gfe75"] },
    { subject: "ARIA", tag: "a11y", level: "mid", refs: ["gfe75"] },
    { subject: "keyboard navigation", tag: "a11y", level: "mid", refs: ["gfe75"] },
    { subject: "Core Web Vitals", tag: "performance", level: "senior", refs: ["gfe75"] },
    { subject: "LCP optimization", tag: "performance", level: "senior", refs: ["gfe75"] },
    { subject: "INP optimization", tag: "performance", level: "senior", refs: ["gfe75"] },
    { subject: "CLS prevention", tag: "performance", level: "senior", refs: ["gfe75"] },
    { subject: "bundle size", tag: "performance", level: "mid", refs: ["gfe75"] },
    { subject: "CORS", tag: "networking", level: "mid", refs: ["gfe75"] },
    { subject: "HTTP caching", tag: "networking", level: "senior", refs: ["gfe75"] },
    { subject: "REST APIs", tag: "networking", level: "mid", refs: ["gfg"] },
    { subject: "GraphQL clients", tag: "networking", level: "mid", refs: ["gfe75"] },
    { subject: "XSS", tag: "security", level: "mid", refs: ["gfg"] },
    { subject: "CSRF", tag: "security", level: "mid", refs: ["gfg"] },
    { subject: "CSP", tag: "security", level: "senior", refs: ["gfe75"] },
    { subject: "OAuth in SPAs", tag: "security", level: "senior", refs: ["gfe75"] },
    { subject: "design tokens", tag: "design-systems", level: "senior", refs: ["gfeSd"] },
    { subject: "component APIs", tag: "design-systems", level: "senior", refs: ["gfeSd"] },
    { subject: "theming", tag: "design-systems", level: "mid", refs: ["gfeSd"] },
    { subject: "monorepos", tag: "architecture", level: "staff", refs: ["gfeSd"] },
    { subject: "microfrontends", tag: "architecture", level: "staff", refs: ["gfeSd"] },
    { subject: "feature flags", tag: "architecture", level: "senior", refs: ["gfeSd"] },
    { subject: "observability", tag: "architecture", level: "senior", refs: ["gfeSd"] },
    { subject: "testing strategy", tag: "testing", level: "mid", refs: ["gfe75"] },
    { subject: "E2E testing", tag: "testing", level: "mid", refs: ["gfe75"] },
    { subject: "visual regression", tag: "testing", level: "senior", refs: ["gfeSd"] },
    { subject: "state management", tag: "react", level: "mid", refs: ["toptalReact"] },
    { subject: "forms in React", tag: "react", level: "mid", refs: ["toptalReact"] },
    { subject: "React performance", tag: "react", level: "senior", refs: ["toptalReact"] },
    { subject: "browser storage", tag: "browser", level: "beginner", refs: ["gfg"] },
    { subject: "service workers", tag: "pwa", level: "senior", refs: ["gfe75"] },
    { subject: "PWA installability", tag: "pwa", level: "mid", refs: ["gfe75"] },
    { subject: "SEO for SPAs", tag: "seo", level: "senior", refs: ["gfe75"] },
    { subject: "i18n routing", tag: "i18n", level: "senior", refs: ["gfe75"] },
    { subject: "date/time handling", tag: "javascript", level: "mid", refs: ["toptalJs"] },
    { subject: "debounce/throttle", tag: "javascript", level: "mid", refs: ["gfe75"] },
    { subject: "immutability", tag: "javascript", level: "mid", refs: ["toptalJs"] },
    { subject: "functional programming in JS", tag: "javascript", level: "mid", refs: ["toptalJs"] },
    { subject: "Web Components", tag: "browser", level: "senior", refs: ["gfe75"] },
    { subject: "Shadow DOM", tag: "browser", level: "senior", refs: ["gfe75"] },
    { subject: "custom elements", tag: "browser", level: "senior", refs: ["gfe75"] },
    { subject: "CSS architecture (BEM)", tag: "css", level: "mid", refs: ["gfg"] },
    { subject: "CSS-in-JS runtime cost", tag: "css", level: "senior", refs: ["gfe75"] },
    { subject: "Tailwind @apply discipline", tag: "css", level: "mid", refs: ["gfe75"] },
    { subject: "design system versioning", tag: "design-systems", level: "staff", refs: ["gfeSd"] },
    { subject: "RFC process for FE", tag: "architecture", level: "staff", refs: ["gfeSd"] },
    { subject: "CI for frontend", tag: "tooling", level: "mid", refs: ["gfg"] },
    { subject: "module federation", tag: "architecture", level: "staff", refs: ["gfeSd"] },
    { subject: "edge rendering", tag: "architecture", level: "staff", refs: ["gfeSd"] },
    { subject: "CDN caching for SPAs", tag: "networking", level: "senior", refs: ["gfe75"] },
    { subject: "cookie auth vs bearer tokens", tag: "security", level: "senior", refs: ["gfe75"] },
    { subject: "content security policy reports", tag: "security", level: "staff", refs: ["gfe75"] },
    { subject: "accessibility audits in CI", tag: "a11y", level: "senior", refs: ["gfe75"] },
    { subject: "prefers-reduced-motion", tag: "a11y", level: "mid", refs: ["gfe75"] },
    { subject: "focus management in SPAs", tag: "a11y", level: "senior", refs: ["gfe75"] },
    { subject: "React Server Components boundaries", tag: "react", level: "senior", refs: ["toptalReact"] },
    { subject: "client-side routing", tag: "react", level: "mid", refs: ["toptalReact"] },
    { subject: "code splitting in React", tag: "react", level: "mid", refs: ["toptalReact"] },
    { subject: "error boundaries", tag: "react", level: "mid", refs: ["toptalReact"] },
    { subject: "concurrent rendering", tag: "react", level: "senior", refs: ["toptalReact"] },
    { subject: "useEffect mental model", tag: "react", level: "mid", refs: ["toptalReact"] },
    { subject: "refs and DOM measurement", tag: "react", level: "mid", refs: ["toptalReact"] },
    { subject: "controlled vs uncontrolled inputs", tag: "react", level: "beginner", refs: ["toptalReact"] },
    { subject: "keys in lists", tag: "react", level: "beginner", refs: ["toptalReact"] },
    { subject: "memoization in React", tag: "react", level: "senior", refs: ["toptalReact"] },
  ];

  const quizAngles = [
    "Explain",
    "Compare approaches to",
    "Common pitfalls with",
    "Interview answer for",
    "Trade-offs around",
    "Debug a production issue involving",
    "How would you teach",
    "Metrics to watch for",
    "Testing strategy for",
    "Senior-level take on",
    "When not to use",
    "Minimal example of",
    "Performance impact of",
    "Accessibility angle on",
    "Security considerations for",
    "Migration plan involving",
    "Design review questions about",
    "Staff-level ownership of",
    "Principal strategy for",
    "Documenting standards for",
  ];

  for (const s of quizSubjects) {
    for (const angle of quizAngles) {
      const title = `${angle} ${s.subject}`;
      add(
        entry(
          "quiz",
          s.level,
          title,
          [s.tag],
          s.refs,
          `${slugify(s.subject)}--${slugify(angle)}`,
        ),
      );
    }
  }

  // --- DSA classic problems (public names) ---
  const dsaProblems: [string, Level, string][] = [
    ["Two Sum II", "beginner", "arrays"],
    ["Valid Palindrome", "beginner", "strings"],
    ["Longest Common Prefix", "beginner", "strings"],
    ["Roman to Integer", "beginner", "strings"],
    ["Integer to Roman", "mid", "strings"],
    ["Longest Substring Without Repeating Characters", "mid", "sliding-window"],
    ["Longest Repeating Character Replacement", "mid", "sliding-window"],
    ["Permutation in String", "mid", "sliding-window"],
    ["Minimum Window Substring", "senior", "sliding-window"],
    ["Sliding Window Maximum", "senior", "sliding-window"],
    ["Best Time to Buy and Sell Stock II", "mid", "arrays"],
    ["Best Time to Buy and Sell Stock with Cooldown", "senior", "dp"],
    ["Maximum Product Subarray", "mid", "arrays"],
    ["Find Minimum in Rotated Sorted Array", "mid", "binary-search"],
    ["Search in Rotated Sorted Array", "mid", "binary-search"],
    ["Binary Search", "beginner", "binary-search"],
    ["Search a 2D Matrix", "mid", "binary-search"],
    ["Koko Eating Bananas", "mid", "binary-search"],
    ["Time Based Key-Value Store", "mid", "binary-search"],
    ["Median of Two Sorted Arrays", "senior", "binary-search"],
    ["3Sum Closest", "mid", "two-pointers"],
    ["4Sum", "mid", "two-pointers"],
    ["Trapping Rain Water", "senior", "two-pointers"],
    ["Move Zeroes", "beginner", "two-pointers"],
    ["Remove Duplicates from Sorted Array", "beginner", "two-pointers"],
    ["Two Sum Sorted", "beginner", "two-pointers"],
    ["Valid Mountain Array", "beginner", "arrays"],
    ["Rotate Array", "mid", "arrays"],
    ["Product of Array Except Self Follow-up O(1) space", "mid", "arrays"],
    ["Spiral Matrix", "mid", "arrays"],
    ["Set Matrix Zeroes", "mid", "arrays"],
    ["Game of Life", "senior", "arrays"],
    ["Insert Interval", "mid", "intervals"],
    ["Non-overlapping Intervals", "mid", "intervals"],
    ["Meeting Rooms", "beginner", "intervals"],
    ["Meeting Rooms II", "mid", "intervals"],
    ["Min Stack", "mid", "stack"],
    ["Evaluate Reverse Polish Notation", "mid", "stack"],
    ["Generate Parentheses", "mid", "stack"],
    ["Daily Temperatures", "mid", "stack"],
    ["Car Fleet", "mid", "stack"],
    ["Largest Rectangle in Histogram", "senior", "stack"],
    ["Asteroid Collision", "mid", "stack"],
    ["Decode String", "mid", "stack"],
    ["Basic Calculator", "senior", "stack"],
    ["Implement Queue using Stacks", "mid", "stack"],
    ["Implement Stack using Queues", "mid", "queue"],
    ["Design Circular Queue", "mid", "queue"],
    ["Number of Recent Calls", "beginner", "queue"],
    ["Sliding Window Median", "senior", "heap"],
    ["Kth Largest Element in an Array", "mid", "heap"],
    ["Top K Frequent Elements", "mid", "heap"],
    ["Find Median from Data Stream", "senior", "heap"],
    ["Task Scheduler", "mid", "heap"],
    ["Design Twitter", "senior", "heap"],
    ["Merge K Sorted Lists", "senior", "heap"],
    ["K Closest Points to Origin", "mid", "heap"],
    ["Last Stone Weight", "beginner", "heap"],
    ["Reorganize String", "mid", "heap"],
    ["Reverse Linked List", "beginner", "linked-list"],
    ["Merge Two Sorted Lists", "beginner", "linked-list"],
    ["Reorder List", "mid", "linked-list"],
    ["Remove Nth Node From End", "mid", "linked-list"],
    ["Copy List with Random Pointer", "mid", "linked-list"],
    ["Add Two Numbers", "mid", "linked-list"],
    ["Find the Duplicate Number", "mid", "linked-list"],
    ["LRU Cache", "senior", "linked-list"],
    ["LFU Cache", "senior", "linked-list"],
    ["Reverse Nodes in k-Group", "senior", "linked-list"],
    ["Maximum Depth of Binary Tree", "beginner", "trees"],
    ["Same Tree", "beginner", "trees"],
    ["Subtree of Another Tree", "beginner", "trees"],
    ["Lowest Common Ancestor of BST", "mid", "trees"],
    ["Lowest Common Ancestor of Binary Tree", "mid", "trees"],
    ["Binary Tree Right Side View", "mid", "trees"],
    ["Count Good Nodes in Binary Tree", "mid", "trees"],
    ["Validate Binary Search Tree", "mid", "trees"],
    ["Kth Smallest Element in a BST", "mid", "trees"],
    ["Construct Binary Tree from Preorder and Inorder", "senior", "trees"],
    ["Binary Tree Maximum Path Sum", "senior", "trees"],
    ["Serialize and Deserialize Binary Tree", "senior", "trees"],
    ["Diameter of Binary Tree", "mid", "trees"],
    ["Balanced Binary Tree", "beginner", "trees"],
    ["Path Sum", "beginner", "trees"],
    ["Path Sum II", "mid", "trees"],
    ["Flatten Binary Tree to Linked List", "mid", "trees"],
    ["Populating Next Right Pointers", "mid", "trees"],
    ["Word Search", "mid", "backtracking"],
    ["Word Search II", "senior", "backtracking"],
    ["Combination Sum", "mid", "backtracking"],
    ["Combination Sum II", "mid", "backtracking"],
    ["Permutations", "mid", "backtracking"],
    ["Permutations II", "mid", "backtracking"],
    ["Subsets", "mid", "backtracking"],
    ["Subsets II", "mid", "backtracking"],
    ["N-Queens", "senior", "backtracking"],
    ["Palindrome Partitioning", "mid", "backtracking"],
    ["Letter Combinations of a Phone Number", "mid", "backtracking"],
    ["Restore IP Addresses", "mid", "backtracking"],
    ["Pacific Atlantic Water Flow", "mid", "graphs"],
    ["Surrounded Regions", "mid", "graphs"],
    ["Rotting Oranges", "mid", "graphs"],
    ["Walls and Gates", "mid", "graphs"],
    ["Clone Graph Follow-up", "mid", "graphs"],
    ["Course Schedule II", "mid", "graphs"],
    ["Alien Dictionary", "senior", "graphs"],
    ["Graph Valid Tree", "mid", "graphs"],
    ["Number of Connected Components", "mid", "graphs"],
    ["Redundant Connection", "mid", "graphs"],
    ["Word Ladder", "senior", "graphs"],
    ["Word Ladder II", "senior", "graphs"],
    ["Cheapest Flights Within K Stops", "senior", "graphs"],
    ["Network Delay Time", "mid", "graphs"],
    ["Min Cost to Connect All Points", "senior", "graphs"],
    ["Swim in Rising Water", "senior", "graphs"],
    ["Climbing Stairs", "beginner", "dp"],
    ["House Robber", "mid", "dp"],
    ["House Robber II", "mid", "dp"],
    ["Longest Palindromic Substring", "mid", "dp"],
    ["Palindromic Substrings", "mid", "dp"],
    ["Decode Ways", "mid", "dp"],
    ["Coin Change", "mid", "dp"],
    ["Coin Change II", "mid", "dp"],
    ["Word Break", "mid", "dp"],
    ["Word Break II", "senior", "dp"],
    ["Longest Increasing Subsequence", "mid", "dp"],
    ["Partition Equal Subset Sum", "mid", "dp"],
    ["Unique Paths", "mid", "dp"],
    ["Unique Paths II", "mid", "dp"],
    ["Jump Game", "mid", "dp"],
    ["Jump Game II", "mid", "dp"],
    ["Longest Common Subsequence", "mid", "dp"],
    ["Edit Distance", "senior", "dp"],
    ["Burst Balloons", "senior", "dp"],
    ["Regular Expression Matching", "senior", "dp"],
    ["Interleaving String", "senior", "dp"],
    ["Distinct Subsequences", "senior", "dp"],
    ["Maximal Square", "mid", "dp"],
    ["Dungeon Game", "senior", "dp"],
    ["Implement Trie", "mid", "tries"],
    ["Design Add and Search Words", "mid", "tries"],
    ["Word Search II with Trie", "senior", "tries"],
    ["Prefix Tree autocomplete", "mid", "tries"],
    ["Insert Delete GetRandom O(1)", "mid", "design"],
    ["Design HashMap", "mid", "design"],
    ["Design HashSet", "beginner", "design"],
    ["Encode and Decode Strings", "mid", "design"],
    ["Design Browser History", "mid", "design"],
    ["Design Underground System", "mid", "design"],
    ["Snapshot Array", "mid", "design"],
    ["Design a Stack With Increment Operation", "mid", "design"],
  ];

  for (const [title, level, tag] of dsaProblems) {
    add(entry("dsa", level, title, [tag], ["blind75", "gfg"], slugify(title)));
  }

  // FE JS utility / machine coding DSA track
  const feUtils = [
    "Implement once",
    "Implement memoize",
    "Implement pipe and compose",
    "Implement partial",
    "Implement debounce leading edge",
    "Implement throttle trailing edge",
    "Implement sleep / delay",
    "Implement timeout Promise wrapper",
    "Implement Promise.allSettled polyfill",
    "Implement Promise.any polyfill",
    "Implement Promise.race polyfill",
    "Implement retry with backoff",
    "Implement chunk array",
    "Implement groupBy",
    "Implement keyBy",
    "Implement omit and pick",
    "Implement get path lodash-style",
    "Implement set path immutably",
    "Implement deepEqual",
    "Implement deep merge",
    "Implement flatten object keys",
    "Implement unflatten object",
    "Implement classnames utility",
    "Implement qs parse/stringify",
    "Implement cookie parse",
    "Implement LRU in plain JS",
    "Implement pub/sub bus",
    "Implement middleware compose (redux-style)",
    "Implement scheduler for async jobs",
    "Implement rate limiter token bucket",
    "Implement semaphore",
    "Implement async pool / mapLimit",
    "Implement observable mini",
    "Implement immutable update helper",
    "Implement binary search utility",
    "Implement heap/priority queue",
    "Implement linked list utility",
    "Implement tree traversal helpers",
    "Implement topological sort",
    "Implement union-find",
    "Implement trie insert/search",
    "Implement cycle detection",
    "Implement memoized fibonacci",
    "Implement virtual list index math",
    "Implement range sum fenwick (light)",
  ];

  for (const title of feUtils) {
    add(entry("dsa", "mid", title, ["javascript", "utilities"], ["gfe75", "toptalJs"]));
  }

  const uiMachines = [
    "UI: Accordion",
    "UI: Breadcrumbs",
    "UI: Pagination",
    "UI: Star rating",
    "UI: Progress bar",
    "UI: Toast / snackbar",
    "UI: Tooltip",
    "UI: Popover",
    "UI: Combobox",
    "UI: Multi-select",
    "UI: Date picker (simplified)",
    "UI: Time picker",
    "UI: Color picker (simplified)",
    "UI: File upload with preview",
    "UI: Image carousel with a11y",
    "UI: Infinite scroll feed",
    "UI: Virtualized list",
    "UI: Data table with sort",
    "UI: Data table with filter",
    "UI: Transfer list",
    "UI: Nested comments",
    "UI: Nested checkbox tree",
    "UI: Kanban column",
    "UI: Drag-and-drop reorder",
    "UI: Resizable panels",
    "UI: Split pane",
    "UI: Command palette",
    "UI: Markdown previewer",
    "UI: Code editor chrome (read-only)",
    "UI: Chat message list",
    "UI: Presence avatars",
    "UI: Notification center",
    "UI: Shopping cart drawer",
    "UI: Checkout steps wizard",
    "UI: Auth login form",
    "UI: OTP input",
    "UI: Password strength meter",
    "UI: Search with highlight",
    "UI: Autocomplete with keyboard",
    "UI: Tag input",
    "UI: Chip input",
    "UI: Stepper",
    "UI: Timeline",
    "UI: Stats cards",
    "UI: Heatmap calendar",
    "UI: Gantt-lite bars",
    "UI: Org chart (simplified)",
    "UI: Mind map nodes",
    "UI: Whiteboard sticky notes",
    "UI: Poll / voting widget",
    "UI: Like button with optimistic UI",
    "UI: Follow button states",
    "UI: Skeleton loading screens",
    "UI: Empty states",
    "UI: Error boundary fallback UI",
    "UI: Offline banner",
    "UI: Cookie consent banner",
    "UI: Theme toggle",
    "UI: Locale switcher",
    "UI: Sidebar navigation",
    "UI: Mega menu",
    "UI: Responsive nav hamburger",
    "UI: Footer with columns",
    "UI: Pricing table",
    "UI: Feature comparison table",
    "UI: Blog post layout",
    "UI: Comments with replies",
    "UI: Reaction picker",
    "UI: Emoji picker (lite)",
    "UI: Rich text toolbar",
    "UI: Image cropper (lite)",
    "UI: Video player chrome",
    "UI: Audio player chrome",
    "UI: Map marker list sync",
    "UI: Filter chips bar",
    "UI: Faceted search layout",
    "UI: Product gallery",
    "UI: Wishlist heart toggle",
    "UI: Quantity stepper",
    "UI: Coupon code field",
    "UI: Address form autocomplete",
    "UI: Credit card form (no real PAN)",
    "UI: Invoice line items editor",
    "UI: Spreadsheet cell (lite)",
    "UI: Kanban with WIP limits",
    "UI: Calendar month view",
    "UI: Agenda list",
    "UI: Booking slot picker",
    "UI: Airline seat map (lite)",
    "UI: PIN pad",
    "UI: Signature pad (canvas)",
    "UI: Drawing canvas tools",
    "UI: Diff viewer (lite)",
    "UI: JSON tree viewer",
    "UI: Log viewer with filter",
    "UI: Metrics sparkline",
    "UI: Chart legend toggle",
    "UI: Dashboard widget grid",
    "UI: Settings page sections",
    "UI: Profile editor",
    "UI: Avatar upload",
    "UI: Team invite modal",
    "UI: Permission matrix",
    "UI: API key reveal field",
    "UI: Webhook URL tester UI",
    "UI: Feature flag toggles admin",
    "UI: Audit log table",
    "UI: Status page incident banner",
  ];

  for (const title of uiMachines) {
    add(entry("dsa", "mid", title, ["ui-coding"], ["gfe75"]));
  }

  // More DSA via pattern × variant
  const dsaPatterns = [
    "two pointers",
    "sliding window",
    "prefix sums",
    "binary search",
    "stack monotonic",
    "queue",
    "heap",
    "hash map",
    "intervals",
    "linked list",
    "trees DFS",
    "trees BFS",
    "graphs DFS",
    "graphs BFS",
    "union find",
    "topological sort",
    "backtracking",
    "dynamic programming 1D",
    "dynamic programming 2D",
    "greedy",
    "bit manipulation",
    "math",
    "string matching",
    "trie",
    "design",
  ];
  const dsaVariants = [
    "easy warm-up",
    "classic medium",
    "follow-up optimize space",
    "follow-up optimize time",
    "edge cases interview drill",
    "explain complexity aloud",
    "brute force then optimize",
    "identify the pattern first",
    "variant with duplicates",
    "variant with negatives",
    "variant with empty input",
    "streaming / online version",
    "concurrent modification twist",
    "return all answers not one",
    "count solutions instead of list",
    "reconstruct the path",
    "in-place constraint",
    "immutable input constraint",
    "memory-limited twist",
    "whiteboard-friendly version",
  ];

  for (const pattern of dsaPatterns) {
    for (const variant of dsaVariants) {
      const title = `${pattern}: ${variant}`;
      add(
        entry(
          "dsa",
          variant.includes("easy") ? "beginner" : variant.includes("classic") ? "mid" : "senior",
          title,
          [slugify(pattern).split("-")[0] || "dsa"],
          ["blind75", "gfg"],
          `pattern-${slugify(pattern)}--${slugify(variant)}`,
        ),
      );
    }
  }

  // --- System design ---
  const sdProducts = [
    "news feed",
    "autocomplete",
    "chat app",
    "photo sharing",
    "e-commerce PDP",
    "e-commerce cart",
    "video streaming player",
    "music player",
    "ride sharing map UI",
    "food delivery tracking",
    "docs collaborative editor",
    "spreadsheet",
    "presentation slides",
    "email client",
    "calendar",
    "kanban board",
    "issue tracker",
    "design tool canvas",
    "whiteboard",
    "figma-like multiplayer cursor",
    "analytics dashboard",
    "admin console",
    "feature flag console",
    "CMS content editor",
    "blog platform",
    "forum / reddit-like",
    "twitter-like composer",
    "instagram stories",
    "tiktok-like feed",
    "linkedin feed",
    "marketplace search",
    "hotel booking",
    "flight search",
    "maps places search",
    "navigation turn-by-turn UI",
    "banking dashboard",
    "trading watchlist",
    "crypto portfolio",
    "health records portal",
    "telemedicine wait room",
    "education LMS",
    "quiz taking UI",
    "code interview platform",
    "IDE in browser",
    "terminal web UI",
    "CI logs viewer",
    "observability trace UI",
    "incident commander board",
    "status page",
    "docs site with versioning",
    "component explorer",
    "design system portal",
    "notification center",
    "inbox zero mail",
    "file storage drive UI",
    "photo album",
    "password manager vault UI",
    "2FA enrollment flow",
    "onboarding checklist",
    "paywall / subscription",
    "ads creative preview",
    "A/B experiment console",
    "translation management UI",
    "form builder",
    "survey builder",
    "poll live results",
    "webinar room",
    "live sports scores",
    "stock ticker tape",
    "weather app",
    "newsreader offline-first",
    "PWA install experience",
    "multi-tenant admin",
    "SSO settings UI",
    "billing invoices list",
    "usage metering charts",
    "rate limit dashboard",
    "API keys management",
    "webhook debugger",
    "GraphQL explorer",
    "schema registry UI",
    "data catalog search",
    "ML model playground UI",
    "prompt playground",
    "chatbot widget",
    "customer support desk",
    "knowledge base search",
    "community upvotes",
    "moderation queue",
    "content report flow",
    "age gate / consent",
    "cookie preference center",
    "accessibility settings",
    "theme studio",
    "icon browser",
    "font pairing tool",
    "color contrast checker",
    "responsive previewer",
    "visual regression diff UI",
    "performance budget dashboard",
    "RUM analytics UI",
    "error tracking triage",
    "session replay viewer",
    "heatmap overlay",
    "funnel analysis UI",
    "cohort chart UI",
    "SQL notebook frontend",
    "BI pivot table",
    "geo choropleth map",
    "3D product configurator UI",
    "AR try-on overlay (lite)",
    "smart home controls",
    "IoT device list",
    "fleet tracking map",
    "warehouse picker UI",
    "POS terminal UI",
    "kiosk mode app",
    "TV leanback navigation",
    "watch companion UI",
    "email template builder",
    "PDF annotation UI",
    "e-sign flow",
    "contract redline viewer",
    "legal hold admin",
    "HR leave request UI",
    "recruiting ATS board",
    "candidate scorecard",
    "interview loop scheduler",
    "offer letter portal",
  ];

  const sdAngles = [
    "Design the frontend for",
    "RADIO walkthrough:",
    "Scale the UI of",
    "Offline-first approach for",
    "Realtime collaboration in",
    "Accessibility-first design of",
    "Performance budget for",
    "Multi-brand theming in",
    "Mobile + desktop architecture for",
    "Observability plan for",
    "Migration strategy onto",
    "Microfrontend split for",
    "Staff-level ownership of",
    "Principal platform view of",
  ];

  for (const product of sdProducts) {
    for (const angle of sdAngles) {
      const title = `${angle} ${product}`;
      const level: Level = angle.includes("Principal")
        ? "principal"
        : angle.includes("Staff")
          ? "staff"
          : angle.includes("Scale") || angle.includes("Migration") || angle.includes("Microfrontend")
            ? "senior"
            : "mid";
      add(
        entry(
          "system-design",
          level,
          title,
          ["system-design"],
          ["gfeSd"],
          `sd-${slugify(product)}--${slugify(angle)}`,
        ),
      );
    }
  }

  // --- Behaviour ---
  const behThemes = [
    "conflict with a designer",
    "conflict with a PM",
    "disagreement on tech stack",
    "pushing back on scope",
    "missed deadline recovery",
    "production outage you led",
    "rollback decision",
    "feature flag incident",
    "accessibility gap you closed",
    "performance regression you owned",
    "mentoring a struggling teammate",
    "hiring loop debrief",
    "difficult code review",
    "receiving critical feedback",
    "giving critical feedback",
    "cross-team dependency failure",
    "vendor evaluation",
    "build vs buy decision",
    "deprecating a beloved library",
    "leading a migration",
    "introducing TypeScript",
    "introducing testing culture",
    "improving CI times",
    "reducing bundle size org-wide",
    "design system adoption",
    "documenting tribal knowledge",
    "on-call fatigue advocacy",
    "work-life boundary",
    "ambiguous roadmap quarter",
    "prioritizing tech debt",
    "saying no to an executive",
    "aligning with security review",
    "privacy requirement change",
    "internationalization surprise",
    "legacy jQuery island",
    "IE11 sunset communication",
    "React major upgrade",
    "Next.js App Router migration",
    "state management rewrite",
    "CSS architecture rewrite",
    "monorepo migration",
    "microfrontend experiment",
    "failed experiment write-up",
    "successful A/B test",
    "customer escalation",
    "support ticket deep dive",
    "partner API break",
    "rate limit surprise",
    "SEO traffic drop",
    "Core Web Vitals miss",
    "accessibility lawsuit risk",
    "diversity in hiring panel",
    "internship project scoping",
    "staff promotion packet",
    "principal strategy narrative",
    "influencing without authority",
    "creating an RFC culture",
    "office hours for platform",
    "guild / chapter leadership",
    "brown bag teaching series",
    "postmortem facilitation",
    "blameless culture modeling",
    "handling a burn-out signal",
    "remote collaboration friction",
    "timezone distributed team",
    "stakeholder demo gone wrong",
    "under-communicating risk",
    "over-engineering admission",
    "shipping a spike to prod by mistake",
    "data loss near-miss",
    "PII logging incident",
    "token leak in frontend",
    "open source contribution conflict",
    "license compliance issue",
    "vendor lock-in pushback",
    "cost optimization initiative",
    "headcount trade-off",
    "reorg impact on roadmap",
    "manager change mid-project",
    "acting TL temporarily",
    "interviewing a senior candidate",
    "calibrating levels",
    "writing a design doc that landed",
    "design doc that was rejected",
    "pair programming breakthrough",
    "mob programming experiment",
    "quality bar raise",
    "definition of done change",
    "SLA negotiation with backend",
    "contract testing introduction",
    "feature freeze pressure",
    "holiday coverage planning",
    "documentation debt cleanup",
    "runbook creation",
    "chaos day participation",
    "game day for FE failover",
    "multi-region UX issues",
    "dark mode launch",
    "rebrand launch",
    "acquisition integration UI",
    "sunsetting a product surface",
  ];

  const behAngles = [
    "Tell me about a time:",
    "STAR story for",
    "How you handled",
    "Leadership moment:",
    "Reflection on",
    "Staff-level narrative:",
    "What you learned from",
  ];

  for (const theme of behThemes) {
    for (const angle of behAngles) {
      const title = `${angle} ${theme}`;
      const level: Level = angle.includes("Staff")
        ? "staff"
        : theme.includes("principal")
          ? "principal"
          : theme.includes("staff")
            ? "staff"
            : "senior";
      add(
        entry(
          "behaviour",
          level,
          title,
          ["behaviour"],
          ["tihBeh"],
          `beh-${slugify(theme)}--${slugify(angle)}`,
        ),
      );
    }
  }

  // --- Negotiation ---
  const negThemes = [
    "early salary question deflect",
    "current compensation disclosure pressure",
    "leveling down offer",
    "leveling up ask",
    "competing offers timing",
    "exploding offer deadline",
    "best and final response",
    "sign-on bonus ask",
    "equity refresh clarification",
    "RSUs vs options education",
    "strike price questions",
    "401k match negotiation",
    "PTO buy / flexibility",
    "remote work stipend",
    "home office budget",
    "learning budget",
    "conference budget",
    "visa sponsorship clarity",
    "relocation package",
    "start date flexibility",
    "title vs level mismatch",
    "manager soft verbal offer",
    "recruiter range fishing",
    "internal transfer raise",
    "counter to low-ball",
    "total cash vs equity mix",
    "signing while interviewing elsewhere",
    "rescinding risk awareness",
    "team budget constraints empathy",
    "geo pay differential",
    "contracting vs FTE conversion",
    "probation period terms",
    "non-compete pushback",
    "IP assignment concerns",
    "moonlighting policy",
    "second offer leverage ethically",
    "asking for written confirmation",
    "benefits waiting period",
    "parental leave questions",
    "disability accommodations",
    "promotion timeline in writing",
    "scope written into offer",
    "retention bonus mid-loop",
    "refresh grant after counter",
    "performance bonus target",
    "commission / variable pay",
    "founder equity conversation",
    "startup risk premium",
    "public company vs private trade-offs",
    "liquidity event questions",
    "tax implications high-level",
    "relocating countries compensation",
    "currency and FX risk",
    "contractor day rate",
    "agency cut transparency",
    "backchannel reference risk",
    "offer comparison spreadsheet",
    "walk-away rehearsal",
    "gratitude without under-asking",
    "silence after counter",
    "multiple recruiters at same company",
    "bar raiser feedback request",
    "role clarity before numbers",
    "team size and on-call load",
    "career ladder documentation ask",
    "managership vs IC track",
    "staff IC scope confirmation",
    "principal mandate clarity",
    "budgeted headcount band",
    "comp ratio education",
    "market data sources you trust",
    "Levels.fyi caveats",
    "negotiation with internal recruiter",
    "executive recruiter dynamics",
    "hiring manager money talk boundaries",
    "finance 'best final' dynamics",
    "accepting then getting better offer ethics",
    "declining gracefully",
    "renegotiating after start (rare)",
    "equity refresh year two",
    "promotion without raise",
    "title inflation caution",
    "band ceiling awareness",
    "spot bonus after save",
    "retention conversation",
    "comp review cycle timing",
    "new hire parity concerns",
    "asking peers about bands carefully",
    "transparency culture companies",
    "unionized considerations awareness",
    "public sector constraints",
    "nonprofit mission vs pay",
    "academia-to-industry jump",
    "bootcamp grad first offer",
    "senior IC switching domains",
    "manager returning to IC pay",
    "staff hire from smaller company",
    "FAANG to startup haircut",
    "startup to FAANG jump",
  ];

  const negAngles = [
    "Script for",
    "Worksheet:",
    "Practice aloud:",
    "Risks in",
    "Email draft for",
    "Recruiter call:",
    "Decision tree:",
  ];

  for (const theme of negThemes) {
    for (const angle of negAngles) {
      const title = `${angle} ${theme}`;
      add(
        entry(
          "negotiation",
          theme.includes("principal") || theme.includes("staff") ? "staff" : "senior",
          title,
          ["negotiation"],
          ["helloNeg"],
          `neg-${slugify(theme)}--${slugify(angle)}`,
        ),
      );
    }
  }

  // Trim / pad to exactly 1999 *new* relative to existing — we'll filter against existing in merge.
  // Generate extras if short:
  let n = 0;
  while (out.length < 2200) {
    n += 1;
    add(
      entry(
        "quiz",
        "mid",
        `Frontend fundamentals drill #${n}: explain a core browser API`,
        ["javascript", "browser"],
        ["gfe75", "gfg"],
        `fundamentals-drill-${n}`,
      ),
    );
  }

  const outDir = path.join(process.cwd(), "content", "catalog");
  fs.mkdirSync(outDir, { recursive: true });
  const outPath = path.join(outDir, "bulk.json");
  fs.writeFileSync(outPath, JSON.stringify({ generatedAt: new Date().toISOString(), entries: out }, null, 0));
  console.log(`Wrote ${out.length} curated stub titles → ${outPath}`);
}

main();
